// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: reasoning_engine.proto

package reasoningv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReasoningMode int32

const (
	ReasoningMode_REASONING_MODE_UNSPECIFIED ReasoningMode = 0
	ReasoningMode_DIRECT                     ReasoningMode = 1
	ReasoningMode_CHAIN_OF_THOUGHT           ReasoningMode = 2
	ReasoningMode_TREE_OF_THOUGHT            ReasoningMode = 3
	ReasoningMode_REACT                      ReasoningMode = 4
	ReasoningMode_CODE_AS_REASONING          ReasoningMode = 5
	ReasoningMode_DEBATE                     ReasoningMode = 6
)

// Enum value maps for ReasoningMode.
var (
	ReasoningMode_name = map[int32]string{
		0: "REASONING_MODE_UNSPECIFIED",
		1: "DIRECT",
		2: "CHAIN_OF_THOUGHT",
		3: "TREE_OF_THOUGHT",
		4: "REACT",
		5: "CODE_AS_REASONING",
		6: "DEBATE",
	}
	ReasoningMode_value = map[string]int32{
		"REASONING_MODE_UNSPECIFIED": 0,
		"DIRECT":                     1,
		"CHAIN_OF_THOUGHT":           2,
		"TREE_OF_THOUGHT":            3,
		"REACT":                      4,
		"CODE_AS_REASONING":          5,
		"DEBATE":                     6,
	}
)

func (x ReasoningMode) Enum() *ReasoningMode {
	p := new(ReasoningMode)
	*p = x
	return p
}

func (x ReasoningMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReasoningMode) Descriptor() protoreflect.EnumDescriptor {
	return file_reasoning_engine_proto_enumTypes[0].Descriptor()
}

func (ReasoningMode) Type() protoreflect.EnumType {
	return &file_reasoning_engine_proto_enumTypes[0]
}

func (x ReasoningMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReasoningMode.Descriptor instead.
func (ReasoningMode) EnumDescriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{0}
}

type ConvergenceStatus int32

const (
	ConvergenceStatus_CONVERGENCE_STATUS_UNSPECIFIED ConvergenceStatus = 0
	ConvergenceStatus_CONTINUE                       ConvergenceStatus = 1
	ConvergenceStatus_CONVERGED                      ConvergenceStatus = 2
	ConvergenceStatus_BUDGET_EXCEEDED                ConvergenceStatus = 3
	ConvergenceStatus_ESCALATE_TO_HUMAN              ConvergenceStatus = 4
)

// Enum value maps for ConvergenceStatus.
var (
	ConvergenceStatus_name = map[int32]string{
		0: "CONVERGENCE_STATUS_UNSPECIFIED",
		1: "CONTINUE",
		2: "CONVERGED",
		3: "BUDGET_EXCEEDED",
		4: "ESCALATE_TO_HUMAN",
	}
	ConvergenceStatus_value = map[string]int32{
		"CONVERGENCE_STATUS_UNSPECIFIED": 0,
		"CONTINUE":                       1,
		"CONVERGED":                      2,
		"BUDGET_EXCEEDED":                3,
		"ESCALATE_TO_HUMAN":              4,
	}
)

func (x ConvergenceStatus) Enum() *ConvergenceStatus {
	p := new(ConvergenceStatus)
	*p = x
	return p
}

func (x ConvergenceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConvergenceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_reasoning_engine_proto_enumTypes[1].Descriptor()
}

func (ConvergenceStatus) Type() protoreflect.EnumType {
	return &file_reasoning_engine_proto_enumTypes[1]
}

func (x ConvergenceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConvergenceStatus.Descriptor instead.
func (ConvergenceStatus) EnumDescriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{1}
}

type SelectReasoningModeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId       string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TaskBrief         string                 `protobuf:"bytes,2,opt,name=task_brief,json=taskBrief,proto3" json:"task_brief,omitempty"`
	ForcedMode        string                 `protobuf:"bytes,3,opt,name=forced_mode,json=forcedMode,proto3" json:"forced_mode,omitempty"`
	BudgetConstraints *BudgetConstraints     `protobuf:"bytes,4,opt,name=budget_constraints,json=budgetConstraints,proto3" json:"budget_constraints,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SelectReasoningModeRequest) Reset() {
	*x = SelectReasoningModeRequest{}
	mi := &file_reasoning_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectReasoningModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectReasoningModeRequest) ProtoMessage() {}

func (x *SelectReasoningModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectReasoningModeRequest.ProtoReflect.Descriptor instead.
func (*SelectReasoningModeRequest) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{0}
}

func (x *SelectReasoningModeRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *SelectReasoningModeRequest) GetTaskBrief() string {
	if x != nil {
		return x.TaskBrief
	}
	return ""
}

func (x *SelectReasoningModeRequest) GetForcedMode() string {
	if x != nil {
		return x.ForcedMode
	}
	return ""
}

func (x *SelectReasoningModeRequest) GetBudgetConstraints() *BudgetConstraints {
	if x != nil {
		return x.BudgetConstraints
	}
	return nil
}

type BudgetConstraints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxTokens     int64                  `protobuf:"varint,1,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	MaxRounds     int64                  `protobuf:"varint,2,opt,name=max_rounds,json=maxRounds,proto3" json:"max_rounds,omitempty"`
	MaxCost       float64                `protobuf:"fixed64,3,opt,name=max_cost,json=maxCost,proto3" json:"max_cost,omitempty"`
	MaxTimeMs     int64                  `protobuf:"varint,4,opt,name=max_time_ms,json=maxTimeMs,proto3" json:"max_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetConstraints) Reset() {
	*x = BudgetConstraints{}
	mi := &file_reasoning_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetConstraints) ProtoMessage() {}

func (x *BudgetConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetConstraints.ProtoReflect.Descriptor instead.
func (*BudgetConstraints) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{1}
}

func (x *BudgetConstraints) GetMaxTokens() int64 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *BudgetConstraints) GetMaxRounds() int64 {
	if x != nil {
		return x.MaxRounds
	}
	return 0
}

func (x *BudgetConstraints) GetMaxCost() float64 {
	if x != nil {
		return x.MaxCost
	}
	return 0
}

func (x *BudgetConstraints) GetMaxTimeMs() int64 {
	if x != nil {
		return x.MaxTimeMs
	}
	return 0
}

type ReasoningModeConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Mode              ReasoningMode          `protobuf:"varint,1,opt,name=mode,proto3,enum=musematic.reasoning.v1.ReasoningMode" json:"mode,omitempty"`
	ComplexityScore   int32                  `protobuf:"varint,2,opt,name=complexity_score,json=complexityScore,proto3" json:"complexity_score,omitempty"`
	RecommendedBudget *BudgetAllocation      `protobuf:"bytes,3,opt,name=recommended_budget,json=recommendedBudget,proto3" json:"recommended_budget,omitempty"`
	Rationale         string                 `protobuf:"bytes,4,opt,name=rationale,proto3" json:"rationale,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReasoningModeConfig) Reset() {
	*x = ReasoningModeConfig{}
	mi := &file_reasoning_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningModeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningModeConfig) ProtoMessage() {}

func (x *ReasoningModeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningModeConfig.ProtoReflect.Descriptor instead.
func (*ReasoningModeConfig) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{2}
}

func (x *ReasoningModeConfig) GetMode() ReasoningMode {
	if x != nil {
		return x.Mode
	}
	return ReasoningMode_REASONING_MODE_UNSPECIFIED
}

func (x *ReasoningModeConfig) GetComplexityScore() int32 {
	if x != nil {
		return x.ComplexityScore
	}
	return 0
}

func (x *ReasoningModeConfig) GetRecommendedBudget() *BudgetAllocation {
	if x != nil {
		return x.RecommendedBudget
	}
	return nil
}

func (x *ReasoningModeConfig) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

type BudgetAllocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        int64                  `protobuf:"varint,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	Rounds        int64                  `protobuf:"varint,2,opt,name=rounds,proto3" json:"rounds,omitempty"`
	Cost          float64                `protobuf:"fixed64,3,opt,name=cost,proto3" json:"cost,omitempty"`
	TimeMs        int64                  `protobuf:"varint,4,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetAllocation) Reset() {
	*x = BudgetAllocation{}
	mi := &file_reasoning_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetAllocation) ProtoMessage() {}

func (x *BudgetAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetAllocation.ProtoReflect.Descriptor instead.
func (*BudgetAllocation) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{3}
}

func (x *BudgetAllocation) GetTokens() int64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *BudgetAllocation) GetRounds() int64 {
	if x != nil {
		return x.Rounds
	}
	return 0
}

func (x *BudgetAllocation) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *BudgetAllocation) GetTimeMs() int64 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

type AllocateReasoningBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Limits        *BudgetAllocation      `protobuf:"bytes,3,opt,name=limits,proto3" json:"limits,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateReasoningBudgetRequest) Reset() {
	*x = AllocateReasoningBudgetRequest{}
	mi := &file_reasoning_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateReasoningBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateReasoningBudgetRequest) ProtoMessage() {}

func (x *AllocateReasoningBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateReasoningBudgetRequest.ProtoReflect.Descriptor instead.
func (*AllocateReasoningBudgetRequest) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{4}
}

func (x *AllocateReasoningBudgetRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *AllocateReasoningBudgetRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *AllocateReasoningBudgetRequest) GetLimits() *BudgetAllocation {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *AllocateReasoningBudgetRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type ReasoningBudgetEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Limits        *BudgetAllocation      `protobuf:"bytes,3,opt,name=limits,proto3" json:"limits,omitempty"`
	Used          *BudgetAllocation      `protobuf:"bytes,4,opt,name=used,proto3" json:"used,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AllocatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=allocated_at,json=allocatedAt,proto3" json:"allocated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasoningBudgetEnvelope) Reset() {
	*x = ReasoningBudgetEnvelope{}
	mi := &file_reasoning_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningBudgetEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningBudgetEnvelope) ProtoMessage() {}

func (x *ReasoningBudgetEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningBudgetEnvelope.ProtoReflect.Descriptor instead.
func (*ReasoningBudgetEnvelope) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{5}
}

func (x *ReasoningBudgetEnvelope) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ReasoningBudgetEnvelope) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ReasoningBudgetEnvelope) GetLimits() *BudgetAllocation {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *ReasoningBudgetEnvelope) GetUsed() *BudgetAllocation {
	if x != nil {
		return x.Used
	}
	return nil
}

func (x *ReasoningBudgetEnvelope) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReasoningBudgetEnvelope) GetAllocatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AllocatedAt
	}
	return nil
}

type GetBudgetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBudgetStatusRequest) Reset() {
	*x = GetBudgetStatusRequest{}
	mi := &file_reasoning_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBudgetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetStatusRequest) ProtoMessage() {}

func (x *GetBudgetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetBudgetStatusRequest) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{6}
}

func (x *GetBudgetStatusRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *GetBudgetStatusRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

type BudgetStatusResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Envelope      *ReasoningBudgetEnvelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetStatusResponse) Reset() {
	*x = BudgetStatusResponse{}
	mi := &file_reasoning_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetStatusResponse) ProtoMessage() {}

func (x *BudgetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetStatusResponse.ProtoReflect.Descriptor instead.
func (*BudgetStatusResponse) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{7}
}

func (x *BudgetStatusResponse) GetEnvelope() *ReasoningBudgetEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type StreamBudgetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBudgetEventsRequest) Reset() {
	*x = StreamBudgetEventsRequest{}
	mi := &file_reasoning_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBudgetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBudgetEventsRequest) ProtoMessage() {}

func (x *StreamBudgetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBudgetEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamBudgetEventsRequest) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{8}
}

func (x *StreamBudgetEventsRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *StreamBudgetEventsRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

type BudgetEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Dimension     string                 `protobuf:"bytes,4,opt,name=dimension,proto3" json:"dimension,omitempty"`
	CurrentValue  float64                `protobuf:"fixed64,5,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	MaxValue      float64                `protobuf:"fixed64,6,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetEvent) Reset() {
	*x = BudgetEvent{}
	mi := &file_reasoning_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetEvent) ProtoMessage() {}

func (x *BudgetEvent) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetEvent.ProtoReflect.Descriptor instead.
func (*BudgetEvent) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{9}
}

func (x *BudgetEvent) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *BudgetEvent) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *BudgetEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *BudgetEvent) GetDimension() string {
	if x != nil {
		return x.Dimension
	}
	return ""
}

func (x *BudgetEvent) GetCurrentValue() float64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *BudgetEvent) GetMaxValue() float64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *BudgetEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type ReasoningTraceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	SequenceNum   int32                  `protobuf:"varint,5,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasoningTraceEvent) Reset() {
	*x = ReasoningTraceEvent{}
	mi := &file_reasoning_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningTraceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningTraceEvent) ProtoMessage() {}

func (x *ReasoningTraceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningTraceEvent.ProtoReflect.Descriptor instead.
func (*ReasoningTraceEvent) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{10}
}

func (x *ReasoningTraceEvent) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ReasoningTraceEvent) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ReasoningTraceEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ReasoningTraceEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ReasoningTraceEvent) GetSequenceNum() int32 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *ReasoningTraceEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ReasoningTraceEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type ReasoningTraceAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId    string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TotalReceived  int32                  `protobuf:"varint,2,opt,name=total_received,json=totalReceived,proto3" json:"total_received,omitempty"`
	TotalPersisted int32                  `protobuf:"varint,3,opt,name=total_persisted,json=totalPersisted,proto3" json:"total_persisted,omitempty"`
	TotalDropped   int32                  `protobuf:"varint,4,opt,name=total_dropped,json=totalDropped,proto3" json:"total_dropped,omitempty"`
	FailedEventIds []string               `protobuf:"bytes,5,rep,name=failed_event_ids,json=failedEventIds,proto3" json:"failed_event_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReasoningTraceAck) Reset() {
	*x = ReasoningTraceAck{}
	mi := &file_reasoning_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningTraceAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningTraceAck) ProtoMessage() {}

func (x *ReasoningTraceAck) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningTraceAck.ProtoReflect.Descriptor instead.
func (*ReasoningTraceAck) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{11}
}

func (x *ReasoningTraceAck) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ReasoningTraceAck) GetTotalReceived() int32 {
	if x != nil {
		return x.TotalReceived
	}
	return 0
}

func (x *ReasoningTraceAck) GetTotalPersisted() int32 {
	if x != nil {
		return x.TotalPersisted
	}
	return 0
}

func (x *ReasoningTraceAck) GetTotalDropped() int32 {
	if x != nil {
		return x.TotalDropped
	}
	return 0
}

func (x *ReasoningTraceAck) GetFailedEventIds() []string {
	if x != nil {
		return x.FailedEventIds
	}
	return nil
}

type CreateTreeBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TreeId        string                 `protobuf:"bytes,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	BranchId      string                 `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	Hypothesis    string                 `protobuf:"bytes,3,opt,name=hypothesis,proto3" json:"hypothesis,omitempty"`
	BranchBudget  *BudgetAllocation      `protobuf:"bytes,4,opt,name=branch_budget,json=branchBudget,proto3" json:"branch_budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTreeBranchRequest) Reset() {
	*x = CreateTreeBranchRequest{}
	mi := &file_reasoning_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTreeBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTreeBranchRequest) ProtoMessage() {}

func (x *CreateTreeBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTreeBranchRequest.ProtoReflect.Descriptor instead.
func (*CreateTreeBranchRequest) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{12}
}

func (x *CreateTreeBranchRequest) GetTreeId() string {
	if x != nil {
		return x.TreeId
	}
	return ""
}

func (x *CreateTreeBranchRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *CreateTreeBranchRequest) GetHypothesis() string {
	if x != nil {
		return x.Hypothesis
	}
	return ""
}

func (x *CreateTreeBranchRequest) GetBranchBudget() *BudgetAllocation {
	if x != nil {
		return x.BranchBudget
	}
	return nil
}

type TreeBranchHandle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TreeId        string                 `protobuf:"bytes,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	BranchId      string                 `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeBranchHandle) Reset() {
	*x = TreeBranchHandle{}
	mi := &file_reasoning_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeBranchHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeBranchHandle) ProtoMessage() {}

func (x *TreeBranchHandle) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeBranchHandle.ProtoReflect.Descriptor instead.
func (*TreeBranchHandle) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{13}
}

func (x *TreeBranchHandle) GetTreeId() string {
	if x != nil {
		return x.TreeId
	}
	return ""
}

func (x *TreeBranchHandle) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *TreeBranchHandle) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TreeBranchHandle) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type EvaluateTreeBranchesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TreeId          string                 `protobuf:"bytes,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	ScoringFunction string                 `protobuf:"bytes,2,opt,name=scoring_function,json=scoringFunction,proto3" json:"scoring_function,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EvaluateTreeBranchesRequest) Reset() {
	*x = EvaluateTreeBranchesRequest{}
	mi := &file_reasoning_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateTreeBranchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateTreeBranchesRequest) ProtoMessage() {}

func (x *EvaluateTreeBranchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateTreeBranchesRequest.ProtoReflect.Descriptor instead.
func (*EvaluateTreeBranchesRequest) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{14}
}

func (x *EvaluateTreeBranchesRequest) GetTreeId() string {
	if x != nil {
		return x.TreeId
	}
	return ""
}

func (x *EvaluateTreeBranchesRequest) GetScoringFunction() string {
	if x != nil {
		return x.ScoringFunction
	}
	return ""
}

type BranchSelectionResult struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SelectedBranchId    string                 `protobuf:"bytes,1,opt,name=selected_branch_id,json=selectedBranchId,proto3" json:"selected_branch_id,omitempty"`
	SelectedQuality     float64                `protobuf:"fixed64,2,opt,name=selected_quality,json=selectedQuality,proto3" json:"selected_quality,omitempty"`
	SelectedTokenCost   int64                  `protobuf:"varint,3,opt,name=selected_token_cost,json=selectedTokenCost,proto3" json:"selected_token_cost,omitempty"`
	AllBranches         []*BranchSummary       `protobuf:"bytes,4,rep,name=all_branches,json=allBranches,proto3" json:"all_branches,omitempty"`
	NoViableBranches    bool                   `protobuf:"varint,5,opt,name=no_viable_branches,json=noViableBranches,proto3" json:"no_viable_branches,omitempty"`
	BestPartialBranchId string                 `protobuf:"bytes,6,opt,name=best_partial_branch_id,json=bestPartialBranchId,proto3" json:"best_partial_branch_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BranchSelectionResult) Reset() {
	*x = BranchSelectionResult{}
	mi := &file_reasoning_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchSelectionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchSelectionResult) ProtoMessage() {}

func (x *BranchSelectionResult) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchSelectionResult.ProtoReflect.Descriptor instead.
func (*BranchSelectionResult) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{15}
}

func (x *BranchSelectionResult) GetSelectedBranchId() string {
	if x != nil {
		return x.SelectedBranchId
	}
	return ""
}

func (x *BranchSelectionResult) GetSelectedQuality() float64 {
	if x != nil {
		return x.SelectedQuality
	}
	return 0
}

func (x *BranchSelectionResult) GetSelectedTokenCost() int64 {
	if x != nil {
		return x.SelectedTokenCost
	}
	return 0
}

func (x *BranchSelectionResult) GetAllBranches() []*BranchSummary {
	if x != nil {
		return x.AllBranches
	}
	return nil
}

func (x *BranchSelectionResult) GetNoViableBranches() bool {
	if x != nil {
		return x.NoViableBranches
	}
	return false
}

func (x *BranchSelectionResult) GetBestPartialBranchId() string {
	if x != nil {
		return x.BestPartialBranchId
	}
	return ""
}

type BranchSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BranchId      string                 `protobuf:"bytes,1,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	Hypothesis    string                 `protobuf:"bytes,2,opt,name=hypothesis,proto3" json:"hypothesis,omitempty"`
	QualityScore  float64                `protobuf:"fixed64,3,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	TokenCost     int64                  `protobuf:"varint,4,opt,name=token_cost,json=tokenCost,proto3" json:"token_cost,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Score         float64                `protobuf:"fixed64,6,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BranchSummary) Reset() {
	*x = BranchSummary{}
	mi := &file_reasoning_engine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchSummary) ProtoMessage() {}

func (x *BranchSummary) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchSummary.ProtoReflect.Descriptor instead.
func (*BranchSummary) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{16}
}

func (x *BranchSummary) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *BranchSummary) GetHypothesis() string {
	if x != nil {
		return x.Hypothesis
	}
	return ""
}

func (x *BranchSummary) GetQualityScore() float64 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *BranchSummary) GetTokenCost() int64 {
	if x != nil {
		return x.TokenCost
	}
	return 0
}

func (x *BranchSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BranchSummary) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type StartSelfCorrectionRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	LoopId                   string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	ExecutionId              string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	MaxIterations            int32                  `protobuf:"varint,3,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	CostCap                  float64                `protobuf:"fixed64,4,opt,name=cost_cap,json=costCap,proto3" json:"cost_cap,omitempty"`
	Epsilon                  float64                `protobuf:"fixed64,5,opt,name=epsilon,proto3" json:"epsilon,omitempty"`
	EscalateOnBudgetExceeded bool                   `protobuf:"varint,6,opt,name=escalate_on_budget_exceeded,json=escalateOnBudgetExceeded,proto3" json:"escalate_on_budget_exceeded,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *StartSelfCorrectionRequest) Reset() {
	*x = StartSelfCorrectionRequest{}
	mi := &file_reasoning_engine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSelfCorrectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSelfCorrectionRequest) ProtoMessage() {}

func (x *StartSelfCorrectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSelfCorrectionRequest.ProtoReflect.Descriptor instead.
func (*StartSelfCorrectionRequest) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{17}
}

func (x *StartSelfCorrectionRequest) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

func (x *StartSelfCorrectionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *StartSelfCorrectionRequest) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *StartSelfCorrectionRequest) GetCostCap() float64 {
	if x != nil {
		return x.CostCap
	}
	return 0
}

func (x *StartSelfCorrectionRequest) GetEpsilon() float64 {
	if x != nil {
		return x.Epsilon
	}
	return 0
}

func (x *StartSelfCorrectionRequest) GetEscalateOnBudgetExceeded() bool {
	if x != nil {
		return x.EscalateOnBudgetExceeded
	}
	return false
}

type SelfCorrectionHandle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopId        string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfCorrectionHandle) Reset() {
	*x = SelfCorrectionHandle{}
	mi := &file_reasoning_engine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfCorrectionHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfCorrectionHandle) ProtoMessage() {}

func (x *SelfCorrectionHandle) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfCorrectionHandle.ProtoReflect.Descriptor instead.
func (*SelfCorrectionHandle) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{18}
}

func (x *SelfCorrectionHandle) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

func (x *SelfCorrectionHandle) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SelfCorrectionHandle) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type CorrectionIterationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopId        string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	QualityScore  float64                `protobuf:"fixed64,2,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	Cost          float64                `protobuf:"fixed64,3,opt,name=cost,proto3" json:"cost,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorrectionIterationEvent) Reset() {
	*x = CorrectionIterationEvent{}
	mi := &file_reasoning_engine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrectionIterationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrectionIterationEvent) ProtoMessage() {}

func (x *CorrectionIterationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrectionIterationEvent.ProtoReflect.Descriptor instead.
func (*CorrectionIterationEvent) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{19}
}

func (x *CorrectionIterationEvent) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

func (x *CorrectionIterationEvent) GetQualityScore() float64 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *CorrectionIterationEvent) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *CorrectionIterationEvent) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ConvergenceResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ConvergenceStatus      `protobuf:"varint,1,opt,name=status,proto3,enum=musematic.reasoning.v1.ConvergenceStatus" json:"status,omitempty"`
	IterationNum  int32                  `protobuf:"varint,2,opt,name=iteration_num,json=iterationNum,proto3" json:"iteration_num,omitempty"`
	Delta         float64                `protobuf:"fixed64,3,opt,name=delta,proto3" json:"delta,omitempty"`
	LoopId        string                 `protobuf:"bytes,4,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvergenceResult) Reset() {
	*x = ConvergenceResult{}
	mi := &file_reasoning_engine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvergenceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvergenceResult) ProtoMessage() {}

func (x *ConvergenceResult) ProtoReflect() protoreflect.Message {
	mi := &file_reasoning_engine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvergenceResult.ProtoReflect.Descriptor instead.
func (*ConvergenceResult) Descriptor() ([]byte, []int) {
	return file_reasoning_engine_proto_rawDescGZIP(), []int{20}
}

func (x *ConvergenceResult) GetStatus() ConvergenceStatus {
	if x != nil {
		return x.Status
	}
	return ConvergenceStatus_CONVERGENCE_STATUS_UNSPECIFIED
}

func (x *ConvergenceResult) GetIterationNum() int32 {
	if x != nil {
		return x.IterationNum
	}
	return 0
}

func (x *ConvergenceResult) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *ConvergenceResult) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

var File_reasoning_engine_proto protoreflect.FileDescriptor

const file_reasoning_engine_proto_rawDesc = "" +
	"\n" +
	"\x16reasoning_engine.proto\x12\x16musematic.reasoning.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x01\n" +
	"\x1aSelectReasoningModeRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1d\n" +
	"\n" +
	"task_brief\x18\x02 \x01(\tR\ttaskBrief\x12\x1f\n" +
	"\vforced_mode\x18\x03 \x01(\tR\n" +
	"forcedMode\x12X\n" +
	"\x12budget_constraints\x18\x04 \x01(\v2).musematic.reasoning.v1.BudgetConstraintsR\x11budgetConstraints\"\x8c\x01\n" +
	"\x11BudgetConstraints\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x01 \x01(\x03R\tmaxTokens\x12\x1d\n" +
	"\n" +
	"max_rounds\x18\x02 \x01(\x03R\tmaxRounds\x12\x19\n" +
	"\bmax_cost\x18\x03 \x01(\x01R\amaxCost\x12\x1e\n" +
	"\vmax_time_ms\x18\x04 \x01(\x03R\tmaxTimeMs\"\xf2\x01\n" +
	"\x13ReasoningModeConfig\x129\n" +
	"\x04mode\x18\x01 \x01(\x0e2%.musematic.reasoning.v1.ReasoningModeR\x04mode\x12)\n" +
	"\x10complexity_score\x18\x02 \x01(\x05R\x0fcomplexityScore\x12W\n" +
	"\x12recommended_budget\x18\x03 \x01(\v2(.musematic.reasoning.v1.BudgetAllocationR\x11recommendedBudget\x12\x1c\n" +
	"\trationale\x18\x04 \x01(\tR\trationale\"o\n" +
	"\x10BudgetAllocation\x12\x16\n" +
	"\x06tokens\x18\x01 \x01(\x03R\x06tokens\x12\x16\n" +
	"\x06rounds\x18\x02 \x01(\x03R\x06rounds\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x01R\x04cost\x12\x17\n" +
	"\atime_ms\x18\x04 \x01(\x03R\x06timeMs\"\xbf\x01\n" +
	"\x1eAllocateReasoningBudgetRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12@\n" +
	"\x06limits\x18\x03 \x01(\v2(.musematic.reasoning.v1.BudgetAllocationR\x06limits\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x03R\n" +
	"ttlSeconds\"\xac\x02\n" +
	"\x17ReasoningBudgetEnvelope\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12@\n" +
	"\x06limits\x18\x03 \x01(\v2(.musematic.reasoning.v1.BudgetAllocationR\x06limits\x12<\n" +
	"\x04used\x18\x04 \x01(\v2(.musematic.reasoning.v1.BudgetAllocationR\x04used\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12=\n" +
	"\fallocated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vallocatedAt\"T\n" +
	"\x16GetBudgetStatusRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\"c\n" +
	"\x14BudgetStatusResponse\x12K\n" +
	"\benvelope\x18\x01 \x01(\v2/.musematic.reasoning.v1.ReasoningBudgetEnvelopeR\benvelope\"W\n" +
	"\x19StreamBudgetEventsRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\"\x85\x02\n" +
	"\vBudgetEvent\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1c\n" +
	"\tdimension\x18\x04 \x01(\tR\tdimension\x12#\n" +
	"\rcurrent_value\x18\x05 \x01(\x01R\fcurrentValue\x12\x1b\n" +
	"\tmax_value\x18\x06 \x01(\x01R\bmaxValue\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\x85\x02\n" +
	"\x13ReasoningTraceEvent\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12!\n" +
	"\fsequence_num\x18\x05 \x01(\x05R\vsequenceNum\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xd5\x01\n" +
	"\x11ReasoningTraceAck\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12%\n" +
	"\x0etotal_received\x18\x02 \x01(\x05R\rtotalReceived\x12'\n" +
	"\x0ftotal_persisted\x18\x03 \x01(\x05R\x0etotalPersisted\x12#\n" +
	"\rtotal_dropped\x18\x04 \x01(\x05R\ftotalDropped\x12(\n" +
	"\x10failed_event_ids\x18\x05 \x03(\tR\x0efailedEventIds\"\xbe\x01\n" +
	"\x17CreateTreeBranchRequest\x12\x17\n" +
	"\atree_id\x18\x01 \x01(\tR\x06treeId\x12\x1b\n" +
	"\tbranch_id\x18\x02 \x01(\tR\bbranchId\x12\x1e\n" +
	"\n" +
	"hypothesis\x18\x03 \x01(\tR\n" +
	"hypothesis\x12M\n" +
	"\rbranch_budget\x18\x04 \x01(\v2(.musematic.reasoning.v1.BudgetAllocationR\fbranchBudget\"\x9b\x01\n" +
	"\x10TreeBranchHandle\x12\x17\n" +
	"\atree_id\x18\x01 \x01(\tR\x06treeId\x12\x1b\n" +
	"\tbranch_id\x18\x02 \x01(\tR\bbranchId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"a\n" +
	"\x1bEvaluateTreeBranchesRequest\x12\x17\n" +
	"\atree_id\x18\x01 \x01(\tR\x06treeId\x12)\n" +
	"\x10scoring_function\x18\x02 \x01(\tR\x0fscoringFunction\"\xcd\x02\n" +
	"\x15BranchSelectionResult\x12,\n" +
	"\x12selected_branch_id\x18\x01 \x01(\tR\x10selectedBranchId\x12)\n" +
	"\x10selected_quality\x18\x02 \x01(\x01R\x0fselectedQuality\x12.\n" +
	"\x13selected_token_cost\x18\x03 \x01(\x03R\x11selectedTokenCost\x12H\n" +
	"\fall_branches\x18\x04 \x03(\v2%.musematic.reasoning.v1.BranchSummaryR\vallBranches\x12,\n" +
	"\x12no_viable_branches\x18\x05 \x01(\bR\x10noViableBranches\x123\n" +
	"\x16best_partial_branch_id\x18\x06 \x01(\tR\x13bestPartialBranchId\"\xbe\x01\n" +
	"\rBranchSummary\x12\x1b\n" +
	"\tbranch_id\x18\x01 \x01(\tR\bbranchId\x12\x1e\n" +
	"\n" +
	"hypothesis\x18\x02 \x01(\tR\n" +
	"hypothesis\x12#\n" +
	"\rquality_score\x18\x03 \x01(\x01R\fqualityScore\x12\x1d\n" +
	"\n" +
	"token_cost\x18\x04 \x01(\x03R\ttokenCost\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x01R\x05score\"\xf3\x01\n" +
	"\x1aStartSelfCorrectionRequest\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12%\n" +
	"\x0emax_iterations\x18\x03 \x01(\x05R\rmaxIterations\x12\x19\n" +
	"\bcost_cap\x18\x04 \x01(\x01R\acostCap\x12\x18\n" +
	"\aepsilon\x18\x05 \x01(\x01R\aepsilon\x12=\n" +
	"\x1bescalate_on_budget_exceeded\x18\x06 \x01(\bR\x18escalateOnBudgetExceeded\"\x82\x01\n" +
	"\x14SelfCorrectionHandle\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\x8d\x01\n" +
	"\x18CorrectionIterationEvent\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\x12#\n" +
	"\rquality_score\x18\x02 \x01(\x01R\fqualityScore\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x01R\x04cost\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"\xaa\x01\n" +
	"\x11ConvergenceResult\x12A\n" +
	"\x06status\x18\x01 \x01(\x0e2).musematic.reasoning.v1.ConvergenceStatusR\x06status\x12#\n" +
	"\riteration_num\x18\x02 \x01(\x05R\fiterationNum\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x01R\x05delta\x12\x17\n" +
	"\aloop_id\x18\x04 \x01(\tR\x06loopId*\x94\x01\n" +
	"\rReasoningMode\x12\x1e\n" +
	"\x1aREASONING_MODE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06DIRECT\x10\x01\x12\x14\n" +
	"\x10CHAIN_OF_THOUGHT\x10\x02\x12\x13\n" +
	"\x0fTREE_OF_THOUGHT\x10\x03\x12\t\n" +
	"\x05REACT\x10\x04\x12\x15\n" +
	"\x11CODE_AS_REASONING\x10\x05\x12\n" +
	"\n" +
	"\x06DEBATE\x10\x06*\x80\x01\n" +
	"\x11ConvergenceStatus\x12\"\n" +
	"\x1eCONVERGENCE_STATUS_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCONTINUE\x10\x01\x12\r\n" +
	"\tCONVERGED\x10\x02\x12\x13\n" +
	"\x0fBUDGET_EXCEEDED\x10\x03\x12\x15\n" +
	"\x11ESCALATE_TO_HUMAN\x10\x042\xd3\b\n" +
	"\x16ReasoningEngineService\x12v\n" +
	"\x13SelectReasoningMode\x122.musematic.reasoning.v1.SelectReasoningModeRequest\x1a+.musematic.reasoning.v1.ReasoningModeConfig\x12\x82\x01\n" +
	"\x17AllocateReasoningBudget\x126.musematic.reasoning.v1.AllocateReasoningBudgetRequest\x1a/.musematic.reasoning.v1.ReasoningBudgetEnvelope\x12x\n" +
	"\x18GetReasoningBudgetStatus\x12..musematic.reasoning.v1.GetBudgetStatusRequest\x1a,.musematic.reasoning.v1.BudgetStatusResponse\x12n\n" +
	"\x12StreamBudgetEvents\x121.musematic.reasoning.v1.StreamBudgetEventsRequest\x1a#.musematic.reasoning.v1.BudgetEvent0\x01\x12p\n" +
	"\x14StreamReasoningTrace\x12+.musematic.reasoning.v1.ReasoningTraceEvent\x1a).musematic.reasoning.v1.ReasoningTraceAck(\x01\x12m\n" +
	"\x10CreateTreeBranch\x12/.musematic.reasoning.v1.CreateTreeBranchRequest\x1a(.musematic.reasoning.v1.TreeBranchHandle\x12z\n" +
	"\x14EvaluateTreeBranches\x123.musematic.reasoning.v1.EvaluateTreeBranchesRequest\x1a-.musematic.reasoning.v1.BranchSelectionResult\x12{\n" +
	"\x17StartSelfCorrectionLoop\x122.musematic.reasoning.v1.StartSelfCorrectionRequest\x1a,.musematic.reasoning.v1.SelfCorrectionHandle\x12x\n" +
	"\x19SubmitCorrectionIteration\x120.musematic.reasoning.v1.CorrectionIterationEvent\x1a).musematic.reasoning.v1.ConvergenceResultB?Z=github.com/musematic/reasoning-engine/api/grpc/v1;reasoningv1b\x06proto3"

var (
	file_reasoning_engine_proto_rawDescOnce sync.Once
	file_reasoning_engine_proto_rawDescData []byte
)

func file_reasoning_engine_proto_rawDescGZIP() []byte {
	file_reasoning_engine_proto_rawDescOnce.Do(func() {
		file_reasoning_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reasoning_engine_proto_rawDesc), len(file_reasoning_engine_proto_rawDesc)))
	})
	return file_reasoning_engine_proto_rawDescData
}

var file_reasoning_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_reasoning_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_reasoning_engine_proto_goTypes = []any{
	(ReasoningMode)(0),                     // 0: musematic.reasoning.v1.ReasoningMode
	(ConvergenceStatus)(0),                 // 1: musematic.reasoning.v1.ConvergenceStatus
	(*SelectReasoningModeRequest)(nil),     // 2: musematic.reasoning.v1.SelectReasoningModeRequest
	(*BudgetConstraints)(nil),              // 3: musematic.reasoning.v1.BudgetConstraints
	(*ReasoningModeConfig)(nil),            // 4: musematic.reasoning.v1.ReasoningModeConfig
	(*BudgetAllocation)(nil),               // 5: musematic.reasoning.v1.BudgetAllocation
	(*AllocateReasoningBudgetRequest)(nil), // 6: musematic.reasoning.v1.AllocateReasoningBudgetRequest
	(*ReasoningBudgetEnvelope)(nil),        // 7: musematic.reasoning.v1.ReasoningBudgetEnvelope
	(*GetBudgetStatusRequest)(nil),         // 8: musematic.reasoning.v1.GetBudgetStatusRequest
	(*BudgetStatusResponse)(nil),           // 9: musematic.reasoning.v1.BudgetStatusResponse
	(*StreamBudgetEventsRequest)(nil),      // 10: musematic.reasoning.v1.StreamBudgetEventsRequest
	(*BudgetEvent)(nil),                    // 11: musematic.reasoning.v1.BudgetEvent
	(*ReasoningTraceEvent)(nil),            // 12: musematic.reasoning.v1.ReasoningTraceEvent
	(*ReasoningTraceAck)(nil),              // 13: musematic.reasoning.v1.ReasoningTraceAck
	(*CreateTreeBranchRequest)(nil),        // 14: musematic.reasoning.v1.CreateTreeBranchRequest
	(*TreeBranchHandle)(nil),               // 15: musematic.reasoning.v1.TreeBranchHandle
	(*EvaluateTreeBranchesRequest)(nil),    // 16: musematic.reasoning.v1.EvaluateTreeBranchesRequest
	(*BranchSelectionResult)(nil),          // 17: musematic.reasoning.v1.BranchSelectionResult
	(*BranchSummary)(nil),                  // 18: musematic.reasoning.v1.BranchSummary
	(*StartSelfCorrectionRequest)(nil),     // 19: musematic.reasoning.v1.StartSelfCorrectionRequest
	(*SelfCorrectionHandle)(nil),           // 20: musematic.reasoning.v1.SelfCorrectionHandle
	(*CorrectionIterationEvent)(nil),       // 21: musematic.reasoning.v1.CorrectionIterationEvent
	(*ConvergenceResult)(nil),              // 22: musematic.reasoning.v1.ConvergenceResult
	(*timestamppb.Timestamp)(nil),          // 23: google.protobuf.Timestamp
}
var file_reasoning_engine_proto_depIdxs = []int32{
	3,  // 0: musematic.reasoning.v1.SelectReasoningModeRequest.budget_constraints:type_name -> musematic.reasoning.v1.BudgetConstraints
	0,  // 1: musematic.reasoning.v1.ReasoningModeConfig.mode:type_name -> musematic.reasoning.v1.ReasoningMode
	5,  // 2: musematic.reasoning.v1.ReasoningModeConfig.recommended_budget:type_name -> musematic.reasoning.v1.BudgetAllocation
	5,  // 3: musematic.reasoning.v1.AllocateReasoningBudgetRequest.limits:type_name -> musematic.reasoning.v1.BudgetAllocation
	5,  // 4: musematic.reasoning.v1.ReasoningBudgetEnvelope.limits:type_name -> musematic.reasoning.v1.BudgetAllocation
	5,  // 5: musematic.reasoning.v1.ReasoningBudgetEnvelope.used:type_name -> musematic.reasoning.v1.BudgetAllocation
	23, // 6: musematic.reasoning.v1.ReasoningBudgetEnvelope.allocated_at:type_name -> google.protobuf.Timestamp
	7,  // 7: musematic.reasoning.v1.BudgetStatusResponse.envelope:type_name -> musematic.reasoning.v1.ReasoningBudgetEnvelope
	23, // 8: musematic.reasoning.v1.BudgetEvent.occurred_at:type_name -> google.protobuf.Timestamp
	23, // 9: musematic.reasoning.v1.ReasoningTraceEvent.occurred_at:type_name -> google.protobuf.Timestamp
	5,  // 10: musematic.reasoning.v1.CreateTreeBranchRequest.branch_budget:type_name -> musematic.reasoning.v1.BudgetAllocation
	23, // 11: musematic.reasoning.v1.TreeBranchHandle.created_at:type_name -> google.protobuf.Timestamp
	18, // 12: musematic.reasoning.v1.BranchSelectionResult.all_branches:type_name -> musematic.reasoning.v1.BranchSummary
	23, // 13: musematic.reasoning.v1.SelfCorrectionHandle.started_at:type_name -> google.protobuf.Timestamp
	1,  // 14: musematic.reasoning.v1.ConvergenceResult.status:type_name -> musematic.reasoning.v1.ConvergenceStatus
	2,  // 15: musematic.reasoning.v1.ReasoningEngineService.SelectReasoningMode:input_type -> musematic.reasoning.v1.SelectReasoningModeRequest
	6,  // 16: musematic.reasoning.v1.ReasoningEngineService.AllocateReasoningBudget:input_type -> musematic.reasoning.v1.AllocateReasoningBudgetRequest
	8,  // 17: musematic.reasoning.v1.ReasoningEngineService.GetReasoningBudgetStatus:input_type -> musematic.reasoning.v1.GetBudgetStatusRequest
	10, // 18: musematic.reasoning.v1.ReasoningEngineService.StreamBudgetEvents:input_type -> musematic.reasoning.v1.StreamBudgetEventsRequest
	12, // 19: musematic.reasoning.v1.ReasoningEngineService.StreamReasoningTrace:input_type -> musematic.reasoning.v1.ReasoningTraceEvent
	14, // 20: musematic.reasoning.v1.ReasoningEngineService.CreateTreeBranch:input_type -> musematic.reasoning.v1.CreateTreeBranchRequest
	16, // 21: musematic.reasoning.v1.ReasoningEngineService.EvaluateTreeBranches:input_type -> musematic.reasoning.v1.EvaluateTreeBranchesRequest
	19, // 22: musematic.reasoning.v1.ReasoningEngineService.StartSelfCorrectionLoop:input_type -> musematic.reasoning.v1.StartSelfCorrectionRequest
	21, // 23: musematic.reasoning.v1.ReasoningEngineService.SubmitCorrectionIteration:input_type -> musematic.reasoning.v1.CorrectionIterationEvent
	4,  // 24: musematic.reasoning.v1.ReasoningEngineService.SelectReasoningMode:output_type -> musematic.reasoning.v1.ReasoningModeConfig
	7,  // 25: musematic.reasoning.v1.ReasoningEngineService.AllocateReasoningBudget:output_type -> musematic.reasoning.v1.ReasoningBudgetEnvelope
	9,  // 26: musematic.reasoning.v1.ReasoningEngineService.GetReasoningBudgetStatus:output_type -> musematic.reasoning.v1.BudgetStatusResponse
	11, // 27: musematic.reasoning.v1.ReasoningEngineService.StreamBudgetEvents:output_type -> musematic.reasoning.v1.BudgetEvent
	13, // 28: musematic.reasoning.v1.ReasoningEngineService.StreamReasoningTrace:output_type -> musematic.reasoning.v1.ReasoningTraceAck
	15, // 29: musematic.reasoning.v1.ReasoningEngineService.CreateTreeBranch:output_type -> musematic.reasoning.v1.TreeBranchHandle
	17, // 30: musematic.reasoning.v1.ReasoningEngineService.EvaluateTreeBranches:output_type -> musematic.reasoning.v1.BranchSelectionResult
	20, // 31: musematic.reasoning.v1.ReasoningEngineService.StartSelfCorrectionLoop:output_type -> musematic.reasoning.v1.SelfCorrectionHandle
	22, // 32: musematic.reasoning.v1.ReasoningEngineService.SubmitCorrectionIteration:output_type -> musematic.reasoning.v1.ConvergenceResult
	24, // [24:33] is the sub-list for method output_type
	15, // [15:24] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_reasoning_engine_proto_init() }
func file_reasoning_engine_proto_init() {
	if File_reasoning_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reasoning_engine_proto_rawDesc), len(file_reasoning_engine_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reasoning_engine_proto_goTypes,
		DependencyIndexes: file_reasoning_engine_proto_depIdxs,
		EnumInfos:         file_reasoning_engine_proto_enumTypes,
		MessageInfos:      file_reasoning_engine_proto_msgTypes,
	}.Build()
	File_reasoning_engine_proto = out.File
	file_reasoning_engine_proto_goTypes = nil
	file_reasoning_engine_proto_depIdxs = nil
}
