// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: reasoning_engine.proto

package reasoningv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReasoningEngineService_SelectReasoningMode_FullMethodName       = "/musematic.reasoning.v1.ReasoningEngineService/SelectReasoningMode"
	ReasoningEngineService_AllocateReasoningBudget_FullMethodName   = "/musematic.reasoning.v1.ReasoningEngineService/AllocateReasoningBudget"
	ReasoningEngineService_GetReasoningBudgetStatus_FullMethodName  = "/musematic.reasoning.v1.ReasoningEngineService/GetReasoningBudgetStatus"
	ReasoningEngineService_StreamBudgetEvents_FullMethodName        = "/musematic.reasoning.v1.ReasoningEngineService/StreamBudgetEvents"
	ReasoningEngineService_StreamReasoningTrace_FullMethodName      = "/musematic.reasoning.v1.ReasoningEngineService/StreamReasoningTrace"
	ReasoningEngineService_CreateTreeBranch_FullMethodName          = "/musematic.reasoning.v1.ReasoningEngineService/CreateTreeBranch"
	ReasoningEngineService_EvaluateTreeBranches_FullMethodName      = "/musematic.reasoning.v1.ReasoningEngineService/EvaluateTreeBranches"
	ReasoningEngineService_StartDebateSession_FullMethodName        = "/musematic.reasoning.v1.ReasoningEngineService/StartDebateSession"
	ReasoningEngineService_SubmitDebateTurn_FullMethodName          = "/musematic.reasoning.v1.ReasoningEngineService/SubmitDebateTurn"
	ReasoningEngineService_FinalizeDebateSession_FullMethodName     = "/musematic.reasoning.v1.ReasoningEngineService/FinalizeDebateSession"
	ReasoningEngineService_StartSelfCorrectionLoop_FullMethodName   = "/musematic.reasoning.v1.ReasoningEngineService/StartSelfCorrectionLoop"
	ReasoningEngineService_SubmitCorrectionIteration_FullMethodName = "/musematic.reasoning.v1.ReasoningEngineService/SubmitCorrectionIteration"
	ReasoningEngineService_GetReasoningTrace_FullMethodName         = "/musematic.reasoning.v1.ReasoningEngineService/GetReasoningTrace"
)

// ReasoningEngineServiceClient is the client API for ReasoningEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReasoningEngineServiceClient interface {
	SelectReasoningMode(ctx context.Context, in *SelectReasoningModeRequest, opts ...grpc.CallOption) (*ReasoningModeConfig, error)
	AllocateReasoningBudget(ctx context.Context, in *AllocateReasoningBudgetRequest, opts ...grpc.CallOption) (*ReasoningBudgetEnvelope, error)
	GetReasoningBudgetStatus(ctx context.Context, in *GetBudgetStatusRequest, opts ...grpc.CallOption) (*BudgetStatusResponse, error)
	StreamBudgetEvents(ctx context.Context, in *StreamBudgetEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BudgetEvent], error)
	StreamReasoningTrace(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ReasoningTraceEvent, ReasoningTraceAck], error)
	CreateTreeBranch(ctx context.Context, in *CreateTreeBranchRequest, opts ...grpc.CallOption) (*TreeBranchHandle, error)
	EvaluateTreeBranches(ctx context.Context, in *EvaluateTreeBranchesRequest, opts ...grpc.CallOption) (*BranchSelectionResult, error)
	StartDebateSession(ctx context.Context, in *StartDebateSessionRequest, opts ...grpc.CallOption) (*DebateSessionHandle, error)
	SubmitDebateTurn(ctx context.Context, in *SubmitDebateTurnRequest, opts ...grpc.CallOption) (*DebateRoundResult, error)
	FinalizeDebateSession(ctx context.Context, in *FinalizeDebateSessionRequest, opts ...grpc.CallOption) (*DebateSessionResult, error)
	StartSelfCorrectionLoop(ctx context.Context, in *StartSelfCorrectionRequest, opts ...grpc.CallOption) (*SelfCorrectionHandle, error)
	SubmitCorrectionIteration(ctx context.Context, in *CorrectionIterationEvent, opts ...grpc.CallOption) (*ConvergenceResult, error)
	GetReasoningTrace(ctx context.Context, in *GetReasoningTraceRequest, opts ...grpc.CallOption) (*GetReasoningTraceResponse, error)
}

type reasoningEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReasoningEngineServiceClient(cc grpc.ClientConnInterface) ReasoningEngineServiceClient {
	return &reasoningEngineServiceClient{cc}
}

func (c *reasoningEngineServiceClient) SelectReasoningMode(ctx context.Context, in *SelectReasoningModeRequest, opts ...grpc.CallOption) (*ReasoningModeConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReasoningModeConfig)
	err := c.cc.Invoke(ctx, ReasoningEngineService_SelectReasoningMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reasoningEngineServiceClient) AllocateReasoningBudget(ctx context.Context, in *AllocateReasoningBudgetRequest, opts ...grpc.CallOption) (*ReasoningBudgetEnvelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReasoningBudgetEnvelope)
	err := c.cc.Invoke(ctx, ReasoningEngineService_AllocateReasoningBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reasoningEngineServiceClient) GetReasoningBudgetStatus(ctx context.Context, in *GetBudgetStatusRequest, opts ...grpc.CallOption) (*BudgetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BudgetStatusResponse)
	err := c.cc.Invoke(ctx, ReasoningEngineService_GetReasoningBudgetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reasoningEngineServiceClient) StreamBudgetEvents(ctx context.Context, in *StreamBudgetEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BudgetEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReasoningEngineService_ServiceDesc.Streams[0], ReasoningEngineService_StreamBudgetEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBudgetEventsRequest, BudgetEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReasoningEngineService_StreamBudgetEventsClient = grpc.ServerStreamingClient[BudgetEvent]

func (c *reasoningEngineServiceClient) StreamReasoningTrace(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ReasoningTraceEvent, ReasoningTraceAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReasoningEngineService_ServiceDesc.Streams[1], ReasoningEngineService_StreamReasoningTrace_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReasoningTraceEvent, ReasoningTraceAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReasoningEngineService_StreamReasoningTraceClient = grpc.ClientStreamingClient[ReasoningTraceEvent, ReasoningTraceAck]

func (c *reasoningEngineServiceClient) CreateTreeBranch(ctx context.Context, in *CreateTreeBranchRequest, opts ...grpc.CallOption) (*TreeBranchHandle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TreeBranchHandle)
	err := c.cc.Invoke(ctx, ReasoningEngineService_CreateTreeBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reasoningEngineServiceClient) EvaluateTreeBranches(ctx context.Context, in *EvaluateTreeBranchesRequest, opts ...grpc.CallOption) (*BranchSelectionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BranchSelectionResult)
	err := c.cc.Invoke(ctx, ReasoningEngineService_EvaluateTreeBranches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reasoningEngineServiceClient) StartDebateSession(ctx context.Context, in *StartDebateSessionRequest, opts ...grpc.CallOption) (*DebateSessionHandle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DebateSessionHandle)
	err := c.cc.Invoke(ctx, ReasoningEngineService_StartDebateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reasoningEngineServiceClient) SubmitDebateTurn(ctx context.Context, in *SubmitDebateTurnRequest, opts ...grpc.CallOption) (*DebateRoundResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DebateRoundResult)
	err := c.cc.Invoke(ctx, ReasoningEngineService_SubmitDebateTurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reasoningEngineServiceClient) FinalizeDebateSession(ctx context.Context, in *FinalizeDebateSessionRequest, opts ...grpc.CallOption) (*DebateSessionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DebateSessionResult)
	err := c.cc.Invoke(ctx, ReasoningEngineService_FinalizeDebateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reasoningEngineServiceClient) StartSelfCorrectionLoop(ctx context.Context, in *StartSelfCorrectionRequest, opts ...grpc.CallOption) (*SelfCorrectionHandle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelfCorrectionHandle)
	err := c.cc.Invoke(ctx, ReasoningEngineService_StartSelfCorrectionLoop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reasoningEngineServiceClient) SubmitCorrectionIteration(ctx context.Context, in *CorrectionIterationEvent, opts ...grpc.CallOption) (*ConvergenceResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvergenceResult)
	err := c.cc.Invoke(ctx, ReasoningEngineService_SubmitCorrectionIteration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reasoningEngineServiceClient) GetReasoningTrace(ctx context.Context, in *GetReasoningTraceRequest, opts ...grpc.CallOption) (*GetReasoningTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReasoningTraceResponse)
	err := c.cc.Invoke(ctx, ReasoningEngineService_GetReasoningTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReasoningEngineServiceServer is the server API for ReasoningEngineService service.
// All implementations must embed UnimplementedReasoningEngineServiceServer
// for forward compatibility.
type ReasoningEngineServiceServer interface {
	SelectReasoningMode(context.Context, *SelectReasoningModeRequest) (*ReasoningModeConfig, error)
	AllocateReasoningBudget(context.Context, *AllocateReasoningBudgetRequest) (*ReasoningBudgetEnvelope, error)
	GetReasoningBudgetStatus(context.Context, *GetBudgetStatusRequest) (*BudgetStatusResponse, error)
	StreamBudgetEvents(*StreamBudgetEventsRequest, grpc.ServerStreamingServer[BudgetEvent]) error
	StreamReasoningTrace(grpc.ClientStreamingServer[ReasoningTraceEvent, ReasoningTraceAck]) error
	CreateTreeBranch(context.Context, *CreateTreeBranchRequest) (*TreeBranchHandle, error)
	EvaluateTreeBranches(context.Context, *EvaluateTreeBranchesRequest) (*BranchSelectionResult, error)
	StartDebateSession(context.Context, *StartDebateSessionRequest) (*DebateSessionHandle, error)
	SubmitDebateTurn(context.Context, *SubmitDebateTurnRequest) (*DebateRoundResult, error)
	FinalizeDebateSession(context.Context, *FinalizeDebateSessionRequest) (*DebateSessionResult, error)
	StartSelfCorrectionLoop(context.Context, *StartSelfCorrectionRequest) (*SelfCorrectionHandle, error)
	SubmitCorrectionIteration(context.Context, *CorrectionIterationEvent) (*ConvergenceResult, error)
	GetReasoningTrace(context.Context, *GetReasoningTraceRequest) (*GetReasoningTraceResponse, error)
	mustEmbedUnimplementedReasoningEngineServiceServer()
}

// UnimplementedReasoningEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReasoningEngineServiceServer struct{}

func (UnimplementedReasoningEngineServiceServer) SelectReasoningMode(context.Context, *SelectReasoningModeRequest) (*ReasoningModeConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectReasoningMode not implemented")
}
func (UnimplementedReasoningEngineServiceServer) AllocateReasoningBudget(context.Context, *AllocateReasoningBudgetRequest) (*ReasoningBudgetEnvelope, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocateReasoningBudget not implemented")
}
func (UnimplementedReasoningEngineServiceServer) GetReasoningBudgetStatus(context.Context, *GetBudgetStatusRequest) (*BudgetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReasoningBudgetStatus not implemented")
}
func (UnimplementedReasoningEngineServiceServer) StreamBudgetEvents(*StreamBudgetEventsRequest, grpc.ServerStreamingServer[BudgetEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamBudgetEvents not implemented")
}
func (UnimplementedReasoningEngineServiceServer) StreamReasoningTrace(grpc.ClientStreamingServer[ReasoningTraceEvent, ReasoningTraceAck]) error {
	return status.Errorf(codes.Unimplemented, "method StreamReasoningTrace not implemented")
}
func (UnimplementedReasoningEngineServiceServer) CreateTreeBranch(context.Context, *CreateTreeBranchRequest) (*TreeBranchHandle, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTreeBranch not implemented")
}
func (UnimplementedReasoningEngineServiceServer) EvaluateTreeBranches(context.Context, *EvaluateTreeBranchesRequest) (*BranchSelectionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateTreeBranches not implemented")
}
func (UnimplementedReasoningEngineServiceServer) StartDebateSession(context.Context, *StartDebateSessionRequest) (*DebateSessionHandle, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDebateSession not implemented")
}
func (UnimplementedReasoningEngineServiceServer) SubmitDebateTurn(context.Context, *SubmitDebateTurnRequest) (*DebateRoundResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitDebateTurn not implemented")
}
func (UnimplementedReasoningEngineServiceServer) FinalizeDebateSession(context.Context, *FinalizeDebateSessionRequest) (*DebateSessionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeDebateSession not implemented")
}
func (UnimplementedReasoningEngineServiceServer) StartSelfCorrectionLoop(context.Context, *StartSelfCorrectionRequest) (*SelfCorrectionHandle, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSelfCorrectionLoop not implemented")
}
func (UnimplementedReasoningEngineServiceServer) SubmitCorrectionIteration(context.Context, *CorrectionIterationEvent) (*ConvergenceResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitCorrectionIteration not implemented")
}
func (UnimplementedReasoningEngineServiceServer) GetReasoningTrace(context.Context, *GetReasoningTraceRequest) (*GetReasoningTraceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReasoningTrace not implemented")
}
func (UnimplementedReasoningEngineServiceServer) mustEmbedUnimplementedReasoningEngineServiceServer() {
}
func (UnimplementedReasoningEngineServiceServer) testEmbeddedByValue() {}

// UnsafeReasoningEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReasoningEngineServiceServer will
// result in compilation errors.
type UnsafeReasoningEngineServiceServer interface {
	mustEmbedUnimplementedReasoningEngineServiceServer()
}

func RegisterReasoningEngineServiceServer(s grpc.ServiceRegistrar, srv ReasoningEngineServiceServer) {
	// If the following call pancis, it indicates UnimplementedReasoningEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReasoningEngineService_ServiceDesc, srv)
}

func _ReasoningEngineService_SelectReasoningMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectReasoningModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasoningEngineServiceServer).SelectReasoningMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasoningEngineService_SelectReasoningMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasoningEngineServiceServer).SelectReasoningMode(ctx, req.(*SelectReasoningModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReasoningEngineService_AllocateReasoningBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateReasoningBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasoningEngineServiceServer).AllocateReasoningBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasoningEngineService_AllocateReasoningBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasoningEngineServiceServer).AllocateReasoningBudget(ctx, req.(*AllocateReasoningBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReasoningEngineService_GetReasoningBudgetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasoningEngineServiceServer).GetReasoningBudgetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasoningEngineService_GetReasoningBudgetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasoningEngineServiceServer).GetReasoningBudgetStatus(ctx, req.(*GetBudgetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReasoningEngineService_StreamBudgetEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBudgetEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReasoningEngineServiceServer).StreamBudgetEvents(m, &grpc.GenericServerStream[StreamBudgetEventsRequest, BudgetEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReasoningEngineService_StreamBudgetEventsServer = grpc.ServerStreamingServer[BudgetEvent]

func _ReasoningEngineService_StreamReasoningTrace_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReasoningEngineServiceServer).StreamReasoningTrace(&grpc.GenericServerStream[ReasoningTraceEvent, ReasoningTraceAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReasoningEngineService_StreamReasoningTraceServer = grpc.ClientStreamingServer[ReasoningTraceEvent, ReasoningTraceAck]

func _ReasoningEngineService_CreateTreeBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTreeBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasoningEngineServiceServer).CreateTreeBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasoningEngineService_CreateTreeBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasoningEngineServiceServer).CreateTreeBranch(ctx, req.(*CreateTreeBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReasoningEngineService_EvaluateTreeBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateTreeBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasoningEngineServiceServer).EvaluateTreeBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasoningEngineService_EvaluateTreeBranches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasoningEngineServiceServer).EvaluateTreeBranches(ctx, req.(*EvaluateTreeBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReasoningEngineService_StartDebateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDebateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasoningEngineServiceServer).StartDebateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasoningEngineService_StartDebateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasoningEngineServiceServer).StartDebateSession(ctx, req.(*StartDebateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReasoningEngineService_SubmitDebateTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitDebateTurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasoningEngineServiceServer).SubmitDebateTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasoningEngineService_SubmitDebateTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasoningEngineServiceServer).SubmitDebateTurn(ctx, req.(*SubmitDebateTurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReasoningEngineService_FinalizeDebateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeDebateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasoningEngineServiceServer).FinalizeDebateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasoningEngineService_FinalizeDebateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasoningEngineServiceServer).FinalizeDebateSession(ctx, req.(*FinalizeDebateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReasoningEngineService_StartSelfCorrectionLoop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSelfCorrectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasoningEngineServiceServer).StartSelfCorrectionLoop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasoningEngineService_StartSelfCorrectionLoop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasoningEngineServiceServer).StartSelfCorrectionLoop(ctx, req.(*StartSelfCorrectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReasoningEngineService_SubmitCorrectionIteration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CorrectionIterationEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasoningEngineServiceServer).SubmitCorrectionIteration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasoningEngineService_SubmitCorrectionIteration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasoningEngineServiceServer).SubmitCorrectionIteration(ctx, req.(*CorrectionIterationEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReasoningEngineService_GetReasoningTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReasoningTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasoningEngineServiceServer).GetReasoningTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasoningEngineService_GetReasoningTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasoningEngineServiceServer).GetReasoningTrace(ctx, req.(*GetReasoningTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReasoningEngineService_ServiceDesc is the grpc.ServiceDesc for ReasoningEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReasoningEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "musematic.reasoning.v1.ReasoningEngineService",
	HandlerType: (*ReasoningEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectReasoningMode",
			Handler:    _ReasoningEngineService_SelectReasoningMode_Handler,
		},
		{
			MethodName: "AllocateReasoningBudget",
			Handler:    _ReasoningEngineService_AllocateReasoningBudget_Handler,
		},
		{
			MethodName: "GetReasoningBudgetStatus",
			Handler:    _ReasoningEngineService_GetReasoningBudgetStatus_Handler,
		},
		{
			MethodName: "CreateTreeBranch",
			Handler:    _ReasoningEngineService_CreateTreeBranch_Handler,
		},
		{
			MethodName: "EvaluateTreeBranches",
			Handler:    _ReasoningEngineService_EvaluateTreeBranches_Handler,
		},
		{
			MethodName: "StartDebateSession",
			Handler:    _ReasoningEngineService_StartDebateSession_Handler,
		},
		{
			MethodName: "SubmitDebateTurn",
			Handler:    _ReasoningEngineService_SubmitDebateTurn_Handler,
		},
		{
			MethodName: "FinalizeDebateSession",
			Handler:    _ReasoningEngineService_FinalizeDebateSession_Handler,
		},
		{
			MethodName: "StartSelfCorrectionLoop",
			Handler:    _ReasoningEngineService_StartSelfCorrectionLoop_Handler,
		},
		{
			MethodName: "SubmitCorrectionIteration",
			Handler:    _ReasoningEngineService_SubmitCorrectionIteration_Handler,
		},
		{
			MethodName: "GetReasoningTrace",
			Handler:    _ReasoningEngineService_GetReasoningTrace_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBudgetEvents",
			Handler:       _ReasoningEngineService_StreamBudgetEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamReasoningTrace",
			Handler:       _ReasoningEngineService_StreamReasoningTrace_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "reasoning_engine.proto",
}
