// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: sandbox_manager.proto

package sandboxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxService_CreateSandbox_FullMethodName           = "/sandbox_manager.v1.SandboxService/CreateSandbox"
	SandboxService_ExecuteSandboxStep_FullMethodName      = "/sandbox_manager.v1.SandboxService/ExecuteSandboxStep"
	SandboxService_StreamSandboxLogs_FullMethodName       = "/sandbox_manager.v1.SandboxService/StreamSandboxLogs"
	SandboxService_TerminateSandbox_FullMethodName        = "/sandbox_manager.v1.SandboxService/TerminateSandbox"
	SandboxService_CollectSandboxArtifacts_FullMethodName = "/sandbox_manager.v1.SandboxService/CollectSandboxArtifacts"
)

// SandboxServiceClient is the client API for SandboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SandboxServiceClient interface {
	CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error)
	ExecuteSandboxStep(ctx context.Context, in *ExecuteSandboxStepRequest, opts ...grpc.CallOption) (*ExecuteSandboxStepResponse, error)
	StreamSandboxLogs(ctx context.Context, in *StreamSandboxLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SandboxLogLine], error)
	TerminateSandbox(ctx context.Context, in *TerminateSandboxRequest, opts ...grpc.CallOption) (*TerminateSandboxResponse, error)
	CollectSandboxArtifacts(ctx context.Context, in *CollectSandboxArtifactsRequest, opts ...grpc.CallOption) (*CollectSandboxArtifactsResponse, error)
}

type sandboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxServiceClient(cc grpc.ClientConnInterface) SandboxServiceClient {
	return &sandboxServiceClient{cc}
}

func (c *sandboxServiceClient) CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxService_CreateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) ExecuteSandboxStep(ctx context.Context, in *ExecuteSandboxStepRequest, opts ...grpc.CallOption) (*ExecuteSandboxStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteSandboxStepResponse)
	err := c.cc.Invoke(ctx, SandboxService_ExecuteSandboxStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) StreamSandboxLogs(ctx context.Context, in *StreamSandboxLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SandboxLogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxService_ServiceDesc.Streams[0], SandboxService_StreamSandboxLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamSandboxLogsRequest, SandboxLogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_StreamSandboxLogsClient = grpc.ServerStreamingClient[SandboxLogLine]

func (c *sandboxServiceClient) TerminateSandbox(ctx context.Context, in *TerminateSandboxRequest, opts ...grpc.CallOption) (*TerminateSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxService_TerminateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) CollectSandboxArtifacts(ctx context.Context, in *CollectSandboxArtifactsRequest, opts ...grpc.CallOption) (*CollectSandboxArtifactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectSandboxArtifactsResponse)
	err := c.cc.Invoke(ctx, SandboxService_CollectSandboxArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxServiceServer is the server API for SandboxService service.
// All implementations must embed UnimplementedSandboxServiceServer
// for forward compatibility.
type SandboxServiceServer interface {
	CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error)
	ExecuteSandboxStep(context.Context, *ExecuteSandboxStepRequest) (*ExecuteSandboxStepResponse, error)
	StreamSandboxLogs(*StreamSandboxLogsRequest, grpc.ServerStreamingServer[SandboxLogLine]) error
	TerminateSandbox(context.Context, *TerminateSandboxRequest) (*TerminateSandboxResponse, error)
	CollectSandboxArtifacts(context.Context, *CollectSandboxArtifactsRequest) (*CollectSandboxArtifactsResponse, error)
	mustEmbedUnimplementedSandboxServiceServer()
}

// UnimplementedSandboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxServiceServer struct{}

func (UnimplementedSandboxServiceServer) CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) ExecuteSandboxStep(context.Context, *ExecuteSandboxStepRequest) (*ExecuteSandboxStepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteSandboxStep not implemented")
}
func (UnimplementedSandboxServiceServer) StreamSandboxLogs(*StreamSandboxLogsRequest, grpc.ServerStreamingServer[SandboxLogLine]) error {
	return status.Error(codes.Unimplemented, "method StreamSandboxLogs not implemented")
}
func (UnimplementedSandboxServiceServer) TerminateSandbox(context.Context, *TerminateSandboxRequest) (*TerminateSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateSandbox not implemented")
}
func (UnimplementedSandboxServiceServer) CollectSandboxArtifacts(context.Context, *CollectSandboxArtifactsRequest) (*CollectSandboxArtifactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectSandboxArtifacts not implemented")
}
func (UnimplementedSandboxServiceServer) mustEmbedUnimplementedSandboxServiceServer() {}
func (UnimplementedSandboxServiceServer) testEmbeddedByValue()                        {}

// UnsafeSandboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxServiceServer will
// result in compilation errors.
type UnsafeSandboxServiceServer interface {
	mustEmbedUnimplementedSandboxServiceServer()
}

func RegisterSandboxServiceServer(s grpc.ServiceRegistrar, srv SandboxServiceServer) {
	// If the following call panics, it indicates UnimplementedSandboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxService_ServiceDesc, srv)
}

func _SandboxService_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_CreateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).CreateSandbox(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_ExecuteSandboxStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteSandboxStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ExecuteSandboxStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ExecuteSandboxStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ExecuteSandboxStep(ctx, req.(*ExecuteSandboxStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_StreamSandboxLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSandboxLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxServiceServer).StreamSandboxLogs(m, &grpc.GenericServerStream[StreamSandboxLogsRequest, SandboxLogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxService_StreamSandboxLogsServer = grpc.ServerStreamingServer[SandboxLogLine]

func _SandboxService_TerminateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).TerminateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_TerminateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).TerminateSandbox(ctx, req.(*TerminateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_CollectSandboxArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectSandboxArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).CollectSandboxArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_CollectSandboxArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).CollectSandboxArtifacts(ctx, req.(*CollectSandboxArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxService_ServiceDesc is the grpc.ServiceDesc for SandboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox_manager.v1.SandboxService",
	HandlerType: (*SandboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSandbox",
			Handler:    _SandboxService_CreateSandbox_Handler,
		},
		{
			MethodName: "ExecuteSandboxStep",
			Handler:    _SandboxService_ExecuteSandboxStep_Handler,
		},
		{
			MethodName: "TerminateSandbox",
			Handler:    _SandboxService_TerminateSandbox_Handler,
		},
		{
			MethodName: "CollectSandboxArtifacts",
			Handler:    _SandboxService_CollectSandboxArtifacts_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSandboxLogs",
			Handler:       _SandboxService_StreamSandboxLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sandbox_manager.proto",
}
