// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sandbox_manager.proto

package sandboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SandboxState int32

const (
	SandboxState_SANDBOX_STATE_UNSPECIFIED SandboxState = 0
	SandboxState_SANDBOX_STATE_CREATING    SandboxState = 1
	SandboxState_SANDBOX_STATE_READY       SandboxState = 2
	SandboxState_SANDBOX_STATE_EXECUTING   SandboxState = 3
	SandboxState_SANDBOX_STATE_COMPLETED   SandboxState = 4
	SandboxState_SANDBOX_STATE_FAILED      SandboxState = 5
	SandboxState_SANDBOX_STATE_TERMINATED  SandboxState = 6
)

// Enum value maps for SandboxState.
var (
	SandboxState_name = map[int32]string{
		0: "SANDBOX_STATE_UNSPECIFIED",
		1: "SANDBOX_STATE_CREATING",
		2: "SANDBOX_STATE_READY",
		3: "SANDBOX_STATE_EXECUTING",
		4: "SANDBOX_STATE_COMPLETED",
		5: "SANDBOX_STATE_FAILED",
		6: "SANDBOX_STATE_TERMINATED",
	}
	SandboxState_value = map[string]int32{
		"SANDBOX_STATE_UNSPECIFIED": 0,
		"SANDBOX_STATE_CREATING":    1,
		"SANDBOX_STATE_READY":       2,
		"SANDBOX_STATE_EXECUTING":   3,
		"SANDBOX_STATE_COMPLETED":   4,
		"SANDBOX_STATE_FAILED":      5,
		"SANDBOX_STATE_TERMINATED":  6,
	}
)

func (x SandboxState) Enum() *SandboxState {
	p := new(SandboxState)
	*p = x
	return p
}

func (x SandboxState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxState) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_manager_proto_enumTypes[0].Descriptor()
}

func (SandboxState) Type() protoreflect.EnumType {
	return &file_sandbox_manager_proto_enumTypes[0]
}

func (x SandboxState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxState.Descriptor instead.
func (SandboxState) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{0}
}

type SandboxEventType int32

const (
	SandboxEventType_SANDBOX_EVENT_UNSPECIFIED        SandboxEventType = 0
	SandboxEventType_SANDBOX_EVENT_CREATED            SandboxEventType = 1
	SandboxEventType_SANDBOX_EVENT_READY              SandboxEventType = 2
	SandboxEventType_SANDBOX_EVENT_STEP_STARTED       SandboxEventType = 3
	SandboxEventType_SANDBOX_EVENT_STEP_COMPLETED     SandboxEventType = 4
	SandboxEventType_SANDBOX_EVENT_COMPLETED          SandboxEventType = 5
	SandboxEventType_SANDBOX_EVENT_FAILED             SandboxEventType = 6
	SandboxEventType_SANDBOX_EVENT_TERMINATED         SandboxEventType = 7
	SandboxEventType_SANDBOX_EVENT_ARTIFACT_COLLECTED SandboxEventType = 8
)

// Enum value maps for SandboxEventType.
var (
	SandboxEventType_name = map[int32]string{
		0: "SANDBOX_EVENT_UNSPECIFIED",
		1: "SANDBOX_EVENT_CREATED",
		2: "SANDBOX_EVENT_READY",
		3: "SANDBOX_EVENT_STEP_STARTED",
		4: "SANDBOX_EVENT_STEP_COMPLETED",
		5: "SANDBOX_EVENT_COMPLETED",
		6: "SANDBOX_EVENT_FAILED",
		7: "SANDBOX_EVENT_TERMINATED",
		8: "SANDBOX_EVENT_ARTIFACT_COLLECTED",
	}
	SandboxEventType_value = map[string]int32{
		"SANDBOX_EVENT_UNSPECIFIED":        0,
		"SANDBOX_EVENT_CREATED":            1,
		"SANDBOX_EVENT_READY":              2,
		"SANDBOX_EVENT_STEP_STARTED":       3,
		"SANDBOX_EVENT_STEP_COMPLETED":     4,
		"SANDBOX_EVENT_COMPLETED":          5,
		"SANDBOX_EVENT_FAILED":             6,
		"SANDBOX_EVENT_TERMINATED":         7,
		"SANDBOX_EVENT_ARTIFACT_COLLECTED": 8,
	}
)

func (x SandboxEventType) Enum() *SandboxEventType {
	p := new(SandboxEventType)
	*p = x
	return p
}

func (x SandboxEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_manager_proto_enumTypes[1].Descriptor()
}

func (SandboxEventType) Type() protoreflect.EnumType {
	return &file_sandbox_manager_proto_enumTypes[1]
}

func (x SandboxEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxEventType.Descriptor instead.
func (SandboxEventType) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{1}
}

type ResourceLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuRequest    string                 `protobuf:"bytes,1,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`
	CpuLimit      string                 `protobuf:"bytes,2,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryRequest string                 `protobuf:"bytes,3,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	MemoryLimit   string                 `protobuf:"bytes,4,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_sandbox_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceLimits) GetCpuRequest() string {
	if x != nil {
		return x.CpuRequest
	}
	return ""
}

func (x *ResourceLimits) GetCpuLimit() string {
	if x != nil {
		return x.CpuLimit
	}
	return ""
}

func (x *ResourceLimits) GetMemoryRequest() string {
	if x != nil {
		return x.MemoryRequest
	}
	return ""
}

func (x *ResourceLimits) GetMemoryLimit() string {
	if x != nil {
		return x.MemoryLimit
	}
	return ""
}

type SandboxTemplate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image          string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Limits         *ResourceLimits        `protobuf:"bytes,3,opt,name=limits,proto3" json:"limits,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxTemplate) Reset() {
	*x = SandboxTemplate{}
	mi := &file_sandbox_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxTemplate) ProtoMessage() {}

func (x *SandboxTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxTemplate.ProtoReflect.Descriptor instead.
func (*SandboxTemplate) Descriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{1}
}

func (x *SandboxTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SandboxTemplate) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SandboxTemplate) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *SandboxTemplate) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type CorrelationContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	InteractionId string                 `protobuf:"bytes,3,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorrelationContext) Reset() {
	*x = CorrelationContext{}
	mi := &file_sandbox_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrelationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelationContext) ProtoMessage() {}

func (x *CorrelationContext) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelationContext.ProtoReflect.Descriptor instead.
func (*CorrelationContext) Descriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{2}
}

func (x *CorrelationContext) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CorrelationContext) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *CorrelationContext) GetInteractionId() string {
	if x != nil {
		return x.InteractionId
	}
	return ""
}

func (x *CorrelationContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type SandboxInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	State         SandboxState           `protobuf:"varint,3,opt,name=state,proto3,enum=sandbox_manager.v1.SandboxState" json:"state,omitempty"`
	FailureReason string                 `protobuf:"bytes,4,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	Template      string                 `protobuf:"bytes,5,opt,name=template,proto3" json:"template,omitempty"`
	PodName       string                 `protobuf:"bytes,6,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TotalSteps    int32                  `protobuf:"varint,8,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	Correlation   *CorrelationContext    `protobuf:"bytes,9,opt,name=correlation,proto3" json:"correlation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxInfo) Reset() {
	*x = SandboxInfo{}
	mi := &file_sandbox_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxInfo) ProtoMessage() {}

func (x *SandboxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxInfo.ProtoReflect.Descriptor instead.
func (*SandboxInfo) Descriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{3}
}

func (x *SandboxInfo) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxInfo) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *SandboxInfo) GetState() SandboxState {
	if x != nil {
		return x.State
	}
	return SandboxState_SANDBOX_STATE_UNSPECIFIED
}

func (x *SandboxInfo) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *SandboxInfo) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *SandboxInfo) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *SandboxInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SandboxInfo) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *SandboxInfo) GetCorrelation() *CorrelationContext {
	if x != nil {
		return x.Correlation
	}
	return nil
}

type ExecutionResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Stdout           string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr           string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode         int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Duration         *durationpb.Duration   `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	TimedOut         bool                   `protobuf:"varint,5,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	OomKilled        bool                   `protobuf:"varint,6,opt,name=oom_killed,json=oomKilled,proto3" json:"oom_killed,omitempty"`
	StructuredOutput string                 `protobuf:"bytes,7,opt,name=structured_output,json=structuredOutput,proto3" json:"structured_output,omitempty"`
	OutputTruncated  bool                   `protobuf:"varint,8,opt,name=output_truncated,json=outputTruncated,proto3" json:"output_truncated,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecutionResult) Reset() {
	*x = ExecutionResult{}
	mi := &file_sandbox_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResult) ProtoMessage() {}

func (x *ExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResult.ProtoReflect.Descriptor instead.
func (*ExecutionResult) Descriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutionResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecutionResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecutionResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecutionResult) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *ExecutionResult) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *ExecutionResult) GetOomKilled() bool {
	if x != nil {
		return x.OomKilled
	}
	return false
}

func (x *ExecutionResult) GetStructuredOutput() string {
	if x != nil {
		return x.StructuredOutput
	}
	return ""
}

func (x *ExecutionResult) GetOutputTruncated() bool {
	if x != nil {
		return x.OutputTruncated
	}
	return false
}

type SandboxEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SandboxId     string                 `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	EventType     SandboxEventType       `protobuf:"varint,4,opt,name=event_type,json=eventType,proto3,enum=sandbox_manager.v1.SandboxEventType" json:"event_type,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	DetailsJson   string                 `protobuf:"bytes,6,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"`
	NewState      SandboxState           `protobuf:"varint,7,opt,name=new_state,json=newState,proto3,enum=sandbox_manager.v1.SandboxState" json:"new_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxEvent) Reset() {
	*x = SandboxEvent{}
	mi := &file_sandbox_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxEvent) ProtoMessage() {}

func (x *SandboxEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxEvent.ProtoReflect.Descriptor instead.
func (*SandboxEvent) Descriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{5}
}

func (x *SandboxEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SandboxEvent) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxEvent) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *SandboxEvent) GetEventType() SandboxEventType {
	if x != nil {
		return x.EventType
	}
	return SandboxEventType_SANDBOX_EVENT_UNSPECIFIED
}

func (x *SandboxEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *SandboxEvent) GetDetailsJson() string {
	if x != nil {
		return x.DetailsJson
	}
	return ""
}

func (x *SandboxEvent) GetNewState() SandboxState {
	if x != nil {
		return x.NewState
	}
	return SandboxState_SANDBOX_STATE_UNSPECIFIED
}

type ArtifactEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	CollectedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactEntry) Reset() {
	*x = ArtifactEntry{}
	mi := &file_sandbox_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactEntry) ProtoMessage() {}

func (x *ArtifactEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactEntry.ProtoReflect.Descriptor instead.
func (*ArtifactEntry) Descriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{6}
}

func (x *ArtifactEntry) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ArtifactEntry) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ArtifactEntry) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactEntry) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ArtifactEntry) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

type CreateSandboxRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TemplateName      string                 `protobuf:"bytes,1,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	Correlation       *CorrelationContext    `protobuf:"bytes,2,opt,name=correlation,proto3" json:"correlation,omitempty"`
	ResourceOverrides *ResourceLimits        `protobuf:"bytes,3,opt,name=resource_overrides,json=resourceOverrides,proto3" json:"resource_overrides,omitempty"`
	TimeoutOverride   int32                  `protobuf:"varint,4,opt,name=timeout_override,json=timeoutOverride,proto3" json:"timeout_override,omitempty"`
	NetworkEnabled    bool                   `protobuf:"varint,5,opt,name=network_enabled,json=networkEnabled,proto3" json:"network_enabled,omitempty"`
	EgressAllowlist   []string               `protobuf:"bytes,6,rep,name=egress_allowlist,json=egressAllowlist,proto3" json:"egress_allowlist,omitempty"`
	EnvVars           map[string]string      `protobuf:"bytes,7,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PipPackages       []string               `protobuf:"bytes,8,rep,name=pip_packages,json=pipPackages,proto3" json:"pip_packages,omitempty"`
	NpmPackages       []string               `protobuf:"bytes,9,rep,name=npm_packages,json=npmPackages,proto3" json:"npm_packages,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_sandbox_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSandboxRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *CreateSandboxRequest) GetCorrelation() *CorrelationContext {
	if x != nil {
		return x.Correlation
	}
	return nil
}

func (x *CreateSandboxRequest) GetResourceOverrides() *ResourceLimits {
	if x != nil {
		return x.ResourceOverrides
	}
	return nil
}

func (x *CreateSandboxRequest) GetTimeoutOverride() int32 {
	if x != nil {
		return x.TimeoutOverride
	}
	return 0
}

func (x *CreateSandboxRequest) GetNetworkEnabled() bool {
	if x != nil {
		return x.NetworkEnabled
	}
	return false
}

func (x *CreateSandboxRequest) GetEgressAllowlist() []string {
	if x != nil {
		return x.EgressAllowlist
	}
	return nil
}

func (x *CreateSandboxRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *CreateSandboxRequest) GetPipPackages() []string {
	if x != nil {
		return x.PipPackages
	}
	return nil
}

func (x *CreateSandboxRequest) GetNpmPackages() []string {
	if x != nil {
		return x.NpmPackages
	}
	return nil
}

type CreateSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	State         SandboxState           `protobuf:"varint,2,opt,name=state,proto3,enum=sandbox_manager.v1.SandboxState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxResponse) Reset() {
	*x = CreateSandboxResponse{}
	mi := &file_sandbox_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse) ProtoMessage() {}

func (x *CreateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxResponse.ProtoReflect.Descriptor instead.
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{8}
}

func (x *CreateSandboxResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateSandboxResponse) GetState() SandboxState {
	if x != nil {
		return x.State
	}
	return SandboxState_SANDBOX_STATE_UNSPECIFIED
}

type ExecuteSandboxStepRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SandboxId       string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Code            string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	TimeoutOverride int32                  `protobuf:"varint,3,opt,name=timeout_override,json=timeoutOverride,proto3" json:"timeout_override,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteSandboxStepRequest) Reset() {
	*x = ExecuteSandboxStepRequest{}
	mi := &file_sandbox_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSandboxStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSandboxStepRequest) ProtoMessage() {}

func (x *ExecuteSandboxStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSandboxStepRequest.ProtoReflect.Descriptor instead.
func (*ExecuteSandboxStepRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteSandboxStepRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ExecuteSandboxStepRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteSandboxStepRequest) GetTimeoutOverride() int32 {
	if x != nil {
		return x.TimeoutOverride
	}
	return 0
}

type ExecuteSandboxStepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ExecutionResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	StepNum       int32                  `protobuf:"varint,2,opt,name=step_num,json=stepNum,proto3" json:"step_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSandboxStepResponse) Reset() {
	*x = ExecuteSandboxStepResponse{}
	mi := &file_sandbox_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSandboxStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSandboxStepResponse) ProtoMessage() {}

func (x *ExecuteSandboxStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSandboxStepResponse.ProtoReflect.Descriptor instead.
func (*ExecuteSandboxStepResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteSandboxStepResponse) GetResult() *ExecutionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteSandboxStepResponse) GetStepNum() int32 {
	if x != nil {
		return x.StepNum
	}
	return 0
}

type StreamSandboxLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSandboxLogsRequest) Reset() {
	*x = StreamSandboxLogsRequest{}
	mi := &file_sandbox_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSandboxLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSandboxLogsRequest) ProtoMessage() {}

func (x *StreamSandboxLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSandboxLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamSandboxLogsRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{11}
}

func (x *StreamSandboxLogsRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *StreamSandboxLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type SandboxLogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxLogLine) Reset() {
	*x = SandboxLogLine{}
	mi := &file_sandbox_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxLogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxLogLine) ProtoMessage() {}

func (x *SandboxLogLine) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxLogLine.ProtoReflect.Descriptor instead.
func (*SandboxLogLine) Descriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{12}
}

func (x *SandboxLogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *SandboxLogLine) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *SandboxLogLine) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TerminateSandboxRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SandboxId          string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	GracePeriodSeconds int32                  `protobuf:"varint,2,opt,name=grace_period_seconds,json=gracePeriodSeconds,proto3" json:"grace_period_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TerminateSandboxRequest) Reset() {
	*x = TerminateSandboxRequest{}
	mi := &file_sandbox_manager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSandboxRequest) ProtoMessage() {}

func (x *TerminateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_manager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateSandboxRequest.ProtoReflect.Descriptor instead.
func (*TerminateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{13}
}

func (x *TerminateSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *TerminateSandboxRequest) GetGracePeriodSeconds() int32 {
	if x != nil {
		return x.GracePeriodSeconds
	}
	return 0
}

type TerminateSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         SandboxState           `protobuf:"varint,1,opt,name=state,proto3,enum=sandbox_manager.v1.SandboxState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateSandboxResponse) Reset() {
	*x = TerminateSandboxResponse{}
	mi := &file_sandbox_manager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSandboxResponse) ProtoMessage() {}

func (x *TerminateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_manager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateSandboxResponse.ProtoReflect.Descriptor instead.
func (*TerminateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{14}
}

func (x *TerminateSandboxResponse) GetState() SandboxState {
	if x != nil {
		return x.State
	}
	return SandboxState_SANDBOX_STATE_UNSPECIFIED
}

type CollectSandboxArtifactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectSandboxArtifactsRequest) Reset() {
	*x = CollectSandboxArtifactsRequest{}
	mi := &file_sandbox_manager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectSandboxArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectSandboxArtifactsRequest) ProtoMessage() {}

func (x *CollectSandboxArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_manager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectSandboxArtifactsRequest.ProtoReflect.Descriptor instead.
func (*CollectSandboxArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{15}
}

func (x *CollectSandboxArtifactsRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type CollectSandboxArtifactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*ArtifactEntry       `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Complete      bool                   `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectSandboxArtifactsResponse) Reset() {
	*x = CollectSandboxArtifactsResponse{}
	mi := &file_sandbox_manager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectSandboxArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectSandboxArtifactsResponse) ProtoMessage() {}

func (x *CollectSandboxArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_manager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectSandboxArtifactsResponse.ProtoReflect.Descriptor instead.
func (*CollectSandboxArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_manager_proto_rawDescGZIP(), []int{16}
}

func (x *CollectSandboxArtifactsResponse) GetArtifacts() []*ArtifactEntry {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *CollectSandboxArtifactsResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

var File_sandbox_manager_proto protoreflect.FileDescriptor

const file_sandbox_manager_proto_rawDesc = "" +
	"\n" +
	"\x15sandbox_manager.proto\x12\x12sandbox_manager.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x01\n" +
	"\x0eResourceLimits\x12\x1f\n" +
	"\vcpu_request\x18\x01 \x01(\tR\n" +
	"cpuRequest\x12\x1b\n" +
	"\tcpu_limit\x18\x02 \x01(\tR\bcpuLimit\x12%\n" +
	"\x0ememory_request\x18\x03 \x01(\tR\rmemoryRequest\x12!\n" +
	"\fmemory_limit\x18\x04 \x01(\tR\vmemoryLimit\"\xa0\x01\n" +
	"\x0fSandboxTemplate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12:\n" +
	"\x06limits\x18\x03 \x01(\v2\".sandbox_manager.v1.ResourceLimitsR\x06limits\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\"\x9c\x01\n" +
	"\x12CorrelationContext\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12%\n" +
	"\x0einteraction_id\x18\x03 \x01(\tR\rinteractionId\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\"\x8b\x03\n" +
	"\vSandboxInfo\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x126\n" +
	"\x05state\x18\x03 \x01(\x0e2 .sandbox_manager.v1.SandboxStateR\x05state\x12%\n" +
	"\x0efailure_reason\x18\x04 \x01(\tR\rfailureReason\x12\x1a\n" +
	"\btemplate\x18\x05 \x01(\tR\btemplate\x12\x19\n" +
	"\bpod_name\x18\x06 \x01(\tR\apodName\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1f\n" +
	"\vtotal_steps\x18\b \x01(\x05R\n" +
	"totalSteps\x12H\n" +
	"\vcorrelation\x18\t \x01(\v2&.sandbox_manager.v1.CorrelationContextR\vcorrelation\"\xa9\x02\n" +
	"\x0fExecutionResult\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x1b\n" +
	"\ttimed_out\x18\x05 \x01(\bR\btimedOut\x12\x1d\n" +
	"\n" +
	"oom_killed\x18\x06 \x01(\bR\toomKilled\x12+\n" +
	"\x11structured_output\x18\a \x01(\tR\x10structuredOutput\x12)\n" +
	"\x10output_truncated\x18\b \x01(\bR\x0foutputTruncated\"\xcf\x02\n" +
	"\fSandboxEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x02 \x01(\tR\tsandboxId\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\x12C\n" +
	"\n" +
	"event_type\x18\x04 \x01(\x0e2$.sandbox_manager.v1.SandboxEventTypeR\teventType\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12!\n" +
	"\fdetails_json\x18\x06 \x01(\tR\vdetailsJson\x12=\n" +
	"\tnew_state\x18\a \x01(\x0e2 .sandbox_manager.v1.SandboxStateR\bnewState\"\xcb\x01\n" +
	"\rArtifactEntry\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12=\n" +
	"\fcollected_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\"\xab\x04\n" +
	"\x14CreateSandboxRequest\x12#\n" +
	"\rtemplate_name\x18\x01 \x01(\tR\ftemplateName\x12H\n" +
	"\vcorrelation\x18\x02 \x01(\v2&.sandbox_manager.v1.CorrelationContextR\vcorrelation\x12Q\n" +
	"\x12resource_overrides\x18\x03 \x01(\v2\".sandbox_manager.v1.ResourceLimitsR\x11resourceOverrides\x12)\n" +
	"\x10timeout_override\x18\x04 \x01(\x05R\x0ftimeoutOverride\x12'\n" +
	"\x0fnetwork_enabled\x18\x05 \x01(\bR\x0enetworkEnabled\x12)\n" +
	"\x10egress_allowlist\x18\x06 \x03(\tR\x0fegressAllowlist\x12P\n" +
	"\benv_vars\x18\a \x03(\v25.sandbox_manager.v1.CreateSandboxRequest.EnvVarsEntryR\aenvVars\x12!\n" +
	"\fpip_packages\x18\b \x03(\tR\vpipPackages\x12!\n" +
	"\fnpm_packages\x18\t \x03(\tR\vnpmPackages\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x15CreateSandboxResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x126\n" +
	"\x05state\x18\x02 \x01(\x0e2 .sandbox_manager.v1.SandboxStateR\x05state\"y\n" +
	"\x19ExecuteSandboxStepRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12)\n" +
	"\x10timeout_override\x18\x03 \x01(\x05R\x0ftimeoutOverride\"t\n" +
	"\x1aExecuteSandboxStepResponse\x12;\n" +
	"\x06result\x18\x01 \x01(\v2#.sandbox_manager.v1.ExecutionResultR\x06result\x12\x19\n" +
	"\bstep_num\x18\x02 \x01(\x05R\astepNum\"Q\n" +
	"\x18StreamSandboxLogsRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\"v\n" +
	"\x0eSandboxLogLine\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"j\n" +
	"\x17TerminateSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x120\n" +
	"\x14grace_period_seconds\x18\x02 \x01(\x05R\x12gracePeriodSeconds\"R\n" +
	"\x18TerminateSandboxResponse\x126\n" +
	"\x05state\x18\x01 \x01(\x0e2 .sandbox_manager.v1.SandboxStateR\x05state\"?\n" +
	"\x1eCollectSandboxArtifactsRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"~\n" +
	"\x1fCollectSandboxArtifactsResponse\x12?\n" +
	"\tartifacts\x18\x01 \x03(\v2!.sandbox_manager.v1.ArtifactEntryR\tartifacts\x12\x1a\n" +
	"\bcomplete\x18\x02 \x01(\bR\bcomplete*\xd4\x01\n" +
	"\fSandboxState\x12\x1d\n" +
	"\x19SANDBOX_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SANDBOX_STATE_CREATING\x10\x01\x12\x17\n" +
	"\x13SANDBOX_STATE_READY\x10\x02\x12\x1b\n" +
	"\x17SANDBOX_STATE_EXECUTING\x10\x03\x12\x1b\n" +
	"\x17SANDBOX_STATE_COMPLETED\x10\x04\x12\x18\n" +
	"\x14SANDBOX_STATE_FAILED\x10\x05\x12\x1c\n" +
	"\x18SANDBOX_STATE_TERMINATED\x10\x06*\xa2\x02\n" +
	"\x10SandboxEventType\x12\x1d\n" +
	"\x19SANDBOX_EVENT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SANDBOX_EVENT_CREATED\x10\x01\x12\x17\n" +
	"\x13SANDBOX_EVENT_READY\x10\x02\x12\x1e\n" +
	"\x1aSANDBOX_EVENT_STEP_STARTED\x10\x03\x12 \n" +
	"\x1cSANDBOX_EVENT_STEP_COMPLETED\x10\x04\x12\x1b\n" +
	"\x17SANDBOX_EVENT_COMPLETED\x10\x05\x12\x18\n" +
	"\x14SANDBOX_EVENT_FAILED\x10\x06\x12\x1c\n" +
	"\x18SANDBOX_EVENT_TERMINATED\x10\a\x12$\n" +
	" SANDBOX_EVENT_ARTIFACT_COLLECTED\x10\b2\xc8\x04\n" +
	"\x0eSandboxService\x12d\n" +
	"\rCreateSandbox\x12(.sandbox_manager.v1.CreateSandboxRequest\x1a).sandbox_manager.v1.CreateSandboxResponse\x12s\n" +
	"\x12ExecuteSandboxStep\x12-.sandbox_manager.v1.ExecuteSandboxStepRequest\x1a..sandbox_manager.v1.ExecuteSandboxStepResponse\x12g\n" +
	"\x11StreamSandboxLogs\x12,.sandbox_manager.v1.StreamSandboxLogsRequest\x1a\".sandbox_manager.v1.SandboxLogLine0\x01\x12m\n" +
	"\x10TerminateSandbox\x12+.sandbox_manager.v1.TerminateSandboxRequest\x1a,.sandbox_manager.v1.TerminateSandboxResponse\x12\x82\x01\n" +
	"\x17CollectSandboxArtifacts\x122.sandbox_manager.v1.CollectSandboxArtifactsRequest\x1a3.sandbox_manager.v1.CollectSandboxArtifactsResponseBRZPgithub.com/andrea-mucci/musematic/services/sandbox-manager/api/grpc/v1;sandboxv1b\x06proto3"

var (
	file_sandbox_manager_proto_rawDescOnce sync.Once
	file_sandbox_manager_proto_rawDescData []byte
)

func file_sandbox_manager_proto_rawDescGZIP() []byte {
	file_sandbox_manager_proto_rawDescOnce.Do(func() {
		file_sandbox_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_manager_proto_rawDesc), len(file_sandbox_manager_proto_rawDesc)))
	})
	return file_sandbox_manager_proto_rawDescData
}

var file_sandbox_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sandbox_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_sandbox_manager_proto_goTypes = []any{
	(SandboxState)(0),                       // 0: sandbox_manager.v1.SandboxState
	(SandboxEventType)(0),                   // 1: sandbox_manager.v1.SandboxEventType
	(*ResourceLimits)(nil),                  // 2: sandbox_manager.v1.ResourceLimits
	(*SandboxTemplate)(nil),                 // 3: sandbox_manager.v1.SandboxTemplate
	(*CorrelationContext)(nil),              // 4: sandbox_manager.v1.CorrelationContext
	(*SandboxInfo)(nil),                     // 5: sandbox_manager.v1.SandboxInfo
	(*ExecutionResult)(nil),                 // 6: sandbox_manager.v1.ExecutionResult
	(*SandboxEvent)(nil),                    // 7: sandbox_manager.v1.SandboxEvent
	(*ArtifactEntry)(nil),                   // 8: sandbox_manager.v1.ArtifactEntry
	(*CreateSandboxRequest)(nil),            // 9: sandbox_manager.v1.CreateSandboxRequest
	(*CreateSandboxResponse)(nil),           // 10: sandbox_manager.v1.CreateSandboxResponse
	(*ExecuteSandboxStepRequest)(nil),       // 11: sandbox_manager.v1.ExecuteSandboxStepRequest
	(*ExecuteSandboxStepResponse)(nil),      // 12: sandbox_manager.v1.ExecuteSandboxStepResponse
	(*StreamSandboxLogsRequest)(nil),        // 13: sandbox_manager.v1.StreamSandboxLogsRequest
	(*SandboxLogLine)(nil),                  // 14: sandbox_manager.v1.SandboxLogLine
	(*TerminateSandboxRequest)(nil),         // 15: sandbox_manager.v1.TerminateSandboxRequest
	(*TerminateSandboxResponse)(nil),        // 16: sandbox_manager.v1.TerminateSandboxResponse
	(*CollectSandboxArtifactsRequest)(nil),  // 17: sandbox_manager.v1.CollectSandboxArtifactsRequest
	(*CollectSandboxArtifactsResponse)(nil), // 18: sandbox_manager.v1.CollectSandboxArtifactsResponse
	nil,                                     // 19: sandbox_manager.v1.CreateSandboxRequest.EnvVarsEntry
	(*timestamppb.Timestamp)(nil),           // 20: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),             // 21: google.protobuf.Duration
}
var file_sandbox_manager_proto_depIdxs = []int32{
	2,  // 0: sandbox_manager.v1.SandboxTemplate.limits:type_name -> sandbox_manager.v1.ResourceLimits
	0,  // 1: sandbox_manager.v1.SandboxInfo.state:type_name -> sandbox_manager.v1.SandboxState
	20, // 2: sandbox_manager.v1.SandboxInfo.created_at:type_name -> google.protobuf.Timestamp
	4,  // 3: sandbox_manager.v1.SandboxInfo.correlation:type_name -> sandbox_manager.v1.CorrelationContext
	21, // 4: sandbox_manager.v1.ExecutionResult.duration:type_name -> google.protobuf.Duration
	1,  // 5: sandbox_manager.v1.SandboxEvent.event_type:type_name -> sandbox_manager.v1.SandboxEventType
	20, // 6: sandbox_manager.v1.SandboxEvent.occurred_at:type_name -> google.protobuf.Timestamp
	0,  // 7: sandbox_manager.v1.SandboxEvent.new_state:type_name -> sandbox_manager.v1.SandboxState
	20, // 8: sandbox_manager.v1.ArtifactEntry.collected_at:type_name -> google.protobuf.Timestamp
	4,  // 9: sandbox_manager.v1.CreateSandboxRequest.correlation:type_name -> sandbox_manager.v1.CorrelationContext
	2,  // 10: sandbox_manager.v1.CreateSandboxRequest.resource_overrides:type_name -> sandbox_manager.v1.ResourceLimits
	19, // 11: sandbox_manager.v1.CreateSandboxRequest.env_vars:type_name -> sandbox_manager.v1.CreateSandboxRequest.EnvVarsEntry
	0,  // 12: sandbox_manager.v1.CreateSandboxResponse.state:type_name -> sandbox_manager.v1.SandboxState
	6,  // 13: sandbox_manager.v1.ExecuteSandboxStepResponse.result:type_name -> sandbox_manager.v1.ExecutionResult
	20, // 14: sandbox_manager.v1.SandboxLogLine.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 15: sandbox_manager.v1.TerminateSandboxResponse.state:type_name -> sandbox_manager.v1.SandboxState
	8,  // 16: sandbox_manager.v1.CollectSandboxArtifactsResponse.artifacts:type_name -> sandbox_manager.v1.ArtifactEntry
	9,  // 17: sandbox_manager.v1.SandboxService.CreateSandbox:input_type -> sandbox_manager.v1.CreateSandboxRequest
	11, // 18: sandbox_manager.v1.SandboxService.ExecuteSandboxStep:input_type -> sandbox_manager.v1.ExecuteSandboxStepRequest
	13, // 19: sandbox_manager.v1.SandboxService.StreamSandboxLogs:input_type -> sandbox_manager.v1.StreamSandboxLogsRequest
	15, // 20: sandbox_manager.v1.SandboxService.TerminateSandbox:input_type -> sandbox_manager.v1.TerminateSandboxRequest
	17, // 21: sandbox_manager.v1.SandboxService.CollectSandboxArtifacts:input_type -> sandbox_manager.v1.CollectSandboxArtifactsRequest
	10, // 22: sandbox_manager.v1.SandboxService.CreateSandbox:output_type -> sandbox_manager.v1.CreateSandboxResponse
	12, // 23: sandbox_manager.v1.SandboxService.ExecuteSandboxStep:output_type -> sandbox_manager.v1.ExecuteSandboxStepResponse
	14, // 24: sandbox_manager.v1.SandboxService.StreamSandboxLogs:output_type -> sandbox_manager.v1.SandboxLogLine
	16, // 25: sandbox_manager.v1.SandboxService.TerminateSandbox:output_type -> sandbox_manager.v1.TerminateSandboxResponse
	18, // 26: sandbox_manager.v1.SandboxService.CollectSandboxArtifacts:output_type -> sandbox_manager.v1.CollectSandboxArtifactsResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_sandbox_manager_proto_init() }
func file_sandbox_manager_proto_init() {
	if File_sandbox_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_manager_proto_rawDesc), len(file_sandbox_manager_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_manager_proto_goTypes,
		DependencyIndexes: file_sandbox_manager_proto_depIdxs,
		EnumInfos:         file_sandbox_manager_proto_enumTypes,
		MessageInfos:      file_sandbox_manager_proto_msgTypes,
	}.Build()
	File_sandbox_manager_proto = out.File
	file_sandbox_manager_proto_goTypes = nil
	file_sandbox_manager_proto_depIdxs = nil
}
