apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simulation-controller.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "simulation-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "simulation-controller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "simulation-controller.serviceAccountName" . }}
      containers:
        - name: simulation-controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "simulation-controller.fullname" . }}
            - secretRef:
                name: {{ include "simulation-controller.fullname" . }}-secrets
          livenessProbe:
            grpc:
              port: {{ .Values.service.port }}
          readinessProbe:
            grpc:
              port: {{ .Values.service.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
