apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simulation-controller.fullname" . }}-secrets
type: Opaque
stringData:
  POSTGRES_DSN: {{ .Values.secrets.POSTGRES_DSN | quote }}
  KAFKA_BROKERS: {{ .Values.secrets.KAFKA_BROKERS | quote }}
  MINIO_ENDPOINT: {{ .Values.secrets.MINIO_ENDPOINT | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.MINIO_ACCESS_KEY | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.MINIO_SECRET_KEY | quote }}
