apiVersion: v1
kind: Service
metadata:
  name: {{ include "simulation-controller.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "simulation-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: grpc
