apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sandbox-manager.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sandbox-manager.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sandbox-manager.fullname" . }}
    spec:
      serviceAccountName: {{ include "sandbox-manager.fullname" . }}
      containers:
        - name: sandbox-manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "sandbox-manager.fullname" . }}-config
          ports:
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
            - name: http
              containerPort: {{ .Values.service.httpPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
