{{- if and (eq .Values.jaeger.storage.type "badger") .Values.jaeger.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-badger
  namespace: {{ include "musematic-observability.namespace" . }}
  labels:
{{ include "musematic-observability.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.jaeger.persistence.size | default "5Gi" }}
{{- end }}
