{{- if .Values.multi_region.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kafka-mirrormaker
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: multi-region-kafka-mirrormaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: multi-region-kafka-mirrormaker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: multi-region-kafka-mirrormaker
    spec:
      containers:
        - name: mirrormaker
          image: {{ .Values.multi_region.images.kafkaMirrorMaker | quote }}
          command: ["/bin/sh", "-ec"]
          args:
            - |
              echo "Start Kafka MirrorMaker for {{ .Values.multi_region.primaryRegion }} -> {{ .Values.multi_region.secondaryRegion }}"
              sleep infinity
          env:
            - name: KAFKA_ADMIN_BROKERS_REF
              value: {{ .Values.multi_region.endpointRefs.kafkaAdminBrokersRef | quote }}
{{- end }}

