# ruff: noqa
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import runtime_controller_pb2 as runtime__controller__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in runtime_controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeControlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LaunchRuntime = channel.unary_unary(
                '/runtime_controller.v1.RuntimeControlService/LaunchRuntime',
                request_serializer=runtime__controller__pb2.LaunchRuntimeRequest.SerializeToString,
                response_deserializer=runtime__controller__pb2.LaunchRuntimeResponse.FromString,
                _registered_method=True)
        self.GetRuntime = channel.unary_unary(
                '/runtime_controller.v1.RuntimeControlService/GetRuntime',
                request_serializer=runtime__controller__pb2.GetRuntimeRequest.SerializeToString,
                response_deserializer=runtime__controller__pb2.GetRuntimeResponse.FromString,
                _registered_method=True)
        self.PauseRuntime = channel.unary_unary(
                '/runtime_controller.v1.RuntimeControlService/PauseRuntime',
                request_serializer=runtime__controller__pb2.PauseRuntimeRequest.SerializeToString,
                response_deserializer=runtime__controller__pb2.PauseRuntimeResponse.FromString,
                _registered_method=True)
        self.ResumeRuntime = channel.unary_unary(
                '/runtime_controller.v1.RuntimeControlService/ResumeRuntime',
                request_serializer=runtime__controller__pb2.ResumeRuntimeRequest.SerializeToString,
                response_deserializer=runtime__controller__pb2.ResumeRuntimeResponse.FromString,
                _registered_method=True)
        self.StopRuntime = channel.unary_unary(
                '/runtime_controller.v1.RuntimeControlService/StopRuntime',
                request_serializer=runtime__controller__pb2.StopRuntimeRequest.SerializeToString,
                response_deserializer=runtime__controller__pb2.StopRuntimeResponse.FromString,
                _registered_method=True)
        self.StreamRuntimeEvents = channel.unary_stream(
                '/runtime_controller.v1.RuntimeControlService/StreamRuntimeEvents',
                request_serializer=runtime__controller__pb2.StreamRuntimeEventsRequest.SerializeToString,
                response_deserializer=runtime__controller__pb2.RuntimeEvent.FromString,
                _registered_method=True)
        self.CollectRuntimeArtifacts = channel.unary_unary(
                '/runtime_controller.v1.RuntimeControlService/CollectRuntimeArtifacts',
                request_serializer=runtime__controller__pb2.CollectRuntimeArtifactsRequest.SerializeToString,
                response_deserializer=runtime__controller__pb2.CollectRuntimeArtifactsResponse.FromString,
                _registered_method=True)
        self.WarmPoolStatus = channel.unary_unary(
                '/runtime_controller.v1.RuntimeControlService/WarmPoolStatus',
                request_serializer=runtime__controller__pb2.WarmPoolStatusRequest.SerializeToString,
                response_deserializer=runtime__controller__pb2.WarmPoolStatusResponse.FromString,
                _registered_method=True)
        self.WarmPoolConfig = channel.unary_unary(
                '/runtime_controller.v1.RuntimeControlService/WarmPoolConfig',
                request_serializer=runtime__controller__pb2.WarmPoolConfigRequest.SerializeToString,
                response_deserializer=runtime__controller__pb2.WarmPoolConfigResponse.FromString,
                _registered_method=True)


class RuntimeControlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LaunchRuntime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseRuntime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeRuntime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRuntime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRuntimeEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectRuntimeArtifacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WarmPoolStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WarmPoolConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LaunchRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.LaunchRuntime,
                    request_deserializer=runtime__controller__pb2.LaunchRuntimeRequest.FromString,
                    response_serializer=runtime__controller__pb2.LaunchRuntimeResponse.SerializeToString,
            ),
            'GetRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntime,
                    request_deserializer=runtime__controller__pb2.GetRuntimeRequest.FromString,
                    response_serializer=runtime__controller__pb2.GetRuntimeResponse.SerializeToString,
            ),
            'PauseRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseRuntime,
                    request_deserializer=runtime__controller__pb2.PauseRuntimeRequest.FromString,
                    response_serializer=runtime__controller__pb2.PauseRuntimeResponse.SerializeToString,
            ),
            'ResumeRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeRuntime,
                    request_deserializer=runtime__controller__pb2.ResumeRuntimeRequest.FromString,
                    response_serializer=runtime__controller__pb2.ResumeRuntimeResponse.SerializeToString,
            ),
            'StopRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRuntime,
                    request_deserializer=runtime__controller__pb2.StopRuntimeRequest.FromString,
                    response_serializer=runtime__controller__pb2.StopRuntimeResponse.SerializeToString,
            ),
            'StreamRuntimeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRuntimeEvents,
                    request_deserializer=runtime__controller__pb2.StreamRuntimeEventsRequest.FromString,
                    response_serializer=runtime__controller__pb2.RuntimeEvent.SerializeToString,
            ),
            'CollectRuntimeArtifacts': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectRuntimeArtifacts,
                    request_deserializer=runtime__controller__pb2.CollectRuntimeArtifactsRequest.FromString,
                    response_serializer=runtime__controller__pb2.CollectRuntimeArtifactsResponse.SerializeToString,
            ),
            'WarmPoolStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.WarmPoolStatus,
                    request_deserializer=runtime__controller__pb2.WarmPoolStatusRequest.FromString,
                    response_serializer=runtime__controller__pb2.WarmPoolStatusResponse.SerializeToString,
            ),
            'WarmPoolConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.WarmPoolConfig,
                    request_deserializer=runtime__controller__pb2.WarmPoolConfigRequest.FromString,
                    response_serializer=runtime__controller__pb2.WarmPoolConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'runtime_controller.v1.RuntimeControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('runtime_controller.v1.RuntimeControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeControlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LaunchRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime_controller.v1.RuntimeControlService/LaunchRuntime',
            runtime__controller__pb2.LaunchRuntimeRequest.SerializeToString,
            runtime__controller__pb2.LaunchRuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime_controller.v1.RuntimeControlService/GetRuntime',
            runtime__controller__pb2.GetRuntimeRequest.SerializeToString,
            runtime__controller__pb2.GetRuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime_controller.v1.RuntimeControlService/PauseRuntime',
            runtime__controller__pb2.PauseRuntimeRequest.SerializeToString,
            runtime__controller__pb2.PauseRuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime_controller.v1.RuntimeControlService/ResumeRuntime',
            runtime__controller__pb2.ResumeRuntimeRequest.SerializeToString,
            runtime__controller__pb2.ResumeRuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime_controller.v1.RuntimeControlService/StopRuntime',
            runtime__controller__pb2.StopRuntimeRequest.SerializeToString,
            runtime__controller__pb2.StopRuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRuntimeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/runtime_controller.v1.RuntimeControlService/StreamRuntimeEvents',
            runtime__controller__pb2.StreamRuntimeEventsRequest.SerializeToString,
            runtime__controller__pb2.RuntimeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectRuntimeArtifacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime_controller.v1.RuntimeControlService/CollectRuntimeArtifacts',
            runtime__controller__pb2.CollectRuntimeArtifactsRequest.SerializeToString,
            runtime__controller__pb2.CollectRuntimeArtifactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WarmPoolStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime_controller.v1.RuntimeControlService/WarmPoolStatus',
            runtime__controller__pb2.WarmPoolStatusRequest.SerializeToString,
            runtime__controller__pb2.WarmPoolStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WarmPoolConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime_controller.v1.RuntimeControlService/WarmPoolConfig',
            runtime__controller__pb2.WarmPoolConfigRequest.SerializeToString,
            runtime__controller__pb2.WarmPoolConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
