// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: simulation_controller.proto

package simulationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimulationConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentImage         string                 `protobuf:"bytes,1,opt,name=agent_image,json=agentImage,proto3" json:"agent_image,omitempty"`
	AgentEnv           map[string]string      `protobuf:"bytes,2,rep,name=agent_env,json=agentEnv,proto3" json:"agent_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CpuRequest         string                 `protobuf:"bytes,3,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`
	MemoryRequest      string                 `protobuf:"bytes,4,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	MaxDurationSeconds int32                  `protobuf:"varint,5,opt,name=max_duration_seconds,json=maxDurationSeconds,proto3" json:"max_duration_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SimulationConfig) Reset() {
	*x = SimulationConfig{}
	mi := &file_simulation_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationConfig) ProtoMessage() {}

func (x *SimulationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationConfig.ProtoReflect.Descriptor instead.
func (*SimulationConfig) Descriptor() ([]byte, []int) {
	return file_simulation_controller_proto_rawDescGZIP(), []int{0}
}

func (x *SimulationConfig) GetAgentImage() string {
	if x != nil {
		return x.AgentImage
	}
	return ""
}

func (x *SimulationConfig) GetAgentEnv() map[string]string {
	if x != nil {
		return x.AgentEnv
	}
	return nil
}

func (x *SimulationConfig) GetCpuRequest() string {
	if x != nil {
		return x.CpuRequest
	}
	return ""
}

func (x *SimulationConfig) GetMemoryRequest() string {
	if x != nil {
		return x.MemoryRequest
	}
	return ""
}

func (x *SimulationConfig) GetMaxDurationSeconds() int32 {
	if x != nil {
		return x.MaxDurationSeconds
	}
	return 0
}

type CreateSimulationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimulationId  string                 `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	Config        *SimulationConfig      `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSimulationRequest) Reset() {
	*x = CreateSimulationRequest{}
	mi := &file_simulation_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSimulationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSimulationRequest) ProtoMessage() {}

func (x *CreateSimulationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSimulationRequest.ProtoReflect.Descriptor instead.
func (*CreateSimulationRequest) Descriptor() ([]byte, []int) {
	return file_simulation_controller_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSimulationRequest) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

func (x *CreateSimulationRequest) GetConfig() *SimulationConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type SimulationHandle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimulationId  string                 `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationHandle) Reset() {
	*x = SimulationHandle{}
	mi := &file_simulation_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationHandle) ProtoMessage() {}

func (x *SimulationHandle) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationHandle.ProtoReflect.Descriptor instead.
func (*SimulationHandle) Descriptor() ([]byte, []int) {
	return file_simulation_controller_proto_rawDescGZIP(), []int{2}
}

func (x *SimulationHandle) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

func (x *SimulationHandle) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *SimulationHandle) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SimulationHandle) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetSimulationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimulationId  string                 `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimulationStatusRequest) Reset() {
	*x = GetSimulationStatusRequest{}
	mi := &file_simulation_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimulationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimulationStatusRequest) ProtoMessage() {}

func (x *GetSimulationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimulationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSimulationStatusRequest) Descriptor() ([]byte, []int) {
	return file_simulation_controller_proto_rawDescGZIP(), []int{3}
}

func (x *GetSimulationStatusRequest) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

type SimulationStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SimulationId   string                 `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PodName        string                 `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodPhase       string                 `protobuf:"bytes,4,opt,name=pod_phase,json=podPhase,proto3" json:"pod_phase,omitempty"`
	ElapsedSeconds int64                  `protobuf:"varint,5,opt,name=elapsed_seconds,json=elapsedSeconds,proto3" json:"elapsed_seconds,omitempty"`
	ResourceUsage  *ResourceUsage         `protobuf:"bytes,6,opt,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimulationStatus) Reset() {
	*x = SimulationStatus{}
	mi := &file_simulation_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationStatus) ProtoMessage() {}

func (x *SimulationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationStatus.ProtoReflect.Descriptor instead.
func (*SimulationStatus) Descriptor() ([]byte, []int) {
	return file_simulation_controller_proto_rawDescGZIP(), []int{4}
}

func (x *SimulationStatus) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

func (x *SimulationStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SimulationStatus) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *SimulationStatus) GetPodPhase() string {
	if x != nil {
		return x.PodPhase
	}
	return ""
}

func (x *SimulationStatus) GetElapsedSeconds() int64 {
	if x != nil {
		return x.ElapsedSeconds
	}
	return 0
}

func (x *SimulationStatus) GetResourceUsage() *ResourceUsage {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

func (x *SimulationStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SimulationStatus) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SimulationStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SimulationStatus) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type ResourceUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuRequest    string                 `protobuf:"bytes,1,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`
	MemoryRequest string                 `protobuf:"bytes,2,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	CpuLimit      string                 `protobuf:"bytes,3,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryLimit   string                 `protobuf:"bytes,4,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_simulation_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_simulation_controller_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceUsage) GetCpuRequest() string {
	if x != nil {
		return x.CpuRequest
	}
	return ""
}

func (x *ResourceUsage) GetMemoryRequest() string {
	if x != nil {
		return x.MemoryRequest
	}
	return ""
}

func (x *ResourceUsage) GetCpuLimit() string {
	if x != nil {
		return x.CpuLimit
	}
	return ""
}

func (x *ResourceUsage) GetMemoryLimit() string {
	if x != nil {
		return x.MemoryLimit
	}
	return ""
}

type StreamSimulationEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimulationId  string                 `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSimulationEventsRequest) Reset() {
	*x = StreamSimulationEventsRequest{}
	mi := &file_simulation_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSimulationEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSimulationEventsRequest) ProtoMessage() {}

func (x *StreamSimulationEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSimulationEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamSimulationEventsRequest) Descriptor() ([]byte, []int) {
	return file_simulation_controller_proto_rawDescGZIP(), []int{6}
}

func (x *StreamSimulationEventsRequest) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

type SimulationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimulationId  string                 `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Simulation    bool                   `protobuf:"varint,4,opt,name=simulation,proto3" json:"simulation,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationEvent) Reset() {
	*x = SimulationEvent{}
	mi := &file_simulation_controller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationEvent) ProtoMessage() {}

func (x *SimulationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_controller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationEvent.ProtoReflect.Descriptor instead.
func (*SimulationEvent) Descriptor() ([]byte, []int) {
	return file_simulation_controller_proto_rawDescGZIP(), []int{7}
}

func (x *SimulationEvent) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

func (x *SimulationEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SimulationEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *SimulationEvent) GetSimulation() bool {
	if x != nil {
		return x.Simulation
	}
	return false
}

func (x *SimulationEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *SimulationEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TerminateSimulationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimulationId  string                 `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateSimulationRequest) Reset() {
	*x = TerminateSimulationRequest{}
	mi := &file_simulation_controller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSimulationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSimulationRequest) ProtoMessage() {}

func (x *TerminateSimulationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_controller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateSimulationRequest.ProtoReflect.Descriptor instead.
func (*TerminateSimulationRequest) Descriptor() ([]byte, []int) {
	return file_simulation_controller_proto_rawDescGZIP(), []int{8}
}

func (x *TerminateSimulationRequest) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

func (x *TerminateSimulationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TerminateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimulationId  string                 `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateResult) Reset() {
	*x = TerminateResult{}
	mi := &file_simulation_controller_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateResult) ProtoMessage() {}

func (x *TerminateResult) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_controller_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateResult.ProtoReflect.Descriptor instead.
func (*TerminateResult) Descriptor() ([]byte, []int) {
	return file_simulation_controller_proto_rawDescGZIP(), []int{9}
}

func (x *TerminateResult) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

func (x *TerminateResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TerminateResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CollectSimulationArtifactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimulationId  string                 `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	Paths         []string               `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectSimulationArtifactsRequest) Reset() {
	*x = CollectSimulationArtifactsRequest{}
	mi := &file_simulation_controller_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectSimulationArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectSimulationArtifactsRequest) ProtoMessage() {}

func (x *CollectSimulationArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_controller_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectSimulationArtifactsRequest.ProtoReflect.Descriptor instead.
func (*CollectSimulationArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_simulation_controller_proto_rawDescGZIP(), []int{10}
}

func (x *CollectSimulationArtifactsRequest) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

func (x *CollectSimulationArtifactsRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type ArtifactCollectionResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SimulationId       string                 `protobuf:"bytes,1,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	ArtifactsCollected int32                  `protobuf:"varint,2,opt,name=artifacts_collected,json=artifactsCollected,proto3" json:"artifacts_collected,omitempty"`
	TotalBytes         int64                  `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Artifacts          []*ArtifactRef         `protobuf:"bytes,4,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Partial            bool                   `protobuf:"varint,5,opt,name=partial,proto3" json:"partial,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ArtifactCollectionResult) Reset() {
	*x = ArtifactCollectionResult{}
	mi := &file_simulation_controller_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactCollectionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactCollectionResult) ProtoMessage() {}

func (x *ArtifactCollectionResult) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_controller_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactCollectionResult.ProtoReflect.Descriptor instead.
func (*ArtifactCollectionResult) Descriptor() ([]byte, []int) {
	return file_simulation_controller_proto_rawDescGZIP(), []int{11}
}

func (x *ArtifactCollectionResult) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

func (x *ArtifactCollectionResult) GetArtifactsCollected() int32 {
	if x != nil {
		return x.ArtifactsCollected
	}
	return 0
}

func (x *ArtifactCollectionResult) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *ArtifactCollectionResult) GetArtifacts() []*ArtifactRef {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ArtifactCollectionResult) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_simulation_controller_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_controller_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_simulation_controller_proto_rawDescGZIP(), []int{12}
}

func (x *ArtifactRef) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ArtifactRef) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ArtifactRef) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactRef) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type ATEScenario struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId       string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	InputData        []byte                 `protobuf:"bytes,3,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	ScorerConfig     string                 `protobuf:"bytes,4,opt,name=scorer_config,json=scorerConfig,proto3" json:"scorer_config,omitempty"`
	QualityThreshold float64                `protobuf:"fixed64,5,opt,name=quality_threshold,json=qualityThreshold,proto3" json:"quality_threshold,omitempty"`
	SafetyRequired   bool                   `protobuf:"varint,6,opt,name=safety_required,json=safetyRequired,proto3" json:"safety_required,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ATEScenario) Reset() {
	*x = ATEScenario{}
	mi := &file_simulation_controller_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ATEScenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ATEScenario) ProtoMessage() {}

func (x *ATEScenario) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_controller_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ATEScenario.ProtoReflect.Descriptor instead.
func (*ATEScenario) Descriptor() ([]byte, []int) {
	return file_simulation_controller_proto_rawDescGZIP(), []int{13}
}

func (x *ATEScenario) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *ATEScenario) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ATEScenario) GetInputData() []byte {
	if x != nil {
		return x.InputData
	}
	return nil
}

func (x *ATEScenario) GetScorerConfig() string {
	if x != nil {
		return x.ScorerConfig
	}
	return ""
}

func (x *ATEScenario) GetQualityThreshold() float64 {
	if x != nil {
		return x.QualityThreshold
	}
	return 0
}

func (x *ATEScenario) GetSafetyRequired() bool {
	if x != nil {
		return x.SafetyRequired
	}
	return false
}

type CreateATERequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Config        *SimulationConfig      `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Scenarios     []*ATEScenario         `protobuf:"bytes,4,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	DatasetRefs   []string               `protobuf:"bytes,5,rep,name=dataset_refs,json=datasetRefs,proto3" json:"dataset_refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateATERequest) Reset() {
	*x = CreateATERequest{}
	mi := &file_simulation_controller_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateATERequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateATERequest) ProtoMessage() {}

func (x *CreateATERequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_controller_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateATERequest.ProtoReflect.Descriptor instead.
func (*CreateATERequest) Descriptor() ([]byte, []int) {
	return file_simulation_controller_proto_rawDescGZIP(), []int{14}
}

func (x *CreateATERequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateATERequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateATERequest) GetConfig() *SimulationConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateATERequest) GetScenarios() []*ATEScenario {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

func (x *CreateATERequest) GetDatasetRefs() []string {
	if x != nil {
		return x.DatasetRefs
	}
	return nil
}

type ATEHandle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SimulationId  string                 `protobuf:"bytes,2,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ScenarioCount int32                  `protobuf:"varint,4,opt,name=scenario_count,json=scenarioCount,proto3" json:"scenario_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ATEHandle) Reset() {
	*x = ATEHandle{}
	mi := &file_simulation_controller_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ATEHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ATEHandle) ProtoMessage() {}

func (x *ATEHandle) ProtoReflect() protoreflect.Message {
	mi := &file_simulation_controller_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ATEHandle.ProtoReflect.Descriptor instead.
func (*ATEHandle) Descriptor() ([]byte, []int) {
	return file_simulation_controller_proto_rawDescGZIP(), []int{15}
}

func (x *ATEHandle) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ATEHandle) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

func (x *ATEHandle) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ATEHandle) GetScenarioCount() int32 {
	if x != nil {
		return x.ScenarioCount
	}
	return 0
}

func (x *ATEHandle) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_simulation_controller_proto protoreflect.FileDescriptor

const file_simulation_controller_proto_rawDesc = "" +
	"\n" +
	"\x1bsimulation_controller.proto\x12\x17musematic.simulation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x02\n" +
	"\x10SimulationConfig\x12\x1f\n" +
	"\vagent_image\x18\x01 \x01(\tR\n" +
	"agentImage\x12T\n" +
	"\tagent_env\x18\x02 \x03(\v27.musematic.simulation.v1.SimulationConfig.AgentEnvEntryR\bagentEnv\x12\x1f\n" +
	"\vcpu_request\x18\x03 \x01(\tR\n" +
	"cpuRequest\x12%\n" +
	"\x0ememory_request\x18\x04 \x01(\tR\rmemoryRequest\x120\n" +
	"\x14max_duration_seconds\x18\x05 \x01(\x05R\x12maxDurationSeconds\x1a;\n" +
	"\rAgentEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x01\n" +
	"\x17CreateSimulationRequest\x12#\n" +
	"\rsimulation_id\x18\x01 \x01(\tR\fsimulationId\x12A\n" +
	"\x06config\x18\x02 \x01(\v2).musematic.simulation.v1.SimulationConfigR\x06config\"\xa5\x01\n" +
	"\x10SimulationHandle\x12#\n" +
	"\rsimulation_id\x18\x01 \x01(\tR\fsimulationId\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"A\n" +
	"\x1aGetSimulationStatusRequest\x12#\n" +
	"\rsimulation_id\x18\x01 \x01(\tR\fsimulationId\"\xd9\x03\n" +
	"\x10SimulationStatus\x12#\n" +
	"\rsimulation_id\x18\x01 \x01(\tR\fsimulationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12\x1b\n" +
	"\tpod_phase\x18\x04 \x01(\tR\bpodPhase\x12'\n" +
	"\x0felapsed_seconds\x18\x05 \x01(\x03R\x0eelapsedSeconds\x12M\n" +
	"\x0eresource_usage\x18\x06 \x01(\v2&.musematic.simulation.v1.ResourceUsageR\rresourceUsage\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\x97\x01\n" +
	"\rResourceUsage\x12\x1f\n" +
	"\vcpu_request\x18\x01 \x01(\tR\n" +
	"cpuRequest\x12%\n" +
	"\x0ememory_request\x18\x02 \x01(\tR\rmemoryRequest\x12\x1b\n" +
	"\tcpu_limit\x18\x03 \x01(\tR\bcpuLimit\x12!\n" +
	"\fmemory_limit\x18\x04 \x01(\tR\vmemoryLimit\"D\n" +
	"\x1dStreamSimulationEventsRequest\x12#\n" +
	"\rsimulation_id\x18\x01 \x01(\tR\fsimulationId\"\xdb\x02\n" +
	"\x0fSimulationEvent\x12#\n" +
	"\rsimulation_id\x18\x01 \x01(\tR\fsimulationId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x1e\n" +
	"\n" +
	"simulation\x18\x04 \x01(\bR\n" +
	"simulation\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12R\n" +
	"\bmetadata\x18\x06 \x03(\v26.musematic.simulation.v1.SimulationEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\x1aTerminateSimulationRequest\x12#\n" +
	"\rsimulation_id\x18\x01 \x01(\tR\fsimulationId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"j\n" +
	"\x0fTerminateResult\x12#\n" +
	"\rsimulation_id\x18\x01 \x01(\tR\fsimulationId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"^\n" +
	"!CollectSimulationArtifactsRequest\x12#\n" +
	"\rsimulation_id\x18\x01 \x01(\tR\fsimulationId\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\"\xef\x01\n" +
	"\x18ArtifactCollectionResult\x12#\n" +
	"\rsimulation_id\x18\x01 \x01(\tR\fsimulationId\x12/\n" +
	"\x13artifacts_collected\x18\x02 \x01(\x05R\x12artifactsCollected\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\x12B\n" +
	"\tartifacts\x18\x04 \x03(\v2$.musematic.simulation.v1.ArtifactRefR\tartifacts\x12\x18\n" +
	"\apartial\x18\x05 \x01(\bR\apartial\"\x8a\x01\n" +
	"\vArtifactRef\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\"\xdc\x01\n" +
	"\vATEScenario\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"input_data\x18\x03 \x01(\fR\tinputData\x12#\n" +
	"\rscorer_config\x18\x04 \x01(\tR\fscorerConfig\x12+\n" +
	"\x11quality_threshold\x18\x05 \x01(\x01R\x10qualityThreshold\x12'\n" +
	"\x0fsafety_required\x18\x06 \x01(\bR\x0esafetyRequired\"\xf6\x01\n" +
	"\x10CreateATERequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12A\n" +
	"\x06config\x18\x03 \x01(\v2).musematic.simulation.v1.SimulationConfigR\x06config\x12B\n" +
	"\tscenarios\x18\x04 \x03(\v2$.musematic.simulation.v1.ATEScenarioR\tscenarios\x12!\n" +
	"\fdataset_refs\x18\x05 \x03(\tR\vdatasetRefs\"\xc9\x01\n" +
	"\tATEHandle\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rsimulation_id\x18\x02 \x01(\tR\fsimulationId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12%\n" +
	"\x0escenario_count\x18\x04 \x01(\x05R\rscenarioCount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xee\x05\n" +
	"\x18SimulationControlService\x12o\n" +
	"\x10CreateSimulation\x120.musematic.simulation.v1.CreateSimulationRequest\x1a).musematic.simulation.v1.SimulationHandle\x12u\n" +
	"\x13GetSimulationStatus\x123.musematic.simulation.v1.GetSimulationStatusRequest\x1a).musematic.simulation.v1.SimulationStatus\x12|\n" +
	"\x16StreamSimulationEvents\x126.musematic.simulation.v1.StreamSimulationEventsRequest\x1a(.musematic.simulation.v1.SimulationEvent0\x01\x12t\n" +
	"\x13TerminateSimulation\x123.musematic.simulation.v1.TerminateSimulationRequest\x1a(.musematic.simulation.v1.TerminateResult\x12\x8b\x01\n" +
	"\x1aCollectSimulationArtifacts\x12:.musematic.simulation.v1.CollectSimulationArtifactsRequest\x1a1.musematic.simulation.v1.ArtifactCollectionResult\x12h\n" +
	"\x17CreateAccreditedTestEnv\x12).musematic.simulation.v1.CreateATERequest\x1a\".musematic.simulation.v1.ATEHandleBEZCgithub.com/musematic/simulation-controller/api/grpc/v1;simulationv1b\x06proto3"

var (
	file_simulation_controller_proto_rawDescOnce sync.Once
	file_simulation_controller_proto_rawDescData []byte
)

func file_simulation_controller_proto_rawDescGZIP() []byte {
	file_simulation_controller_proto_rawDescOnce.Do(func() {
		file_simulation_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_simulation_controller_proto_rawDesc), len(file_simulation_controller_proto_rawDesc)))
	})
	return file_simulation_controller_proto_rawDescData
}

var file_simulation_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_simulation_controller_proto_goTypes = []any{
	(*SimulationConfig)(nil),                  // 0: musematic.simulation.v1.SimulationConfig
	(*CreateSimulationRequest)(nil),           // 1: musematic.simulation.v1.CreateSimulationRequest
	(*SimulationHandle)(nil),                  // 2: musematic.simulation.v1.SimulationHandle
	(*GetSimulationStatusRequest)(nil),        // 3: musematic.simulation.v1.GetSimulationStatusRequest
	(*SimulationStatus)(nil),                  // 4: musematic.simulation.v1.SimulationStatus
	(*ResourceUsage)(nil),                     // 5: musematic.simulation.v1.ResourceUsage
	(*StreamSimulationEventsRequest)(nil),     // 6: musematic.simulation.v1.StreamSimulationEventsRequest
	(*SimulationEvent)(nil),                   // 7: musematic.simulation.v1.SimulationEvent
	(*TerminateSimulationRequest)(nil),        // 8: musematic.simulation.v1.TerminateSimulationRequest
	(*TerminateResult)(nil),                   // 9: musematic.simulation.v1.TerminateResult
	(*CollectSimulationArtifactsRequest)(nil), // 10: musematic.simulation.v1.CollectSimulationArtifactsRequest
	(*ArtifactCollectionResult)(nil),          // 11: musematic.simulation.v1.ArtifactCollectionResult
	(*ArtifactRef)(nil),                       // 12: musematic.simulation.v1.ArtifactRef
	(*ATEScenario)(nil),                       // 13: musematic.simulation.v1.ATEScenario
	(*CreateATERequest)(nil),                  // 14: musematic.simulation.v1.CreateATERequest
	(*ATEHandle)(nil),                         // 15: musematic.simulation.v1.ATEHandle
	nil,                                       // 16: musematic.simulation.v1.SimulationConfig.AgentEnvEntry
	nil,                                       // 17: musematic.simulation.v1.SimulationEvent.MetadataEntry
	(*timestamppb.Timestamp)(nil),             // 18: google.protobuf.Timestamp
}
var file_simulation_controller_proto_depIdxs = []int32{
	16, // 0: musematic.simulation.v1.SimulationConfig.agent_env:type_name -> musematic.simulation.v1.SimulationConfig.AgentEnvEntry
	0,  // 1: musematic.simulation.v1.CreateSimulationRequest.config:type_name -> musematic.simulation.v1.SimulationConfig
	18, // 2: musematic.simulation.v1.SimulationHandle.created_at:type_name -> google.protobuf.Timestamp
	5,  // 3: musematic.simulation.v1.SimulationStatus.resource_usage:type_name -> musematic.simulation.v1.ResourceUsage
	18, // 4: musematic.simulation.v1.SimulationStatus.created_at:type_name -> google.protobuf.Timestamp
	18, // 5: musematic.simulation.v1.SimulationStatus.started_at:type_name -> google.protobuf.Timestamp
	18, // 6: musematic.simulation.v1.SimulationStatus.completed_at:type_name -> google.protobuf.Timestamp
	18, // 7: musematic.simulation.v1.SimulationEvent.occurred_at:type_name -> google.protobuf.Timestamp
	17, // 8: musematic.simulation.v1.SimulationEvent.metadata:type_name -> musematic.simulation.v1.SimulationEvent.MetadataEntry
	12, // 9: musematic.simulation.v1.ArtifactCollectionResult.artifacts:type_name -> musematic.simulation.v1.ArtifactRef
	0,  // 10: musematic.simulation.v1.CreateATERequest.config:type_name -> musematic.simulation.v1.SimulationConfig
	13, // 11: musematic.simulation.v1.CreateATERequest.scenarios:type_name -> musematic.simulation.v1.ATEScenario
	18, // 12: musematic.simulation.v1.ATEHandle.created_at:type_name -> google.protobuf.Timestamp
	1,  // 13: musematic.simulation.v1.SimulationControlService.CreateSimulation:input_type -> musematic.simulation.v1.CreateSimulationRequest
	3,  // 14: musematic.simulation.v1.SimulationControlService.GetSimulationStatus:input_type -> musematic.simulation.v1.GetSimulationStatusRequest
	6,  // 15: musematic.simulation.v1.SimulationControlService.StreamSimulationEvents:input_type -> musematic.simulation.v1.StreamSimulationEventsRequest
	8,  // 16: musematic.simulation.v1.SimulationControlService.TerminateSimulation:input_type -> musematic.simulation.v1.TerminateSimulationRequest
	10, // 17: musematic.simulation.v1.SimulationControlService.CollectSimulationArtifacts:input_type -> musematic.simulation.v1.CollectSimulationArtifactsRequest
	14, // 18: musematic.simulation.v1.SimulationControlService.CreateAccreditedTestEnv:input_type -> musematic.simulation.v1.CreateATERequest
	2,  // 19: musematic.simulation.v1.SimulationControlService.CreateSimulation:output_type -> musematic.simulation.v1.SimulationHandle
	4,  // 20: musematic.simulation.v1.SimulationControlService.GetSimulationStatus:output_type -> musematic.simulation.v1.SimulationStatus
	7,  // 21: musematic.simulation.v1.SimulationControlService.StreamSimulationEvents:output_type -> musematic.simulation.v1.SimulationEvent
	9,  // 22: musematic.simulation.v1.SimulationControlService.TerminateSimulation:output_type -> musematic.simulation.v1.TerminateResult
	11, // 23: musematic.simulation.v1.SimulationControlService.CollectSimulationArtifacts:output_type -> musematic.simulation.v1.ArtifactCollectionResult
	15, // 24: musematic.simulation.v1.SimulationControlService.CreateAccreditedTestEnv:output_type -> musematic.simulation.v1.ATEHandle
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_simulation_controller_proto_init() }
func file_simulation_controller_proto_init() {
	if File_simulation_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_simulation_controller_proto_rawDesc), len(file_simulation_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_simulation_controller_proto_goTypes,
		DependencyIndexes: file_simulation_controller_proto_depIdxs,
		MessageInfos:      file_simulation_controller_proto_msgTypes,
	}.Build()
	File_simulation_controller_proto = out.File
	file_simulation_controller_proto_goTypes = nil
	file_simulation_controller_proto_depIdxs = nil
}
