// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: simulation_controller.proto

package simulationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SimulationControlService_CreateSimulation_FullMethodName           = "/musematic.simulation.v1.SimulationControlService/CreateSimulation"
	SimulationControlService_GetSimulationStatus_FullMethodName        = "/musematic.simulation.v1.SimulationControlService/GetSimulationStatus"
	SimulationControlService_StreamSimulationEvents_FullMethodName     = "/musematic.simulation.v1.SimulationControlService/StreamSimulationEvents"
	SimulationControlService_TerminateSimulation_FullMethodName        = "/musematic.simulation.v1.SimulationControlService/TerminateSimulation"
	SimulationControlService_CollectSimulationArtifacts_FullMethodName = "/musematic.simulation.v1.SimulationControlService/CollectSimulationArtifacts"
	SimulationControlService_CreateAccreditedTestEnv_FullMethodName    = "/musematic.simulation.v1.SimulationControlService/CreateAccreditedTestEnv"
)

// SimulationControlServiceClient is the client API for SimulationControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimulationControlServiceClient interface {
	CreateSimulation(ctx context.Context, in *CreateSimulationRequest, opts ...grpc.CallOption) (*SimulationHandle, error)
	GetSimulationStatus(ctx context.Context, in *GetSimulationStatusRequest, opts ...grpc.CallOption) (*SimulationStatus, error)
	StreamSimulationEvents(ctx context.Context, in *StreamSimulationEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SimulationEvent], error)
	TerminateSimulation(ctx context.Context, in *TerminateSimulationRequest, opts ...grpc.CallOption) (*TerminateResult, error)
	CollectSimulationArtifacts(ctx context.Context, in *CollectSimulationArtifactsRequest, opts ...grpc.CallOption) (*ArtifactCollectionResult, error)
	CreateAccreditedTestEnv(ctx context.Context, in *CreateATERequest, opts ...grpc.CallOption) (*ATEHandle, error)
}

type simulationControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulationControlServiceClient(cc grpc.ClientConnInterface) SimulationControlServiceClient {
	return &simulationControlServiceClient{cc}
}

func (c *simulationControlServiceClient) CreateSimulation(ctx context.Context, in *CreateSimulationRequest, opts ...grpc.CallOption) (*SimulationHandle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulationHandle)
	err := c.cc.Invoke(ctx, SimulationControlService_CreateSimulation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationControlServiceClient) GetSimulationStatus(ctx context.Context, in *GetSimulationStatusRequest, opts ...grpc.CallOption) (*SimulationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulationStatus)
	err := c.cc.Invoke(ctx, SimulationControlService_GetSimulationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationControlServiceClient) StreamSimulationEvents(ctx context.Context, in *StreamSimulationEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SimulationEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SimulationControlService_ServiceDesc.Streams[0], SimulationControlService_StreamSimulationEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamSimulationEventsRequest, SimulationEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimulationControlService_StreamSimulationEventsClient = grpc.ServerStreamingClient[SimulationEvent]

func (c *simulationControlServiceClient) TerminateSimulation(ctx context.Context, in *TerminateSimulationRequest, opts ...grpc.CallOption) (*TerminateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateResult)
	err := c.cc.Invoke(ctx, SimulationControlService_TerminateSimulation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationControlServiceClient) CollectSimulationArtifacts(ctx context.Context, in *CollectSimulationArtifactsRequest, opts ...grpc.CallOption) (*ArtifactCollectionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactCollectionResult)
	err := c.cc.Invoke(ctx, SimulationControlService_CollectSimulationArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationControlServiceClient) CreateAccreditedTestEnv(ctx context.Context, in *CreateATERequest, opts ...grpc.CallOption) (*ATEHandle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ATEHandle)
	err := c.cc.Invoke(ctx, SimulationControlService_CreateAccreditedTestEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimulationControlServiceServer is the server API for SimulationControlService service.
// All implementations must embed UnimplementedSimulationControlServiceServer
// for forward compatibility.
type SimulationControlServiceServer interface {
	CreateSimulation(context.Context, *CreateSimulationRequest) (*SimulationHandle, error)
	GetSimulationStatus(context.Context, *GetSimulationStatusRequest) (*SimulationStatus, error)
	StreamSimulationEvents(*StreamSimulationEventsRequest, grpc.ServerStreamingServer[SimulationEvent]) error
	TerminateSimulation(context.Context, *TerminateSimulationRequest) (*TerminateResult, error)
	CollectSimulationArtifacts(context.Context, *CollectSimulationArtifactsRequest) (*ArtifactCollectionResult, error)
	CreateAccreditedTestEnv(context.Context, *CreateATERequest) (*ATEHandle, error)
	mustEmbedUnimplementedSimulationControlServiceServer()
}

// UnimplementedSimulationControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimulationControlServiceServer struct{}

func (UnimplementedSimulationControlServiceServer) CreateSimulation(context.Context, *CreateSimulationRequest) (*SimulationHandle, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSimulation not implemented")
}
func (UnimplementedSimulationControlServiceServer) GetSimulationStatus(context.Context, *GetSimulationStatusRequest) (*SimulationStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSimulationStatus not implemented")
}
func (UnimplementedSimulationControlServiceServer) StreamSimulationEvents(*StreamSimulationEventsRequest, grpc.ServerStreamingServer[SimulationEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamSimulationEvents not implemented")
}
func (UnimplementedSimulationControlServiceServer) TerminateSimulation(context.Context, *TerminateSimulationRequest) (*TerminateResult, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateSimulation not implemented")
}
func (UnimplementedSimulationControlServiceServer) CollectSimulationArtifacts(context.Context, *CollectSimulationArtifactsRequest) (*ArtifactCollectionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectSimulationArtifacts not implemented")
}
func (UnimplementedSimulationControlServiceServer) CreateAccreditedTestEnv(context.Context, *CreateATERequest) (*ATEHandle, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccreditedTestEnv not implemented")
}
func (UnimplementedSimulationControlServiceServer) mustEmbedUnimplementedSimulationControlServiceServer() {
}
func (UnimplementedSimulationControlServiceServer) testEmbeddedByValue() {}

// UnsafeSimulationControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulationControlServiceServer will
// result in compilation errors.
type UnsafeSimulationControlServiceServer interface {
	mustEmbedUnimplementedSimulationControlServiceServer()
}

func RegisterSimulationControlServiceServer(s grpc.ServiceRegistrar, srv SimulationControlServiceServer) {
	// If the following call panics, it indicates UnimplementedSimulationControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SimulationControlService_ServiceDesc, srv)
}

func _SimulationControlService_CreateSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationControlServiceServer).CreateSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationControlService_CreateSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationControlServiceServer).CreateSimulation(ctx, req.(*CreateSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationControlService_GetSimulationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSimulationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationControlServiceServer).GetSimulationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationControlService_GetSimulationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationControlServiceServer).GetSimulationStatus(ctx, req.(*GetSimulationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationControlService_StreamSimulationEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSimulationEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SimulationControlServiceServer).StreamSimulationEvents(m, &grpc.GenericServerStream[StreamSimulationEventsRequest, SimulationEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimulationControlService_StreamSimulationEventsServer = grpc.ServerStreamingServer[SimulationEvent]

func _SimulationControlService_TerminateSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationControlServiceServer).TerminateSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationControlService_TerminateSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationControlServiceServer).TerminateSimulation(ctx, req.(*TerminateSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationControlService_CollectSimulationArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectSimulationArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationControlServiceServer).CollectSimulationArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationControlService_CollectSimulationArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationControlServiceServer).CollectSimulationArtifacts(ctx, req.(*CollectSimulationArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationControlService_CreateAccreditedTestEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateATERequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationControlServiceServer).CreateAccreditedTestEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationControlService_CreateAccreditedTestEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationControlServiceServer).CreateAccreditedTestEnv(ctx, req.(*CreateATERequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SimulationControlService_ServiceDesc is the grpc.ServiceDesc for SimulationControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimulationControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "musematic.simulation.v1.SimulationControlService",
	HandlerType: (*SimulationControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSimulation",
			Handler:    _SimulationControlService_CreateSimulation_Handler,
		},
		{
			MethodName: "GetSimulationStatus",
			Handler:    _SimulationControlService_GetSimulationStatus_Handler,
		},
		{
			MethodName: "TerminateSimulation",
			Handler:    _SimulationControlService_TerminateSimulation_Handler,
		},
		{
			MethodName: "CollectSimulationArtifacts",
			Handler:    _SimulationControlService_CollectSimulationArtifacts_Handler,
		},
		{
			MethodName: "CreateAccreditedTestEnv",
			Handler:    _SimulationControlService_CreateAccreditedTestEnv_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSimulationEvents",
			Handler:       _SimulationControlService_StreamSimulationEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "simulation_controller.proto",
}
