run:
  timeout: 5m

issues:
  exclude-use-default: false

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosec
    - gocyclo
    - dupl

linters-settings:
  gocyclo:
    min-complexity: 15
