apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ coalesce (index .Values "redis-cluster" "password") .Values.global.redis.password .Values.auth.password | quote }}

