apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configSecretRef }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_DSN: {{ .Values.secrets.POSTGRES_DSN | quote }}
  REDIS_ADDR: {{ .Values.secrets.REDIS_ADDR | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.REDIS_PASSWORD | quote }}
  KAFKA_BROKERS: {{ .Values.secrets.KAFKA_BROKERS | quote }}
  MINIO_ENDPOINT: {{ .Values.secrets.MINIO_ENDPOINT | quote }}
  MINIO_BUCKET: {{ .Values.secrets.MINIO_BUCKET | quote }}
