apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: musematic-runtime-controller
subjects:
  - kind: ServiceAccount
    name: musematic-runtime-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: musematic-runtime-controller
