{{- range .Values.topics }}
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: {{ printf "%s.dlq" (.name | replace "_" "-") }}
  namespace: {{ $.Values.namespace }}
  labels:
    strimzi.io/cluster: {{ $.Values.clusterName }}
spec:
  topicName: {{ .name }}.dlq
  partitions: {{ $.Values.dlqPartitions }}
  replicas: {{ $.Values.replicationFactor }}
  config:
    retention.ms: {{ $.Values.dlqRetentionMs | int64 | quote }}
---
{{- end }}

