{{- if not .Values.combined }}
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: {{ .Values.clusterName }}-broker
  namespace: {{ .Values.namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
spec:
  replicas: {{ .Values.brokerReplicas }}
  roles:
    - broker
  {{- with .Values.jvmOptions }}
  jvmOptions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  storage:
    type: persistent-claim
    size: {{ .Values.storage.size | quote }}
    class: {{ .Values.storage.class | quote }}
    deleteClaim: false
{{- end }}
