{{- if not .Values.combined }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: {{ .Values.clusterName }}-controller
  namespace: {{ .Values.namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
spec:
  replicas: {{ .Values.controllerReplicas }}
  roles:
    - controller
  storage:
    type: persistent-claim
    size: {{ .Values.storage.size | quote }}
    class: {{ .Values.storage.class | quote }}
    deleteClaim: false
{{- end }}

