{{- range .Values.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    strimzi.io/cluster: {{ $.Values.clusterName }}
spec:
  partitions: {{ .partitions }}
  replicas: {{ $.Values.replicationFactor }}
  config:
    retention.ms: {{ .retentionMs | quote }}
    min.insync.replicas: {{ $.Values.minInsyncReplicas | quote }}
---
{{- end }}

