{{- range .Values.topics }}
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: {{ .name | replace "_" "-" }}
  namespace: {{ $.Values.namespace }}
  labels:
    strimzi.io/cluster: {{ $.Values.clusterName }}
spec:
  topicName: {{ .name }}
  partitions: {{ .partitions }}
  replicas: {{ $.Values.replicationFactor }}
  config:
    retention.ms: {{ .retentionMs | int64 | quote }}
    min.insync.replicas: {{ $.Values.minInsyncReplicas | int64 | quote }}
---
{{- end }}

