apiVersion: v1
kind: ConfigMap
metadata:
  name: musematic-clickhouse-server-config
  namespace: {{ .Release.Namespace }}
data:
  config.xml: |
    <clickhouse>
      <listen_host>0.0.0.0</listen_host>
      <listen_try>1</listen_try>
      <http_port>{{ .Values.service.httpPort }}</http_port>
      <tcp_port>{{ .Values.service.nativePort }}</tcp_port>
      <interserver_http_port>{{ .Values.service.interserverHttpPort }}</interserver_http_port>
{{- if .Values.clickhouse.keeper.enabled }}
      <zookeeper>
        <node>
          <host>musematic-clickhouse-keeper.{{ .Release.Namespace }}.svc.cluster.local</host>
          <port>9181</port>
        </node>
      </zookeeper>
{{- end }}
    </clickhouse>
