{{- $existing := lookup "v1" "Secret" .Release.Namespace "clickhouse-credentials" -}}
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  CLICKHOUSE_PASSWORD: {{ (and $existing $existing.data $existing.data.CLICKHOUSE_PASSWORD | ternary ($existing.data.CLICKHOUSE_PASSWORD | b64dec) (randAlphaNum 32)) | quote }}
