apiVersion: v1
kind: Service
metadata:
  name: musematic-clickhouse
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: clickhouse
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: native
      port: {{ .Values.service.nativePort }}
      targetPort: native
