{{- $namespace := include "musematic.minio.namespace" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: minio-platform-credentials
  namespace: {{ $namespace }}
type: Opaque
stringData:
  MINIO_ACCESS_KEY: {{ include "musematic.minio.lookupOrDefault" (dict "namespace" $namespace "name" "minio-platform-credentials" "key" "MINIO_ACCESS_KEY" "default" "platform") | quote }}
  MINIO_SECRET_KEY: {{ include "musematic.minio.lookupOrDefault" (dict "namespace" $namespace "name" "minio-platform-credentials" "key" "MINIO_SECRET_KEY" "default" (randAlphaNum 32)) | quote }}
