redis-cluster:
  cluster:
    nodes: 6
    replicas: 1
  redis:
    maxmemory: "4Gi"
  persistence:
    size: 100Gi
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 5Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  pdb:
    create: true
    maxUnavailable: 1

networkPolicy:
  enabled: true
