createNamespace: true

auth:
  password: change-me

global:
  redis:
    password: change-me

redis-cluster:
  image:
    repository: bitnamilegacy/redis-cluster
    tag: 8.2.1-debian-12-r0
  fullnameOverride: musematic-redis
  password: change-me
  existingSecret: redis-credentials
  existingSecretPasswordKey: password
  persistence:
    enabled: true
    appendonly: "yes"
    appendfsync: "everysec"
  redis:
    maxmemoryPolicy: "allkeys-lru"
    extraFlags:
      - "--cluster-node-timeout"
      - "15000"
      - "--cluster-require-full-coverage"
      - "no"
  service:
    type: ClusterIP
    port: 6379

networkPolicy:
  enabled: false

