WARM_LAUNCH_MAX_SECONDS = 2.0
COLD_LAUNCH_MAX_SECONDS = 10.0
TRIVIAL_AGENT_ROUNDTRIP_MAX_SECONDS = 5.0
CONCURRENT_EXECUTION_COUNT = 10
CONCURRENT_MAX_WALL_CLOCK_SECONDS = 15.0
REASONING_OVERHEAD_MAX_MS = 50
REASONING_BASELINE_ITERATIONS = 100
