apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-jaeger
  namespace: {{ include "musematic-observability.namespace" . }}
  labels:
{{ include "musematic-observability.dataSourceLabels" . | indent 4 }}
data:
  jaeger.yaml: |
    apiVersion: 1
    datasources:
      - name: Jaeger
        uid: jaeger
        type: jaeger
        access: proxy
        url: http://musematic-observability-jaeger-query.platform-observability.svc.cluster.local:16686
        isDefault: false
        editable: false
