apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-prometheus
  namespace: {{ include "musematic-observability.namespace" . }}
  labels:
{{ include "musematic-observability.dataSourceLabels" . | indent 4 }}
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://observability-kube-prometh-prometheus.{{ include "musematic-observability.namespace" . }}.svc.cluster.local:9090
        isDefault: true
        editable: false
