apiVersion: v1
kind: Secret
metadata:
  name: {{ include "musematic-control-plane.secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_DSN: {{ .Values.connections.postgresDsn | quote }}
  DATABASE_URL: {{ .Values.connections.postgresDsn | quote }}
  NEO4J_PASSWORD: {{ .Values.connections.neo4jPassword | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.connections.clickhousePassword | quote }}
  OPENSEARCH_PASSWORD: {{ .Values.connections.opensearchPassword | quote }}
  S3_ACCESS_KEY: {{ .Values.connections.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ .Values.connections.s3SecretKey | quote }}
  AUTH_JWT_SECRET_KEY: {{ .Values.connections.authJwtSecretKey | quote }}
  AUTH_MFA_ENCRYPTION_KEY: {{ .Values.connections.authMfaEncryptionKey | quote }}
