{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "musematic-control-plane.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "musematic-control-plane.componentLabels" . | indent 4 }}
  annotations:
    vault.hashicorp.com/role: {{ .Values.vault.kubernetes.role | quote }}
{{- range $name, $value := .Values.serviceAccount.annotations }}
    {{ $name }}: {{ $value | quote }}
{{- end }}
{{- end }}
