// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: runtime_controller.proto

package runtimecontrollerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeControlService_LaunchRuntime_FullMethodName           = "/runtime_controller.v1.RuntimeControlService/LaunchRuntime"
	RuntimeControlService_GetRuntime_FullMethodName              = "/runtime_controller.v1.RuntimeControlService/GetRuntime"
	RuntimeControlService_PauseRuntime_FullMethodName            = "/runtime_controller.v1.RuntimeControlService/PauseRuntime"
	RuntimeControlService_ResumeRuntime_FullMethodName           = "/runtime_controller.v1.RuntimeControlService/ResumeRuntime"
	RuntimeControlService_StopRuntime_FullMethodName             = "/runtime_controller.v1.RuntimeControlService/StopRuntime"
	RuntimeControlService_StreamRuntimeEvents_FullMethodName     = "/runtime_controller.v1.RuntimeControlService/StreamRuntimeEvents"
	RuntimeControlService_CollectRuntimeArtifacts_FullMethodName = "/runtime_controller.v1.RuntimeControlService/CollectRuntimeArtifacts"
	RuntimeControlService_WarmPoolStatus_FullMethodName          = "/runtime_controller.v1.RuntimeControlService/WarmPoolStatus"
	RuntimeControlService_WarmPoolConfig_FullMethodName          = "/runtime_controller.v1.RuntimeControlService/WarmPoolConfig"
)

// RuntimeControlServiceClient is the client API for RuntimeControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuntimeControlServiceClient interface {
	LaunchRuntime(ctx context.Context, in *LaunchRuntimeRequest, opts ...grpc.CallOption) (*LaunchRuntimeResponse, error)
	GetRuntime(ctx context.Context, in *GetRuntimeRequest, opts ...grpc.CallOption) (*GetRuntimeResponse, error)
	PauseRuntime(ctx context.Context, in *PauseRuntimeRequest, opts ...grpc.CallOption) (*PauseRuntimeResponse, error)
	ResumeRuntime(ctx context.Context, in *ResumeRuntimeRequest, opts ...grpc.CallOption) (*ResumeRuntimeResponse, error)
	StopRuntime(ctx context.Context, in *StopRuntimeRequest, opts ...grpc.CallOption) (*StopRuntimeResponse, error)
	StreamRuntimeEvents(ctx context.Context, in *StreamRuntimeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuntimeEvent], error)
	CollectRuntimeArtifacts(ctx context.Context, in *CollectRuntimeArtifactsRequest, opts ...grpc.CallOption) (*CollectRuntimeArtifactsResponse, error)
	WarmPoolStatus(ctx context.Context, in *WarmPoolStatusRequest, opts ...grpc.CallOption) (*WarmPoolStatusResponse, error)
	WarmPoolConfig(ctx context.Context, in *WarmPoolConfigRequest, opts ...grpc.CallOption) (*WarmPoolConfigResponse, error)
}

type runtimeControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeControlServiceClient(cc grpc.ClientConnInterface) RuntimeControlServiceClient {
	return &runtimeControlServiceClient{cc}
}

func (c *runtimeControlServiceClient) LaunchRuntime(ctx context.Context, in *LaunchRuntimeRequest, opts ...grpc.CallOption) (*LaunchRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LaunchRuntimeResponse)
	err := c.cc.Invoke(ctx, RuntimeControlService_LaunchRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeControlServiceClient) GetRuntime(ctx context.Context, in *GetRuntimeRequest, opts ...grpc.CallOption) (*GetRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuntimeResponse)
	err := c.cc.Invoke(ctx, RuntimeControlService_GetRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeControlServiceClient) PauseRuntime(ctx context.Context, in *PauseRuntimeRequest, opts ...grpc.CallOption) (*PauseRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseRuntimeResponse)
	err := c.cc.Invoke(ctx, RuntimeControlService_PauseRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeControlServiceClient) ResumeRuntime(ctx context.Context, in *ResumeRuntimeRequest, opts ...grpc.CallOption) (*ResumeRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeRuntimeResponse)
	err := c.cc.Invoke(ctx, RuntimeControlService_ResumeRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeControlServiceClient) StopRuntime(ctx context.Context, in *StopRuntimeRequest, opts ...grpc.CallOption) (*StopRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopRuntimeResponse)
	err := c.cc.Invoke(ctx, RuntimeControlService_StopRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeControlServiceClient) StreamRuntimeEvents(ctx context.Context, in *StreamRuntimeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuntimeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuntimeControlService_ServiceDesc.Streams[0], RuntimeControlService_StreamRuntimeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRuntimeEventsRequest, RuntimeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeControlService_StreamRuntimeEventsClient = grpc.ServerStreamingClient[RuntimeEvent]

func (c *runtimeControlServiceClient) CollectRuntimeArtifacts(ctx context.Context, in *CollectRuntimeArtifactsRequest, opts ...grpc.CallOption) (*CollectRuntimeArtifactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectRuntimeArtifactsResponse)
	err := c.cc.Invoke(ctx, RuntimeControlService_CollectRuntimeArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeControlServiceClient) WarmPoolStatus(ctx context.Context, in *WarmPoolStatusRequest, opts ...grpc.CallOption) (*WarmPoolStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarmPoolStatusResponse)
	err := c.cc.Invoke(ctx, RuntimeControlService_WarmPoolStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeControlServiceClient) WarmPoolConfig(ctx context.Context, in *WarmPoolConfigRequest, opts ...grpc.CallOption) (*WarmPoolConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarmPoolConfigResponse)
	err := c.cc.Invoke(ctx, RuntimeControlService_WarmPoolConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeControlServiceServer is the server API for RuntimeControlService service.
// All implementations must embed UnimplementedRuntimeControlServiceServer
// for forward compatibility.
type RuntimeControlServiceServer interface {
	LaunchRuntime(context.Context, *LaunchRuntimeRequest) (*LaunchRuntimeResponse, error)
	GetRuntime(context.Context, *GetRuntimeRequest) (*GetRuntimeResponse, error)
	PauseRuntime(context.Context, *PauseRuntimeRequest) (*PauseRuntimeResponse, error)
	ResumeRuntime(context.Context, *ResumeRuntimeRequest) (*ResumeRuntimeResponse, error)
	StopRuntime(context.Context, *StopRuntimeRequest) (*StopRuntimeResponse, error)
	StreamRuntimeEvents(*StreamRuntimeEventsRequest, grpc.ServerStreamingServer[RuntimeEvent]) error
	CollectRuntimeArtifacts(context.Context, *CollectRuntimeArtifactsRequest) (*CollectRuntimeArtifactsResponse, error)
	WarmPoolStatus(context.Context, *WarmPoolStatusRequest) (*WarmPoolStatusResponse, error)
	WarmPoolConfig(context.Context, *WarmPoolConfigRequest) (*WarmPoolConfigResponse, error)
	mustEmbedUnimplementedRuntimeControlServiceServer()
}

// UnimplementedRuntimeControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeControlServiceServer struct{}

func (UnimplementedRuntimeControlServiceServer) LaunchRuntime(context.Context, *LaunchRuntimeRequest) (*LaunchRuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LaunchRuntime not implemented")
}
func (UnimplementedRuntimeControlServiceServer) GetRuntime(context.Context, *GetRuntimeRequest) (*GetRuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRuntime not implemented")
}
func (UnimplementedRuntimeControlServiceServer) PauseRuntime(context.Context, *PauseRuntimeRequest) (*PauseRuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseRuntime not implemented")
}
func (UnimplementedRuntimeControlServiceServer) ResumeRuntime(context.Context, *ResumeRuntimeRequest) (*ResumeRuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeRuntime not implemented")
}
func (UnimplementedRuntimeControlServiceServer) StopRuntime(context.Context, *StopRuntimeRequest) (*StopRuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopRuntime not implemented")
}
func (UnimplementedRuntimeControlServiceServer) StreamRuntimeEvents(*StreamRuntimeEventsRequest, grpc.ServerStreamingServer[RuntimeEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamRuntimeEvents not implemented")
}
func (UnimplementedRuntimeControlServiceServer) CollectRuntimeArtifacts(context.Context, *CollectRuntimeArtifactsRequest) (*CollectRuntimeArtifactsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectRuntimeArtifacts not implemented")
}
func (UnimplementedRuntimeControlServiceServer) WarmPoolStatus(context.Context, *WarmPoolStatusRequest) (*WarmPoolStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WarmPoolStatus not implemented")
}
func (UnimplementedRuntimeControlServiceServer) WarmPoolConfig(context.Context, *WarmPoolConfigRequest) (*WarmPoolConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WarmPoolConfig not implemented")
}
func (UnimplementedRuntimeControlServiceServer) mustEmbedUnimplementedRuntimeControlServiceServer() {}
func (UnimplementedRuntimeControlServiceServer) testEmbeddedByValue()                               {}

// UnsafeRuntimeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeControlServiceServer will
// result in compilation errors.
type UnsafeRuntimeControlServiceServer interface {
	mustEmbedUnimplementedRuntimeControlServiceServer()
}

func RegisterRuntimeControlServiceServer(s grpc.ServiceRegistrar, srv RuntimeControlServiceServer) {
	// If the following call pancis, it indicates UnimplementedRuntimeControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeControlService_ServiceDesc, srv)
}

func _RuntimeControlService_LaunchRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaunchRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeControlServiceServer).LaunchRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeControlService_LaunchRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeControlServiceServer).LaunchRuntime(ctx, req.(*LaunchRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeControlService_GetRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeControlServiceServer).GetRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeControlService_GetRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeControlServiceServer).GetRuntime(ctx, req.(*GetRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeControlService_PauseRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeControlServiceServer).PauseRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeControlService_PauseRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeControlServiceServer).PauseRuntime(ctx, req.(*PauseRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeControlService_ResumeRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeControlServiceServer).ResumeRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeControlService_ResumeRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeControlServiceServer).ResumeRuntime(ctx, req.(*ResumeRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeControlService_StopRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeControlServiceServer).StopRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeControlService_StopRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeControlServiceServer).StopRuntime(ctx, req.(*StopRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeControlService_StreamRuntimeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRuntimeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeControlServiceServer).StreamRuntimeEvents(m, &grpc.GenericServerStream[StreamRuntimeEventsRequest, RuntimeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeControlService_StreamRuntimeEventsServer = grpc.ServerStreamingServer[RuntimeEvent]

func _RuntimeControlService_CollectRuntimeArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRuntimeArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeControlServiceServer).CollectRuntimeArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeControlService_CollectRuntimeArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeControlServiceServer).CollectRuntimeArtifacts(ctx, req.(*CollectRuntimeArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeControlService_WarmPoolStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WarmPoolStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeControlServiceServer).WarmPoolStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeControlService_WarmPoolStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeControlServiceServer).WarmPoolStatus(ctx, req.(*WarmPoolStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeControlService_WarmPoolConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WarmPoolConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeControlServiceServer).WarmPoolConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeControlService_WarmPoolConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeControlServiceServer).WarmPoolConfig(ctx, req.(*WarmPoolConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuntimeControlService_ServiceDesc is the grpc.ServiceDesc for RuntimeControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime_controller.v1.RuntimeControlService",
	HandlerType: (*RuntimeControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LaunchRuntime",
			Handler:    _RuntimeControlService_LaunchRuntime_Handler,
		},
		{
			MethodName: "GetRuntime",
			Handler:    _RuntimeControlService_GetRuntime_Handler,
		},
		{
			MethodName: "PauseRuntime",
			Handler:    _RuntimeControlService_PauseRuntime_Handler,
		},
		{
			MethodName: "ResumeRuntime",
			Handler:    _RuntimeControlService_ResumeRuntime_Handler,
		},
		{
			MethodName: "StopRuntime",
			Handler:    _RuntimeControlService_StopRuntime_Handler,
		},
		{
			MethodName: "CollectRuntimeArtifacts",
			Handler:    _RuntimeControlService_CollectRuntimeArtifacts_Handler,
		},
		{
			MethodName: "WarmPoolStatus",
			Handler:    _RuntimeControlService_WarmPoolStatus_Handler,
		},
		{
			MethodName: "WarmPoolConfig",
			Handler:    _RuntimeControlService_WarmPoolConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRuntimeEvents",
			Handler:       _RuntimeControlService_StreamRuntimeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "runtime_controller.proto",
}
