// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: runtime_controller.proto

package runtimecontrollerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeState int32

const (
	RuntimeState_RUNTIME_STATE_UNSPECIFIED   RuntimeState = 0
	RuntimeState_RUNTIME_STATE_PENDING       RuntimeState = 1
	RuntimeState_RUNTIME_STATE_RUNNING       RuntimeState = 2
	RuntimeState_RUNTIME_STATE_PAUSED        RuntimeState = 3
	RuntimeState_RUNTIME_STATE_STOPPED       RuntimeState = 4
	RuntimeState_RUNTIME_STATE_FORCE_STOPPED RuntimeState = 5
	RuntimeState_RUNTIME_STATE_FAILED        RuntimeState = 6
)

// Enum value maps for RuntimeState.
var (
	RuntimeState_name = map[int32]string{
		0: "RUNTIME_STATE_UNSPECIFIED",
		1: "RUNTIME_STATE_PENDING",
		2: "RUNTIME_STATE_RUNNING",
		3: "RUNTIME_STATE_PAUSED",
		4: "RUNTIME_STATE_STOPPED",
		5: "RUNTIME_STATE_FORCE_STOPPED",
		6: "RUNTIME_STATE_FAILED",
	}
	RuntimeState_value = map[string]int32{
		"RUNTIME_STATE_UNSPECIFIED":   0,
		"RUNTIME_STATE_PENDING":       1,
		"RUNTIME_STATE_RUNNING":       2,
		"RUNTIME_STATE_PAUSED":        3,
		"RUNTIME_STATE_STOPPED":       4,
		"RUNTIME_STATE_FORCE_STOPPED": 5,
		"RUNTIME_STATE_FAILED":        6,
	}
)

func (x RuntimeState) Enum() *RuntimeState {
	p := new(RuntimeState)
	*p = x
	return p
}

func (x RuntimeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeState) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_controller_proto_enumTypes[0].Descriptor()
}

func (RuntimeState) Type() protoreflect.EnumType {
	return &file_runtime_controller_proto_enumTypes[0]
}

func (x RuntimeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeState.Descriptor instead.
func (RuntimeState) EnumDescriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{0}
}

type RuntimeEventType int32

const (
	RuntimeEventType_RUNTIME_EVENT_UNSPECIFIED        RuntimeEventType = 0
	RuntimeEventType_RUNTIME_EVENT_LAUNCHED           RuntimeEventType = 1
	RuntimeEventType_RUNTIME_EVENT_PAUSED             RuntimeEventType = 2
	RuntimeEventType_RUNTIME_EVENT_RESUMED            RuntimeEventType = 3
	RuntimeEventType_RUNTIME_EVENT_STOPPED            RuntimeEventType = 4
	RuntimeEventType_RUNTIME_EVENT_FORCE_STOPPED      RuntimeEventType = 5
	RuntimeEventType_RUNTIME_EVENT_FAILED             RuntimeEventType = 6
	RuntimeEventType_RUNTIME_EVENT_HEARTBEAT          RuntimeEventType = 7
	RuntimeEventType_RUNTIME_EVENT_ARTIFACT_COLLECTED RuntimeEventType = 8
	RuntimeEventType_RUNTIME_EVENT_DRIFT_DETECTED     RuntimeEventType = 9
)

// Enum value maps for RuntimeEventType.
var (
	RuntimeEventType_name = map[int32]string{
		0: "RUNTIME_EVENT_UNSPECIFIED",
		1: "RUNTIME_EVENT_LAUNCHED",
		2: "RUNTIME_EVENT_PAUSED",
		3: "RUNTIME_EVENT_RESUMED",
		4: "RUNTIME_EVENT_STOPPED",
		5: "RUNTIME_EVENT_FORCE_STOPPED",
		6: "RUNTIME_EVENT_FAILED",
		7: "RUNTIME_EVENT_HEARTBEAT",
		8: "RUNTIME_EVENT_ARTIFACT_COLLECTED",
		9: "RUNTIME_EVENT_DRIFT_DETECTED",
	}
	RuntimeEventType_value = map[string]int32{
		"RUNTIME_EVENT_UNSPECIFIED":        0,
		"RUNTIME_EVENT_LAUNCHED":           1,
		"RUNTIME_EVENT_PAUSED":             2,
		"RUNTIME_EVENT_RESUMED":            3,
		"RUNTIME_EVENT_STOPPED":            4,
		"RUNTIME_EVENT_FORCE_STOPPED":      5,
		"RUNTIME_EVENT_FAILED":             6,
		"RUNTIME_EVENT_HEARTBEAT":          7,
		"RUNTIME_EVENT_ARTIFACT_COLLECTED": 8,
		"RUNTIME_EVENT_DRIFT_DETECTED":     9,
	}
)

func (x RuntimeEventType) Enum() *RuntimeEventType {
	p := new(RuntimeEventType)
	*p = x
	return p
}

func (x RuntimeEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_controller_proto_enumTypes[1].Descriptor()
}

func (RuntimeEventType) Type() protoreflect.EnumType {
	return &file_runtime_controller_proto_enumTypes[1]
}

func (x RuntimeEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeEventType.Descriptor instead.
func (RuntimeEventType) EnumDescriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{1}
}

type CorrelationContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId    string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	InteractionId  string                 `protobuf:"bytes,3,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	ExecutionId    string                 `protobuf:"bytes,4,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	FleetId        string                 `protobuf:"bytes,5,opt,name=fleet_id,json=fleetId,proto3" json:"fleet_id,omitempty"`
	GoalId         string                 `protobuf:"bytes,6,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	TraceId        string                 `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CorrelationContext) Reset() {
	*x = CorrelationContext{}
	mi := &file_runtime_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrelationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelationContext) ProtoMessage() {}

func (x *CorrelationContext) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelationContext.ProtoReflect.Descriptor instead.
func (*CorrelationContext) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{0}
}

func (x *CorrelationContext) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CorrelationContext) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *CorrelationContext) GetInteractionId() string {
	if x != nil {
		return x.InteractionId
	}
	return ""
}

func (x *CorrelationContext) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *CorrelationContext) GetFleetId() string {
	if x != nil {
		return x.FleetId
	}
	return ""
}

func (x *CorrelationContext) GetGoalId() string {
	if x != nil {
		return x.GoalId
	}
	return ""
}

func (x *CorrelationContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type ResourceLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuRequest    string                 `protobuf:"bytes,1,opt,name=cpu_request,json=cpuRequest,proto3" json:"cpu_request,omitempty"`
	CpuLimit      string                 `protobuf:"bytes,2,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryRequest string                 `protobuf:"bytes,3,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	MemoryLimit   string                 `protobuf:"bytes,4,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_runtime_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceLimits) GetCpuRequest() string {
	if x != nil {
		return x.CpuRequest
	}
	return ""
}

func (x *ResourceLimits) GetCpuLimit() string {
	if x != nil {
		return x.CpuLimit
	}
	return ""
}

func (x *ResourceLimits) GetMemoryRequest() string {
	if x != nil {
		return x.MemoryRequest
	}
	return ""
}

func (x *ResourceLimits) GetMemoryLimit() string {
	if x != nil {
		return x.MemoryLimit
	}
	return ""
}

type RuntimeContract struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	AgentRevision               string                 `protobuf:"bytes,1,opt,name=agent_revision,json=agentRevision,proto3" json:"agent_revision,omitempty"`
	ModelBinding                string                 `protobuf:"bytes,2,opt,name=model_binding,json=modelBinding,proto3" json:"model_binding,omitempty"`
	PolicyIds                   []string               `protobuf:"bytes,3,rep,name=policy_ids,json=policyIds,proto3" json:"policy_ids,omitempty"`
	CorrelationContext          *CorrelationContext    `protobuf:"bytes,4,opt,name=correlation_context,json=correlationContext,proto3" json:"correlation_context,omitempty"`
	ReasoningConfigJson         string                 `protobuf:"bytes,5,opt,name=reasoning_config_json,json=reasoningConfigJson,proto3" json:"reasoning_config_json,omitempty"`
	ContextEngineeringProfileId string                 `protobuf:"bytes,6,opt,name=context_engineering_profile_id,json=contextEngineeringProfileId,proto3" json:"context_engineering_profile_id,omitempty"`
	ReasoningBudgetEnvelopeJson string                 `protobuf:"bytes,7,opt,name=reasoning_budget_envelope_json,json=reasoningBudgetEnvelopeJson,proto3" json:"reasoning_budget_envelope_json,omitempty"`
	ResourceLimits              *ResourceLimits        `protobuf:"bytes,8,opt,name=resource_limits,json=resourceLimits,proto3" json:"resource_limits,omitempty"`
	SecretRefs                  []string               `protobuf:"bytes,9,rep,name=secret_refs,json=secretRefs,proto3" json:"secret_refs,omitempty"`
	EnvVars                     map[string]string      `protobuf:"bytes,10,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TaskPlanJson                string                 `protobuf:"bytes,11,opt,name=task_plan_json,json=taskPlanJson,proto3" json:"task_plan_json,omitempty"`
	StepId                      string                 `protobuf:"bytes,12,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *RuntimeContract) Reset() {
	*x = RuntimeContract{}
	mi := &file_runtime_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeContract) ProtoMessage() {}

func (x *RuntimeContract) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeContract.ProtoReflect.Descriptor instead.
func (*RuntimeContract) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{2}
}

func (x *RuntimeContract) GetAgentRevision() string {
	if x != nil {
		return x.AgentRevision
	}
	return ""
}

func (x *RuntimeContract) GetModelBinding() string {
	if x != nil {
		return x.ModelBinding
	}
	return ""
}

func (x *RuntimeContract) GetPolicyIds() []string {
	if x != nil {
		return x.PolicyIds
	}
	return nil
}

func (x *RuntimeContract) GetCorrelationContext() *CorrelationContext {
	if x != nil {
		return x.CorrelationContext
	}
	return nil
}

func (x *RuntimeContract) GetReasoningConfigJson() string {
	if x != nil {
		return x.ReasoningConfigJson
	}
	return ""
}

func (x *RuntimeContract) GetContextEngineeringProfileId() string {
	if x != nil {
		return x.ContextEngineeringProfileId
	}
	return ""
}

func (x *RuntimeContract) GetReasoningBudgetEnvelopeJson() string {
	if x != nil {
		return x.ReasoningBudgetEnvelopeJson
	}
	return ""
}

func (x *RuntimeContract) GetResourceLimits() *ResourceLimits {
	if x != nil {
		return x.ResourceLimits
	}
	return nil
}

func (x *RuntimeContract) GetSecretRefs() []string {
	if x != nil {
		return x.SecretRefs
	}
	return nil
}

func (x *RuntimeContract) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *RuntimeContract) GetTaskPlanJson() string {
	if x != nil {
		return x.TaskPlanJson
	}
	return ""
}

func (x *RuntimeContract) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

type RuntimeInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RuntimeId          string                 `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	ExecutionId        string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	State              RuntimeState           `protobuf:"varint,3,opt,name=state,proto3,enum=runtime_controller.v1.RuntimeState" json:"state,omitempty"`
	FailureReason      string                 `protobuf:"bytes,4,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	PodName            string                 `protobuf:"bytes,5,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	LaunchedAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=launched_at,json=launchedAt,proto3" json:"launched_at,omitempty"`
	LastHeartbeatAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	CorrelationContext *CorrelationContext    `protobuf:"bytes,8,opt,name=correlation_context,json=correlationContext,proto3" json:"correlation_context,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RuntimeInfo) Reset() {
	*x = RuntimeInfo{}
	mi := &file_runtime_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfo) ProtoMessage() {}

func (x *RuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfo.ProtoReflect.Descriptor instead.
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{3}
}

func (x *RuntimeInfo) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *RuntimeInfo) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *RuntimeInfo) GetState() RuntimeState {
	if x != nil {
		return x.State
	}
	return RuntimeState_RUNTIME_STATE_UNSPECIFIED
}

func (x *RuntimeInfo) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *RuntimeInfo) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *RuntimeInfo) GetLaunchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LaunchedAt
	}
	return nil
}

func (x *RuntimeInfo) GetLastHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return nil
}

func (x *RuntimeInfo) GetCorrelationContext() *CorrelationContext {
	if x != nil {
		return x.CorrelationContext
	}
	return nil
}

type RuntimeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	RuntimeId     string                 `protobuf:"bytes,2,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	EventType     RuntimeEventType       `protobuf:"varint,4,opt,name=event_type,json=eventType,proto3,enum=runtime_controller.v1.RuntimeEventType" json:"event_type,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	DetailsJson   string                 `protobuf:"bytes,6,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"`
	NewState      RuntimeState           `protobuf:"varint,7,opt,name=new_state,json=newState,proto3,enum=runtime_controller.v1.RuntimeState" json:"new_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeEvent) Reset() {
	*x = RuntimeEvent{}
	mi := &file_runtime_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEvent) ProtoMessage() {}

func (x *RuntimeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEvent.ProtoReflect.Descriptor instead.
func (*RuntimeEvent) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{4}
}

func (x *RuntimeEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RuntimeEvent) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *RuntimeEvent) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *RuntimeEvent) GetEventType() RuntimeEventType {
	if x != nil {
		return x.EventType
	}
	return RuntimeEventType_RUNTIME_EVENT_UNSPECIFIED
}

func (x *RuntimeEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *RuntimeEvent) GetDetailsJson() string {
	if x != nil {
		return x.DetailsJson
	}
	return ""
}

func (x *RuntimeEvent) GetNewState() RuntimeState {
	if x != nil {
		return x.NewState
	}
	return RuntimeState_RUNTIME_STATE_UNSPECIFIED
}

type LaunchRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      *RuntimeContract       `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchRuntimeRequest) Reset() {
	*x = LaunchRuntimeRequest{}
	mi := &file_runtime_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchRuntimeRequest) ProtoMessage() {}

func (x *LaunchRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchRuntimeRequest.ProtoReflect.Descriptor instead.
func (*LaunchRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{5}
}

func (x *LaunchRuntimeRequest) GetContract() *RuntimeContract {
	if x != nil {
		return x.Contract
	}
	return nil
}

type LaunchRuntimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeId     string                 `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	State         RuntimeState           `protobuf:"varint,2,opt,name=state,proto3,enum=runtime_controller.v1.RuntimeState" json:"state,omitempty"`
	WarmStart     bool                   `protobuf:"varint,3,opt,name=warm_start,json=warmStart,proto3" json:"warm_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchRuntimeResponse) Reset() {
	*x = LaunchRuntimeResponse{}
	mi := &file_runtime_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchRuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchRuntimeResponse) ProtoMessage() {}

func (x *LaunchRuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchRuntimeResponse.ProtoReflect.Descriptor instead.
func (*LaunchRuntimeResponse) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{6}
}

func (x *LaunchRuntimeResponse) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *LaunchRuntimeResponse) GetState() RuntimeState {
	if x != nil {
		return x.State
	}
	return RuntimeState_RUNTIME_STATE_UNSPECIFIED
}

func (x *LaunchRuntimeResponse) GetWarmStart() bool {
	if x != nil {
		return x.WarmStart
	}
	return false
}

type GetRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeRequest) Reset() {
	*x = GetRuntimeRequest{}
	mi := &file_runtime_controller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeRequest) ProtoMessage() {}

func (x *GetRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{7}
}

func (x *GetRuntimeRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetRuntimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtime       *RuntimeInfo           `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeResponse) Reset() {
	*x = GetRuntimeResponse{}
	mi := &file_runtime_controller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeResponse) ProtoMessage() {}

func (x *GetRuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeResponse.ProtoReflect.Descriptor instead.
func (*GetRuntimeResponse) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{8}
}

func (x *GetRuntimeResponse) GetRuntime() *RuntimeInfo {
	if x != nil {
		return x.Runtime
	}
	return nil
}

type PauseRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRuntimeRequest) Reset() {
	*x = PauseRuntimeRequest{}
	mi := &file_runtime_controller_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRuntimeRequest) ProtoMessage() {}

func (x *PauseRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRuntimeRequest.ProtoReflect.Descriptor instead.
func (*PauseRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{9}
}

func (x *PauseRuntimeRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type PauseRuntimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         RuntimeState           `protobuf:"varint,1,opt,name=state,proto3,enum=runtime_controller.v1.RuntimeState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRuntimeResponse) Reset() {
	*x = PauseRuntimeResponse{}
	mi := &file_runtime_controller_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRuntimeResponse) ProtoMessage() {}

func (x *PauseRuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRuntimeResponse.ProtoReflect.Descriptor instead.
func (*PauseRuntimeResponse) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{10}
}

func (x *PauseRuntimeResponse) GetState() RuntimeState {
	if x != nil {
		return x.State
	}
	return RuntimeState_RUNTIME_STATE_UNSPECIFIED
}

type ResumeRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRuntimeRequest) Reset() {
	*x = ResumeRuntimeRequest{}
	mi := &file_runtime_controller_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRuntimeRequest) ProtoMessage() {}

func (x *ResumeRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRuntimeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{11}
}

func (x *ResumeRuntimeRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type ResumeRuntimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         RuntimeState           `protobuf:"varint,1,opt,name=state,proto3,enum=runtime_controller.v1.RuntimeState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRuntimeResponse) Reset() {
	*x = ResumeRuntimeResponse{}
	mi := &file_runtime_controller_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRuntimeResponse) ProtoMessage() {}

func (x *ResumeRuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRuntimeResponse.ProtoReflect.Descriptor instead.
func (*ResumeRuntimeResponse) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{12}
}

func (x *ResumeRuntimeResponse) GetState() RuntimeState {
	if x != nil {
		return x.State
	}
	return RuntimeState_RUNTIME_STATE_UNSPECIFIED
}

type StopRuntimeRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId        string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	GracePeriodSeconds int32                  `protobuf:"varint,2,opt,name=grace_period_seconds,json=gracePeriodSeconds,proto3" json:"grace_period_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StopRuntimeRequest) Reset() {
	*x = StopRuntimeRequest{}
	mi := &file_runtime_controller_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRuntimeRequest) ProtoMessage() {}

func (x *StopRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRuntimeRequest.ProtoReflect.Descriptor instead.
func (*StopRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{13}
}

func (x *StopRuntimeRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *StopRuntimeRequest) GetGracePeriodSeconds() int32 {
	if x != nil {
		return x.GracePeriodSeconds
	}
	return 0
}

type StopRuntimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         RuntimeState           `protobuf:"varint,1,opt,name=state,proto3,enum=runtime_controller.v1.RuntimeState" json:"state,omitempty"`
	ForceKilled   bool                   `protobuf:"varint,2,opt,name=force_killed,json=forceKilled,proto3" json:"force_killed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRuntimeResponse) Reset() {
	*x = StopRuntimeResponse{}
	mi := &file_runtime_controller_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRuntimeResponse) ProtoMessage() {}

func (x *StopRuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRuntimeResponse.ProtoReflect.Descriptor instead.
func (*StopRuntimeResponse) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{14}
}

func (x *StopRuntimeResponse) GetState() RuntimeState {
	if x != nil {
		return x.State
	}
	return RuntimeState_RUNTIME_STATE_UNSPECIFIED
}

func (x *StopRuntimeResponse) GetForceKilled() bool {
	if x != nil {
		return x.ForceKilled
	}
	return false
}

type StreamRuntimeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRuntimeEventsRequest) Reset() {
	*x = StreamRuntimeEventsRequest{}
	mi := &file_runtime_controller_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRuntimeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRuntimeEventsRequest) ProtoMessage() {}

func (x *StreamRuntimeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRuntimeEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamRuntimeEventsRequest) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{15}
}

func (x *StreamRuntimeEventsRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *StreamRuntimeEventsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

type CollectRuntimeArtifactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectRuntimeArtifactsRequest) Reset() {
	*x = CollectRuntimeArtifactsRequest{}
	mi := &file_runtime_controller_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectRuntimeArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectRuntimeArtifactsRequest) ProtoMessage() {}

func (x *CollectRuntimeArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectRuntimeArtifactsRequest.ProtoReflect.Descriptor instead.
func (*CollectRuntimeArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{16}
}

func (x *CollectRuntimeArtifactsRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type ArtifactEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	CollectedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactEntry) Reset() {
	*x = ArtifactEntry{}
	mi := &file_runtime_controller_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactEntry) ProtoMessage() {}

func (x *ArtifactEntry) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactEntry.ProtoReflect.Descriptor instead.
func (*ArtifactEntry) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{17}
}

func (x *ArtifactEntry) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ArtifactEntry) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ArtifactEntry) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactEntry) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ArtifactEntry) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

type CollectRuntimeArtifactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*ArtifactEntry       `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Complete      bool                   `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectRuntimeArtifactsResponse) Reset() {
	*x = CollectRuntimeArtifactsResponse{}
	mi := &file_runtime_controller_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectRuntimeArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectRuntimeArtifactsResponse) ProtoMessage() {}

func (x *CollectRuntimeArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_controller_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectRuntimeArtifactsResponse.ProtoReflect.Descriptor instead.
func (*CollectRuntimeArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_runtime_controller_proto_rawDescGZIP(), []int{18}
}

func (x *CollectRuntimeArtifactsResponse) GetArtifacts() []*ArtifactEntry {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *CollectRuntimeArtifactsResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

var File_runtime_controller_proto protoreflect.FileDescriptor

const file_runtime_controller_proto_rawDesc = "" +
	"\n" +
	"\x18runtime_controller.proto\x12\x15runtime_controller.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n" +
	"\x12CorrelationContext\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12%\n" +
	"\x0einteraction_id\x18\x03 \x01(\tR\rinteractionId\x12!\n" +
	"\fexecution_id\x18\x04 \x01(\tR\vexecutionId\x12\x19\n" +
	"\bfleet_id\x18\x05 \x01(\tR\afleetId\x12\x17\n" +
	"\agoal_id\x18\x06 \x01(\tR\x06goalId\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\"\x98\x01\n" +
	"\x0eResourceLimits\x12\x1f\n" +
	"\vcpu_request\x18\x01 \x01(\tR\n" +
	"cpuRequest\x12\x1b\n" +
	"\tcpu_limit\x18\x02 \x01(\tR\bcpuLimit\x12%\n" +
	"\x0ememory_request\x18\x03 \x01(\tR\rmemoryRequest\x12!\n" +
	"\fmemory_limit\x18\x04 \x01(\tR\vmemoryLimit\"\xd2\x05\n" +
	"\x0fRuntimeContract\x12%\n" +
	"\x0eagent_revision\x18\x01 \x01(\tR\ragentRevision\x12#\n" +
	"\rmodel_binding\x18\x02 \x01(\tR\fmodelBinding\x12\x1d\n" +
	"\n" +
	"policy_ids\x18\x03 \x03(\tR\tpolicyIds\x12Z\n" +
	"\x13correlation_context\x18\x04 \x01(\v2).runtime_controller.v1.CorrelationContextR\x12correlationContext\x122\n" +
	"\x15reasoning_config_json\x18\x05 \x01(\tR\x13reasoningConfigJson\x12C\n" +
	"\x1econtext_engineering_profile_id\x18\x06 \x01(\tR\x1bcontextEngineeringProfileId\x12C\n" +
	"\x1ereasoning_budget_envelope_json\x18\a \x01(\tR\x1breasoningBudgetEnvelopeJson\x12N\n" +
	"\x0fresource_limits\x18\b \x01(\v2%.runtime_controller.v1.ResourceLimitsR\x0eresourceLimits\x12\x1f\n" +
	"\vsecret_refs\x18\t \x03(\tR\n" +
	"secretRefs\x12N\n" +
	"\benv_vars\x18\n" +
	" \x03(\v23.runtime_controller.v1.RuntimeContract.EnvVarsEntryR\aenvVars\x12$\n" +
	"\x0etask_plan_json\x18\v \x01(\tR\ftaskPlanJson\x12\x17\n" +
	"\astep_id\x18\f \x01(\tR\x06stepId\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x03\n" +
	"\vRuntimeInfo\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x01 \x01(\tR\truntimeId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x129\n" +
	"\x05state\x18\x03 \x01(\x0e2#.runtime_controller.v1.RuntimeStateR\x05state\x12%\n" +
	"\x0efailure_reason\x18\x04 \x01(\tR\rfailureReason\x12\x19\n" +
	"\bpod_name\x18\x05 \x01(\tR\apodName\x12;\n" +
	"\vlaunched_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"launchedAt\x12F\n" +
	"\x11last_heartbeat_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHeartbeatAt\x12Z\n" +
	"\x13correlation_context\x18\b \x01(\v2).runtime_controller.v1.CorrelationContextR\x12correlationContext\"\xd5\x02\n" +
	"\fRuntimeEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x02 \x01(\tR\truntimeId\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\x12F\n" +
	"\n" +
	"event_type\x18\x04 \x01(\x0e2'.runtime_controller.v1.RuntimeEventTypeR\teventType\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12!\n" +
	"\fdetails_json\x18\x06 \x01(\tR\vdetailsJson\x12@\n" +
	"\tnew_state\x18\a \x01(\x0e2#.runtime_controller.v1.RuntimeStateR\bnewState\"Z\n" +
	"\x14LaunchRuntimeRequest\x12B\n" +
	"\bcontract\x18\x01 \x01(\v2&.runtime_controller.v1.RuntimeContractR\bcontract\"\x90\x01\n" +
	"\x15LaunchRuntimeResponse\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x01 \x01(\tR\truntimeId\x129\n" +
	"\x05state\x18\x02 \x01(\x0e2#.runtime_controller.v1.RuntimeStateR\x05state\x12\x1d\n" +
	"\n" +
	"warm_start\x18\x03 \x01(\bR\twarmStart\"6\n" +
	"\x11GetRuntimeRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"R\n" +
	"\x12GetRuntimeResponse\x12<\n" +
	"\aruntime\x18\x01 \x01(\v2\".runtime_controller.v1.RuntimeInfoR\aruntime\"8\n" +
	"\x13PauseRuntimeRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"Q\n" +
	"\x14PauseRuntimeResponse\x129\n" +
	"\x05state\x18\x01 \x01(\x0e2#.runtime_controller.v1.RuntimeStateR\x05state\"9\n" +
	"\x14ResumeRuntimeRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"R\n" +
	"\x15ResumeRuntimeResponse\x129\n" +
	"\x05state\x18\x01 \x01(\x0e2#.runtime_controller.v1.RuntimeStateR\x05state\"i\n" +
	"\x12StopRuntimeRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x120\n" +
	"\x14grace_period_seconds\x18\x02 \x01(\x05R\x12gracePeriodSeconds\"s\n" +
	"\x13StopRuntimeResponse\x129\n" +
	"\x05state\x18\x01 \x01(\x0e2#.runtime_controller.v1.RuntimeStateR\x05state\x12!\n" +
	"\fforce_killed\x18\x02 \x01(\bR\vforceKilled\"q\n" +
	"\x1aStreamRuntimeEventsRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x120\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\"C\n" +
	"\x1eCollectRuntimeArtifactsRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\xcb\x01\n" +
	"\rArtifactEntry\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12=\n" +
	"\fcollected_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\"\x81\x01\n" +
	"\x1fCollectRuntimeArtifactsResponse\x12B\n" +
	"\tartifacts\x18\x01 \x03(\v2$.runtime_controller.v1.ArtifactEntryR\tartifacts\x12\x1a\n" +
	"\bcomplete\x18\x02 \x01(\bR\bcomplete*\xd3\x01\n" +
	"\fRuntimeState\x12\x1d\n" +
	"\x19RUNTIME_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RUNTIME_STATE_PENDING\x10\x01\x12\x19\n" +
	"\x15RUNTIME_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14RUNTIME_STATE_PAUSED\x10\x03\x12\x19\n" +
	"\x15RUNTIME_STATE_STOPPED\x10\x04\x12\x1f\n" +
	"\x1bRUNTIME_STATE_FORCE_STOPPED\x10\x05\x12\x18\n" +
	"\x14RUNTIME_STATE_FAILED\x10\x06*\xbd\x02\n" +
	"\x10RuntimeEventType\x12\x1d\n" +
	"\x19RUNTIME_EVENT_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RUNTIME_EVENT_LAUNCHED\x10\x01\x12\x18\n" +
	"\x14RUNTIME_EVENT_PAUSED\x10\x02\x12\x19\n" +
	"\x15RUNTIME_EVENT_RESUMED\x10\x03\x12\x19\n" +
	"\x15RUNTIME_EVENT_STOPPED\x10\x04\x12\x1f\n" +
	"\x1bRUNTIME_EVENT_FORCE_STOPPED\x10\x05\x12\x18\n" +
	"\x14RUNTIME_EVENT_FAILED\x10\x06\x12\x1b\n" +
	"\x17RUNTIME_EVENT_HEARTBEAT\x10\a\x12$\n" +
	" RUNTIME_EVENT_ARTIFACT_COLLECTED\x10\b\x12 \n" +
	"\x1cRUNTIME_EVENT_DRIFT_DETECTED\x10\t2\x9d\x06\n" +
	"\x15RuntimeControlService\x12j\n" +
	"\rLaunchRuntime\x12+.runtime_controller.v1.LaunchRuntimeRequest\x1a,.runtime_controller.v1.LaunchRuntimeResponse\x12a\n" +
	"\n" +
	"GetRuntime\x12(.runtime_controller.v1.GetRuntimeRequest\x1a).runtime_controller.v1.GetRuntimeResponse\x12g\n" +
	"\fPauseRuntime\x12*.runtime_controller.v1.PauseRuntimeRequest\x1a+.runtime_controller.v1.PauseRuntimeResponse\x12j\n" +
	"\rResumeRuntime\x12+.runtime_controller.v1.ResumeRuntimeRequest\x1a,.runtime_controller.v1.ResumeRuntimeResponse\x12d\n" +
	"\vStopRuntime\x12).runtime_controller.v1.StopRuntimeRequest\x1a*.runtime_controller.v1.StopRuntimeResponse\x12o\n" +
	"\x13StreamRuntimeEvents\x121.runtime_controller.v1.StreamRuntimeEventsRequest\x1a#.runtime_controller.v1.RuntimeEvent0\x01\x12\x88\x01\n" +
	"\x17CollectRuntimeArtifacts\x125.runtime_controller.v1.CollectRuntimeArtifactsRequest\x1a6.runtime_controller.v1.CollectRuntimeArtifactsResponseB_Z]github.com/andrea-mucci/musematic/services/runtime-controller/api/grpc/v1;runtimecontrollerv1b\x06proto3"

var (
	file_runtime_controller_proto_rawDescOnce sync.Once
	file_runtime_controller_proto_rawDescData []byte
)

func file_runtime_controller_proto_rawDescGZIP() []byte {
	file_runtime_controller_proto_rawDescOnce.Do(func() {
		file_runtime_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_controller_proto_rawDesc), len(file_runtime_controller_proto_rawDesc)))
	})
	return file_runtime_controller_proto_rawDescData
}

var file_runtime_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_runtime_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_runtime_controller_proto_goTypes = []any{
	(RuntimeState)(0),                       // 0: runtime_controller.v1.RuntimeState
	(RuntimeEventType)(0),                   // 1: runtime_controller.v1.RuntimeEventType
	(*CorrelationContext)(nil),              // 2: runtime_controller.v1.CorrelationContext
	(*ResourceLimits)(nil),                  // 3: runtime_controller.v1.ResourceLimits
	(*RuntimeContract)(nil),                 // 4: runtime_controller.v1.RuntimeContract
	(*RuntimeInfo)(nil),                     // 5: runtime_controller.v1.RuntimeInfo
	(*RuntimeEvent)(nil),                    // 6: runtime_controller.v1.RuntimeEvent
	(*LaunchRuntimeRequest)(nil),            // 7: runtime_controller.v1.LaunchRuntimeRequest
	(*LaunchRuntimeResponse)(nil),           // 8: runtime_controller.v1.LaunchRuntimeResponse
	(*GetRuntimeRequest)(nil),               // 9: runtime_controller.v1.GetRuntimeRequest
	(*GetRuntimeResponse)(nil),              // 10: runtime_controller.v1.GetRuntimeResponse
	(*PauseRuntimeRequest)(nil),             // 11: runtime_controller.v1.PauseRuntimeRequest
	(*PauseRuntimeResponse)(nil),            // 12: runtime_controller.v1.PauseRuntimeResponse
	(*ResumeRuntimeRequest)(nil),            // 13: runtime_controller.v1.ResumeRuntimeRequest
	(*ResumeRuntimeResponse)(nil),           // 14: runtime_controller.v1.ResumeRuntimeResponse
	(*StopRuntimeRequest)(nil),              // 15: runtime_controller.v1.StopRuntimeRequest
	(*StopRuntimeResponse)(nil),             // 16: runtime_controller.v1.StopRuntimeResponse
	(*StreamRuntimeEventsRequest)(nil),      // 17: runtime_controller.v1.StreamRuntimeEventsRequest
	(*CollectRuntimeArtifactsRequest)(nil),  // 18: runtime_controller.v1.CollectRuntimeArtifactsRequest
	(*ArtifactEntry)(nil),                   // 19: runtime_controller.v1.ArtifactEntry
	(*CollectRuntimeArtifactsResponse)(nil), // 20: runtime_controller.v1.CollectRuntimeArtifactsResponse
	nil,                                     // 21: runtime_controller.v1.RuntimeContract.EnvVarsEntry
	(*timestamppb.Timestamp)(nil),           // 22: google.protobuf.Timestamp
}
var file_runtime_controller_proto_depIdxs = []int32{
	2,  // 0: runtime_controller.v1.RuntimeContract.correlation_context:type_name -> runtime_controller.v1.CorrelationContext
	3,  // 1: runtime_controller.v1.RuntimeContract.resource_limits:type_name -> runtime_controller.v1.ResourceLimits
	21, // 2: runtime_controller.v1.RuntimeContract.env_vars:type_name -> runtime_controller.v1.RuntimeContract.EnvVarsEntry
	0,  // 3: runtime_controller.v1.RuntimeInfo.state:type_name -> runtime_controller.v1.RuntimeState
	22, // 4: runtime_controller.v1.RuntimeInfo.launched_at:type_name -> google.protobuf.Timestamp
	22, // 5: runtime_controller.v1.RuntimeInfo.last_heartbeat_at:type_name -> google.protobuf.Timestamp
	2,  // 6: runtime_controller.v1.RuntimeInfo.correlation_context:type_name -> runtime_controller.v1.CorrelationContext
	1,  // 7: runtime_controller.v1.RuntimeEvent.event_type:type_name -> runtime_controller.v1.RuntimeEventType
	22, // 8: runtime_controller.v1.RuntimeEvent.occurred_at:type_name -> google.protobuf.Timestamp
	0,  // 9: runtime_controller.v1.RuntimeEvent.new_state:type_name -> runtime_controller.v1.RuntimeState
	4,  // 10: runtime_controller.v1.LaunchRuntimeRequest.contract:type_name -> runtime_controller.v1.RuntimeContract
	0,  // 11: runtime_controller.v1.LaunchRuntimeResponse.state:type_name -> runtime_controller.v1.RuntimeState
	5,  // 12: runtime_controller.v1.GetRuntimeResponse.runtime:type_name -> runtime_controller.v1.RuntimeInfo
	0,  // 13: runtime_controller.v1.PauseRuntimeResponse.state:type_name -> runtime_controller.v1.RuntimeState
	0,  // 14: runtime_controller.v1.ResumeRuntimeResponse.state:type_name -> runtime_controller.v1.RuntimeState
	0,  // 15: runtime_controller.v1.StopRuntimeResponse.state:type_name -> runtime_controller.v1.RuntimeState
	22, // 16: runtime_controller.v1.StreamRuntimeEventsRequest.since:type_name -> google.protobuf.Timestamp
	22, // 17: runtime_controller.v1.ArtifactEntry.collected_at:type_name -> google.protobuf.Timestamp
	19, // 18: runtime_controller.v1.CollectRuntimeArtifactsResponse.artifacts:type_name -> runtime_controller.v1.ArtifactEntry
	7,  // 19: runtime_controller.v1.RuntimeControlService.LaunchRuntime:input_type -> runtime_controller.v1.LaunchRuntimeRequest
	9,  // 20: runtime_controller.v1.RuntimeControlService.GetRuntime:input_type -> runtime_controller.v1.GetRuntimeRequest
	11, // 21: runtime_controller.v1.RuntimeControlService.PauseRuntime:input_type -> runtime_controller.v1.PauseRuntimeRequest
	13, // 22: runtime_controller.v1.RuntimeControlService.ResumeRuntime:input_type -> runtime_controller.v1.ResumeRuntimeRequest
	15, // 23: runtime_controller.v1.RuntimeControlService.StopRuntime:input_type -> runtime_controller.v1.StopRuntimeRequest
	17, // 24: runtime_controller.v1.RuntimeControlService.StreamRuntimeEvents:input_type -> runtime_controller.v1.StreamRuntimeEventsRequest
	18, // 25: runtime_controller.v1.RuntimeControlService.CollectRuntimeArtifacts:input_type -> runtime_controller.v1.CollectRuntimeArtifactsRequest
	8,  // 26: runtime_controller.v1.RuntimeControlService.LaunchRuntime:output_type -> runtime_controller.v1.LaunchRuntimeResponse
	10, // 27: runtime_controller.v1.RuntimeControlService.GetRuntime:output_type -> runtime_controller.v1.GetRuntimeResponse
	12, // 28: runtime_controller.v1.RuntimeControlService.PauseRuntime:output_type -> runtime_controller.v1.PauseRuntimeResponse
	14, // 29: runtime_controller.v1.RuntimeControlService.ResumeRuntime:output_type -> runtime_controller.v1.ResumeRuntimeResponse
	16, // 30: runtime_controller.v1.RuntimeControlService.StopRuntime:output_type -> runtime_controller.v1.StopRuntimeResponse
	6,  // 31: runtime_controller.v1.RuntimeControlService.StreamRuntimeEvents:output_type -> runtime_controller.v1.RuntimeEvent
	20, // 32: runtime_controller.v1.RuntimeControlService.CollectRuntimeArtifacts:output_type -> runtime_controller.v1.CollectRuntimeArtifactsResponse
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_runtime_controller_proto_init() }
func file_runtime_controller_proto_init() {
	if File_runtime_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_controller_proto_rawDesc), len(file_runtime_controller_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_controller_proto_goTypes,
		DependencyIndexes: file_runtime_controller_proto_depIdxs,
		EnumInfos:         file_runtime_controller_proto_enumTypes,
		MessageInfos:      file_runtime_controller_proto_msgTypes,
	}.Build()
	File_runtime_controller_proto = out.File
	file_runtime_controller_proto_goTypes = nil
	file_runtime_controller_proto_depIdxs = nil
}
