clickhouse:
  replicaCount: 1
  keeper:
    enabled: false
  resources:
    requests:
      memory: 2Gi
      cpu: "1"
    limits:
      memory: 4Gi
      cpu: "2"

persistence:
  size: 20Gi

networkPolicy:
  enabled: false

backup:
  enabled: false
