{{- $existing := lookup "v1" "Secret" .Release.Namespace "qdrant-api-key" -}}
apiVersion: v1
kind: Secret
metadata:
  name: qdrant-api-key
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  QDRANT_API_KEY: {{ (and $existing $existing.data $existing.data.QDRANT_API_KEY | ternary ($existing.data.QDRANT_API_KEY | b64dec) (randAlphaNum 32)) | quote }}
