#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
from pathlib import Path

KEY_RE = re.compile(r"^(?P<indent>\s*)(?P<key>[A-Za-z0-9_.-]+):(?P<value>.*)$")


def extract_values(path: Path) -> list[tuple[str, str]]:
    stack: list[tuple[int, str]] = []
    rows: list[tuple[str, str]] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("- "):
            continue
        match = KEY_RE.match(raw_line)
        if not match:
            continue
        indent = len(match.group("indent"))
        key = match.group("key")
        value = match.group("value").strip()
        while stack and stack[-1][0] >= indent:
            stack.pop()
        current_path = ".".join([item[1] for item in stack] + [key])
        if value:
            rows.append((current_path, value))
        stack.append((indent, key))
    return rows


def chart_name(path: Path, root: Path) -> str:
    rel = path.relative_to(root)
    return rel.parts[0] if rel.parts else path.parent.name


def chart_dirs(root: Path) -> list[Path]:
    return sorted(path.parent for path in root.rglob("Chart.yaml"))


def refresh_chart_readmes(root: Path) -> None:
    helm_docs = shutil.which("helm-docs")
    if not helm_docs:
        return
    subprocess.run(
        [helm_docs, "--chart-search-root", str(root)],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )


def render_from_readmes(root: Path) -> str | None:
    charts = chart_dirs(root)
    if not charts:
        return None
    if not all((chart / "README.md").exists() for chart in charts):
        return None

    lines = [
        "# Helm Values",
        "",
        "This page is generated by `scripts/aggregate-helm-docs.py` from per-chart `helm-docs` README files.",
        "Run `helm-docs --chart-search-root=deploy/helm` before committing chart value changes.",
        "",
    ]
    for chart in charts:
        readme = (chart / "README.md").read_text(encoding="utf-8").splitlines()
        title = readme[0].lstrip("# ").strip() if readme else chart.name
        lines.extend([f"## {title}", ""])
        for line in readme[1:]:
            if line.startswith("# "):
                lines.append("### " + line[2:])
            elif line.startswith("## "):
                lines.append("### " + line[3:])
            elif line.startswith("### "):
                lines.append("#### " + line[4:])
            else:
                lines.append(line)
        lines.append("")
    return "\n".join(lines)


def render(root: Path) -> str:
    refresh_chart_readmes(root)
    rendered = render_from_readmes(root)
    if rendered is not None:
        return rendered

    lines = [
        "# Helm Values",
        "",
        "This page is generated by `scripts/aggregate-helm-docs.py` from Helm values files.",
        "Install `helm-docs` to refresh per-chart README files with richer descriptions.",
        "",
    ]
    values_files = sorted(root.rglob("values*.yaml"))
    for chart in sorted({chart_name(path, root) for path in values_files}):
        lines.extend([f"## {chart}", "", "| Values file | Key | Default |", "| --- | --- | --- |"])
        for path in [item for item in values_files if chart_name(item, root) == chart]:
            rel = path.relative_to(root).as_posix()
            rows = extract_values(path)
            if not rows:
                lines.append(f"| `{rel}` | - | - |")
                continue
            for key, value in rows:
                escaped = value.replace("|", "\\|")
                lines.append(f"| `{rel}` | `{key}` | `{escaped}` |")
        lines.append("")
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Aggregate Helm values documentation.")
    parser.add_argument("--chart-root", type=Path, default=Path("deploy/helm"))
    parser.add_argument("--output", type=Path)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    content = render(args.chart_root)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(content, encoding="utf-8")
    else:
        print(content, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
