mode: dev

policyJob:
  vaultAddr: http://musematic-vault.platform-security.svc.cluster.local:8200

vault:
  injector:
    enabled: false
  ui:
    enabled: true
    serviceType: ClusterIP
  server:
    extraEnvironmentVars: null
    dev:
      enabled: true
      devRootToken: root
    dataStorage:
      enabled: false
    auditStorage:
      enabled: false
    ha:
      enabled: false
