{{- $existing := lookup "v1" "Secret" .Release.Namespace "opensearch-credentials" -}}
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  OPENSEARCH_USERNAME: {{ .Values.credentials.username | quote }}
  OPENSEARCH_PASSWORD: {{ (and $existing $existing.data $existing.data.OPENSEARCH_PASSWORD | ternary ($existing.data.OPENSEARCH_PASSWORD | b64dec) .Values.credentials.password) | quote }}
