apiVersion: v1
kind: Service
metadata:
  name: clamav
  namespace: {{ .Values.namespace }}
  labels:
{{ include "musematic-clamav.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: clamd
      port: {{ .Values.service.port }}
      targetPort: 3310
      protocol: TCP
  selector:
{{ include "musematic-clamav.selectorLabels" . | indent 4 }}
