from __future__ import annotations

from pathlib import Path

content = """# OpenAPI Embeds

The interactive REST API page reads `openapi.json`, which is generated by
`scripts/export-openapi.py`.
"""

target = Path(__file__).resolve().parent / "api-reference/openapi-embeds.md"
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text(content, encoding="utf-8")
