opensearch:
  singleNode: true
  replicas: 1
  extraEnvs:
    - name: OPENSEARCH_JAVA_OPTS
      value: "-Xms512m -Xmx512m"
    - name: DISABLE_SECURITY_PLUGIN
      value: "true"
    - name: AWS_EC2_METADATA_DISABLED
      value: "true"
    - name: AWS_REGION
      value: "us-east-1"
    - name: AWS_DEFAULT_REGION
      value: "us-east-1"
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: minio-platform-credentials
          key: MINIO_ACCESS_KEY
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-platform-credentials
          key: MINIO_SECRET_KEY
  persistence:
    size: 5Gi
  resources:
    requests:
      cpu: "250m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

opensearch-dashboards:
  extraEnvs:
    - name: OPENSEARCH_HOSTS
      value: '["http://musematic-opensearch:9200"]'
    - name: DISABLE_SECURITY_DASHBOARDS_PLUGIN
      value: "true"

networkPolicy:
  enabled: true

initJob:
  opensearchUrl: "http://musematic-opensearch:9200"
