{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: musematic-neo4j
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: neo4j
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: platform-control
      ports:
        - protocol: TCP
          port: 7687
        - protocol: TCP
          port: 7474
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: platform-execution
      ports:
        - protocol: TCP
          port: 7687
        - protocol: TCP
          port: 7474
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: platform-observability
      ports:
        - protocol: TCP
          port: 7474
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: neo4j
      ports:
        - protocol: TCP
          port: 5000
        - protocol: TCP
          port: 7000
        - protocol: TCP
          port: 7687
{{- end }}
